### ISSUE TITLE
python3安装成功了，但是Python2一直不成功

### ISSUE THREAD

**Issue by dark-flame-master** [chenjiandongx/pyecharts#10]
错误代码如下：

E:\>pip2 install pyecharts --no-cache-dir
Collecting pyecharts
  Downloading pyecharts-0.1.5.tar.gz
    Complete output from command python setup.py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\
p.py", line 6, in <module>
        import pyecharts.__version__ as about
      File "pyecharts\__init__.py", line 5, in <m
        from pyecharts.charts.effectscatter impor
      File "pyecharts\charts\effectscatter.py", l
        from pyecharts.charts.scatter import Scat
      File "pyecharts\charts\scatter.py", line 7,
        import Image
    ImportError: No module named Image

    ----------------------------------------
Command "python setup.py egg_info" failed with er
\appdata\local\temp\pip-build-vdikyj\pyecharts\

环境是windows7 64位
我先装的python3的版本，然后安装的2，3安装运行都没有问题，但是2有错误提示，我看了一下，和某一个issue是类似的，Image有问题

**Comment by chenjiandongx** [comment]
关于 Image 的，试试 pip install Image

**Comment by dark-flame-master** [comment]
ok，解决了
