### ISSUE TITLE
xaxis_type='time'数据不呈现

### ISSUE THREAD

**Issue by sooluck** [chenjiandongx/pyecharts#101]
x列是格式化后的str:time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())
设置xaxis_type='time'后一个点都没有了，请问这个是有什么特殊的吗？

**Comment by chenjiandongx** [comment]
@sooluck 
这点我没有在文档中说明，如果将 time 转为 str 后，xaxis_type 的类型其实就相当于 category 了。但是 python 中的 datetime 类型在转换为 Js 所需的类型是有问题的。在 json 序列化的时候是会报错的，总结一句话就是目前 time 类型坐标轴是没有效果的，看看后期能不能解决吧。

**Comment by sooluck** [comment]
https://stackoverflow.com/questions/455580/json-datetime-between-python-and-javascript

是不是这个问题啊？

**Comment by chenjiandongx** [comment]
是的，我刚试了一下该问题提供的解决方案，现在可以转换 datetime.datetime, datetime.date 类型的了，谢谢

**Comment by sooluck** [comment]
也就是说目前没有办法用time属性吧？谢谢啦

**Comment by chenjiandongx** [comment]
是的

**Comment by FavorMylikes** [comment]
新版本解决这个问题了吗
