### ISSUE TITLE
用了Overlap以后无法使用Grid

### ISSUE THREAD

**Issue by kent119** [chenjiandongx/pyecharts#103]
环境：Ubuntu 16 + Docker + Jupyter Notebook
版本：0.1.9.5

想在notebook里画下面这种图，试了Page，结果只能生成html文件，Notebook里只显示 `<pyecharts.custom.page.Page at 0x7fea9ff1c390>`

但是用 Grid 的话，只能放没有经过overlap的图。如果要overlap之后再用Grid的话，就会提示：
`AttributeError: 'Overlap' object has no attribute '_option'`

请问有没有什么解决办法？

![image](https://user-images.githubusercontent.com/18453664/29399513-1bede5fc-835c-11e7-98bc-5d3375bcc275.png)

**Comment by chenjiandongx** [comment]
@kent119 
目前来说 overlap 和 grid 不能同时放在一起 不然会导致坐标轴索引混乱 看看后期能不能解决这个问题

**Comment by kent119** [comment]
@chenjiandongx 
那请问 page 能直接在Notebook中显示吗？

我现在用的是下面的方法，缺点是会有点卡，还得手动输入`page_height`。
```
# Embed page in Notebook
from IPython.display import IFrame
IFrame('./render.html', width="100%", height=page_height)
```

**Comment by chenjiandongx** [comment]
@kent119 
page 暂时还不能在 Notebook 中直接显示，因为使用的模板不同，看看后续版本可不可以解决这个问题。

**Comment by kent119** [comment]
@chenjiandongx 现在用page也是不得已的方法，其实我这里想做的效果是：
 上下两幅图可以一起显示，并且用同一个datazoom。

感觉像是两幅图各自overlap之后，再overlap；
或者是一个overlap中可以有多个坐标系，共用datazoom，然后add的时候选择与哪个坐标系overlap。

**Comment by chenjiandongx** [comment]
@kent119 
你这需求得加两倍价钱阿 老哥
