### ISSUE TITLE
WordCloud问题

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#104]
WordCloud是否可以自定义词云的图形样式？  比如人形、矩形、圆形等。

没有找到这个用法

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/29400731-fef68ff8-8360-11e7-82e9-d96fb10418f1.png)

**Comment by chenjiandongx** [comment]
@dengyingguo `symbol` 参数支持以 path 开头的 svg 图路径

**Comment by dengyingguo** [comment]
@chenjiandongx  不会……

我是程序小白，我是自学的python。  这个svg不会处理……不要笑话我

**Comment by chenjiandongx** [comment]
@dengyingguo https://www.w3.org/TR/SVG/paths.html#PathData  Echarts 官方推荐介绍，大家都是学习过来的。那你看着，issue 我关了
