### ISSUE TITLE
install error:No module named config

### ISSUE THREAD

**Issue by morgengu** [chenjiandongx/pyecharts#105]
python 2.7卸载0.1.9.4, 安装0.1.9.5时
显示错误如下

Collecting pyecharts
  Using cached pyecharts-0.1.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-tfmumo\pyecharts\setup.py", line 40, in <module>
        cmdclass=cmdclass(__jupyter_echarts__, enable="echarts/main"),
      File "C:\Python27\lib\site-packages\jupyterpip\__init__.py", line 51, in cmdclass
        from IPython.html.services.config import ConfigManager
    ImportError: No module named config

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-tfmumo\pyecharts
这个问题怎么解决？

**Comment by chenjiandongx** [comment]
`pip install notebook ` 然后再安装 pyecharts

**Comment by morgengu** [comment]
谢谢，安装 pyecharts前提示PIP也要先更新，然后问题解决了，感谢

**Comment by chfw** [comment]
I will start modifying jupyter-pip over night
