### ISSUE TITLE
Jupyter导出Html和Markdown Chart不显示，怎么处理？

### ISSUE THREAD

**Issue by youyoude** [chenjiandongx/pyecharts#107]
用Jupyter Notebook 在线显示 echart成功，导出 html 和markdown ，chart 都成了空白 ，怎么处理？

**Comment by chenjiandongx** [comment]
这个应该是正常的，pyecharts 的图形在 notebook 中显示的话 html 是要经过处理的。

**Comment by chfw** [comment]
@youyoude , 你能说说具体如何导出的？我可以看看。

**Comment by youyoude** [comment]
@chfw  就是用 jupyter notebook   文件下载为 html 的功能，下载后html 中  关于 js的 设置 如下
<script>
    require.config({
         paths:{
             echarts: '/nbextensions/echarts/echarts.min',
             echartsgl: '/nbextensions/echarts/echarts-gl.min',
             wordcloud: '/nbextensions/echarts/echarts-wordcloud.min',
             liquidfill: '/nbextensions/echarts/echarts-liquidfill.min',
             china: '/nbextensions/echarts/china'
         }
    });
显然是个 本地路径 ，能有办法从 notebook里把他改成 别的路径吗？

**Comment by chfw** [comment]
@youyoude , Thanks. Understood the problem. Initial solution will follow in this week. Stay tuned.

**Comment by chfw** [comment]
With the next version of pyecharts, you will be able to do so:

```
from pyecharts import Scatter3D, online

import random
online()  # <--
data = [[random.randint(0, 100), random.randint(0, 100), random.randint(0, 100)] for _ in range(80)]
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
scatter3D = Scatter3D("3D 散点图示例", width=1200, height=600)
scatter3D.add("", data, is_visualmap=True, visual_range_color=range_color)
scatter3D
```

With current version, there is a hack(scater3D._jshost='https://chfw.github.io/jupyter-echarts/echarts') but it is not recommended because _jshost is a protected attribute and is subjected to future change.

**Comment by youyoude** [comment]
Super！！! Thanks @chfw

**Comment by anyang001** [comment]
![default](https://user-images.githubusercontent.com/31056083/29646647-543bb9f6-88b7-11e7-868b-50ab682c556a.png)
0.1.9.7 无法import online

**Comment by chenjiandongx** [comment]
@anyang001 
是的 下个版本才会有 或者你也可以源码安装 就可以使用该新特性了

**Comment by chfw** [comment]
@anyang001 , please pay attention to this note: https://github.com/chenjiandongx/pyecharts/blob/master/docs/en-us/doc_for_pyechart_developer.md#why-the-folder-pyechartstemplatesjs-is-empty

**Comment by anyang001** [comment]
@chenjiandongx @chfw 谢谢！
