### ISSUE TITLE
Unable to pip install 0.1.9.5 version 

### ISSUE THREAD

**Issue by HarrisonCUI** [chenjiandongx/pyecharts#108]
Hey Chen, I couldn't use pip to install 0.1.9.5 version both in my terminal and pycharm...  it works fine if I clone it through GitHub ....But I use pycharm quite often so I really need some help

**Comment by HarrisonCUI** [comment]
BTW, 0.1.9.4 works fine

**Comment by chenjiandongx** [comment]
could you provide more detail?

**Comment by HarrisonCUI** [comment]
Sure, here is the error info when I install 

Collecting pyecharts
  Using cached pyecharts-0.1.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Collecting jupyter-pip
      Using cached jupyter-pip-0.3.tar.gz
    Installing collected packages: jupyter-pip
      Running setup.py install for jupyter-pip: started
        Running setup.py install for jupyter-pip: finished with status 'error'
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-build-sH9spA/jupyter-pip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-TiZ3Gt-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib
        creating build/lib/jupyterpip
        copying jupyterpip/__init__.py -> build/lib/jupyterpip
        running egg_info
        writing jupyter_pip.egg-info/PKG-INFO
        writing top-level names to jupyter_pip.egg-info/top_level.txt
        writing dependency_links to jupyter_pip.egg-info/dependency_links.txt
        warning: manifest_maker: standard file '-c' not found
    
        reading manifest file 'jupyter_pip.egg-info/SOURCES.txt'
        writing manifest file 'jupyter_pip.egg-info/SOURCES.txt'
        running install_lib
        creating /Library/Python/2.7/site-packages/jupyterpip
        error: could not create '/Library/Python/2.7/site-packages/jupyterpip': Permission denied
    
        ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-build-sH9spA/jupyter-pip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-TiZ3Gt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-build-sH9spA/jupyter-pip/
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-build-cTjEGw/pyecharts/setup.py", line 11, in <module>
        pip.main(['install', 'jupyter-pip']); cmdclass = importlib.import_module('jupyterpip').cmdclass
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named jupyterpip
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k8/zkl3z4nd55vdmbybqkhd24c40000gn/T/pip-build-cTjEGw/pyecharts/

**Comment by chenjiandongx** [comment]
on Linux os?

**Comment by HarrisonCUI** [comment]
Mac OS

**Comment by chenjiandongx** [comment]
能否采取管理员权限单独安装 jupyter-pip 试试看

**Comment by chenjiandongx** [comment]
Could you try to install jupyter-pip sparately with admin permissions？

**Comment by HarrisonCUI** [comment]
Fabulous, You are right, if I install Jupiter- pip first then  it will works... Thanks

**Comment by chenjiandongx** [comment]
👏 good!
