### ISSUE TITLE
Geo 的问题：

### ISSUE THREAD

**Issue by lolibasu1768** [chenjiandongx/pyecharts#109]
73 行左右 的 "name"：导致所有scatter都用了 attr 的最后一个元作为名字。没有细测，应该是这里的问题 
临时应用的话，可以在data 最后加一个空值 ("","")

       if type == "scatter":
            self._option.get('series').append({
                "type": type,
                "name": name,
                "coordinateSystem": 'geo',
                "symbol": chart['symbol'],
                "symbolSize": symbol_size,
                "data": _data,
                "label": chart['label'],
            })

**Comment by chenjiandongx** [comment]
这个问题早上刚解决了 https://github.com/chenjiandongx/pyecharts/blob/master/pyecharts/charts/geo.py 最后一行

**Comment by lolibasu1768** [comment]
噢，那就好，可能是我还没有更新吧。
还有，为什么不考虑直接在 Geo 上支持一下自定义的 地理坐标呢？

**Comment by chenjiandongx** [comment]
为了尽量方便用户吧 所以一开始加入尽量多的城市坐标 现在数量已达 630 个，如果你乐意也欢迎你贡献更多城市坐标。

**Comment by lolibasu1768** [comment]
改了一下，果然。各位的效率真是没得说
