### ISSUE TITLE
新版本无法安装

### ISSUE THREAD

**Issue by Jortana** [chenjiandongx/pyecharts#113]
使用`pip install pyecharts`报错

Complete output from command python setup.py egg_info:
    c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
      "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pip-build-4tcpt419\pyecharts\setup.py", line 40, in <module>
        cmdclass=cmdclass(__jupyter_echarts__, enable="echarts/main"),
      File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\jupyterpip\__init__.py", line 50, in cmdclass
        from IPython.html.nbextensions import install_nbextension
    ModuleNotFoundError: No module named 'IPython.html.nbextensions'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pip-build-4tcpt419\pyecharts\

使用`python setup.py install`时也有上面后半部分的报错

**Comment by chenjiandongx** [comment]
先执行 pip install notebook 再安装 pip install pyecharts==0.1.9.6 试试

**Comment by chfw** [comment]
Oh must be the jupyter-pip was old. and pyecharts should have demanded jupyter-pip==0.3.1

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/setup.py#L21

__requires__ = ['pillow', 'jinja2', 'future', 'jupyter-pip>=0.3.1']

**Comment by chfw** [comment]
hence, the alternative solution is: `pip install jupyter-pip==0.3.1`

**Comment by Jortana** [comment]
Thank you very much.
I have never install Jupyter-pip before.


在 2017年8月19日，21:44，jaska <notifications@github.com<mailto:notifications@github.com>> 写道：


https://github.com/chenjiandongx/pyecharts/blob/master/setup.py#L21

requires = ['pillow', 'jinja2', 'future', 'jupyter-pip>=0.3.1']

**Comment by chfw** [comment]
Oh, I see. Have you installed 0.1.9.5 before?

**Comment by Jortana** [comment]
Yep. Today I saw the now version, so I want to upgrade but failed.
Then I uninstall the old and install again but failed again.
Thanks to your help I can solve this problem.

在 2017年8月19日，21:53，jaska <notifications@github.com<mailto:notifications@github.com>> 写道：


Oh, I see. Have you installed 0.1.9.5 before?

**Comment by chfw** [comment]
Please verify using 0.1.9.7

**Comment by Jortana** [comment]
ok thanks

在 2017年8月20日，15:32，jaska <notifications@github.com<mailto:notifications@github.com>> 写道：


Please verify using 0.1.9.7
