### ISSUE TITLE
tooltip的一些疑问

### ISSUE THREAD

**Issue by sooluck** [chenjiandongx/pyecharts#119]
tooltip的使用例子有点少，所以产生了一些疑问。
from pyecharts import Line

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 10, 100]
v2 = [55, 60, 16, 20, 15, 80]
line = Line("折线图示例")
line.add("商家A", attr, v1, mark_point=["average"],tooltip_tragger='axis',tooltip_formatter='{a0} {b0} {c0}\n{a1} {b1} {c1}')
line.add("商家B", attr, v2, is_smooth=True, mark_line=["max", "average"],tooltip_tragger='axis')
line.show_config()
line.render()

测试代码如上，通过改变tooltip的参数出来的效果不尽相同，比如：
line.add("商家A", attr, v1, mark_point=["average"],tooltip_tragger='axis',tooltip_formatter='{a0} {b0} {c0}\n{a1} {b1} {c1}')
line.add("商家B", attr, v2, is_smooth=True, mark_line=["max", "average"],tooltip_tragger='axis')
![1](https://user-images.githubusercontent.com/28747831/29506412-0a86d38a-867e-11e7-9cf2-ac45d064ccbd.jpg)
但如果改成：
line.add("商家A", attr, v1, mark_point=["average"],tooltip_tragger='axis',tooltip_formatter='{a0} {b0} {c0}\n{a1} {b1} {c1}')
line.add("商家B", attr, v2, is_smooth=True, mark_line=["max", "average"],tooltip_tragger='axis',tooltip_formatter='{a0} {b0} {c0}\n{a1} {b1} {c1}')
![2](https://user-images.githubusercontent.com/28747831/29506430-23880c28-867e-11e7-8fd7-bfde6fe2acea.jpg)

甚至：
line.add("商家A", attr, v1, mark_point=["average"],tooltip_tragger='axis',tooltip_formatter='{a0} {b0} {c0}\n{a1} {b1} {c1}')
line.add("商家B", attr, v2, is_smooth=True, mark_line=["max", "average"])
就没有tooltip了：
![3](https://user-images.githubusercontent.com/28747831/29506456-4f3bad7a-867e-11e7-99b4-7275fe4d6568.jpg)

用得很疑惑，还望赐教。

**Comment by sooluck** [comment]
从图上来看我更倾向于第一种展现形式，在实际使用过程中确实就会很迷惑了。

**Comment by sooluck** [comment]
大概明白了，tooltip如果不设置formatter就会是第一种默认样式，而tooltip应该是line的一个子属性，不会跟series变化而变化。

**Comment by chenjiandongx** [comment]
每个 chart instance 只有一份 tooltip 设置
