### ISSUE TITLE
Bar图，x轴为时间，y轴为数量，要求鼠标触及，显示该数据的名称，请问怎么设置？

### ISSUE THREAD

**Issue by morgengu** [chenjiandongx/pyecharts#120]
如题，感谢哈

**Comment by chenjiandongx** [comment]
请查看 tooltips 相关设置 在通用配置项中有介绍

**Comment by morgengu** [comment]
我的意思是 该数据的名称也是另外一个数据list，怎添加ADD（）里面

**Comment by chenjiandongx** [comment]
请详细描述问题 或者贴上图片 不然我无法解答

**Comment by morgengu** [comment]
比如有一个订单数据，抬头是： 订单日期，订单金额，客户名称，客户地点。设x轴是订单日期,y轴是订单金额，怎么样在鼠标点到BAR中某个数据，显示另外的信息：客户名称，客户地点.
![capture](https://user-images.githubusercontent.com/30671457/29603072-00f9f304-87e3-11e7-802d-41b68e14422e.JPG)

**Comment by sooluck** [comment]
bar.add(客户名称[i]+':'+客户地点[i],x,y)

**Comment by sooluck** [comment]
感觉你这个需求用bar是不是完成不了？
一个替代的方法：
select distinct 客户名称 from table
select distinct 客户地点 from table
然后排列组合
select 订单日期,订单金额 from table where 客户地点='' and 客户名称=''
然后按照时间顺序：
bar.add(客户名称[i]+'客户地点[i]',x,y)

我sql不是很好，大概意思是这样。

**Comment by chenjiandongx** [comment]
@morgengu 我觉得 @sooluck 这个做法是可取的

**Comment by morgengu** [comment]
谢谢楼上两位建议，看来只这样了。如果我说，数据比较多， @chenjiandongx ,肯定还会说，要是一个样，写个循环吧，哈哈。话说，有没有准备搞个风骚的sankey图啊。

**Comment by chenjiandongx** [comment]
@morgengu 新增 sankey 图也不是说不可以

**Comment by chenjiandongx** [comment]
@morgengu 喏，风骚 Sankey
```python
import sys
import os
import json

from pyecharts import Sankey

PY2 = sys.version_info[0] == 2

if PY2:
    import codecs
    with codecs.open(os.path.join("..", "json", "energy.json"), "rb") as f:
        j = json.load(f)
else:
    with open(os.path.join("..", "json", "energy.json"), "r", encoding="utf-8") as f:
        j = json.load(f)
sankey = Sankey("桑基图示例", width=1200, height=600)
sankey.add("sankey", nodes=j['nodes'], links=j['links'], line_opacity=0.2,
           line_curve=0.5, line_color='source', is_label_show=True, label_pos='right')
sankey.render()
```
![image](https://user-images.githubusercontent.com/19553554/29649693-51436aee-88c8-11e7-98c5-52bb69003fdb.png)

**Comment by morgengu** [comment]
@chenjiandongx ,太效率了，感谢
