### ISSUE TITLE
添加数据库的支持

### ISSUE THREAD

**Issue by ideaplat** [chenjiandongx/pyecharts#122]
能否再flask、django里面添加数据库的支持，比如MySQL。这样通过MySQL的数据，可以直接显示。
另外在前端上能否添加bootstrap或者其他的框架？从而可以增加效果？

**Comment by chfw** [comment]
I don't think this library should become "God" package that does all things. The example codes of Flask and Django is to show how you can integrate it by yourself.

If you would like to have specailist libraries that do it for you , I would recommend you to checkout one of my libraries: https://github.com/pyexcel/pyexcel-echarts, which is still under development and is supposed to bring in tighter integration with databases and tabula data. Together with [pyexcel](https://github.com/pyexcel/pyexcel),  the database tables, and tabular data can be [visualized](http://django-excel.readthedocs.io/en/latest/#visualize-your-data).

**Comment by chenjiandongx** [comment]
@ideaplat  我也同意 @chfw 的看法，这个库应该有这个库所要关注的重点。
