### ISSUE TITLE
使用Overlap()时无法绘图，报错

### ISSUE THREAD

**Issue by Seedarchangel** [chenjiandongx/pyecharts#123]
同样的码，用0.9.5的pyecharts没有问题，更新到0.9.7时报错
`File "/Users/Desktop/MyProject/TuChart/MongoClient.py", line 92, in graphpage
    page.render()

  File "/Users/anaconda/lib/python2.7/site-packages/pyecharts/custom/page.py", line 39, in render
    dependencies = self._merge_dependencies()

  File "/User/anaconda/lib/python2.7/site-packages/pyecharts/custom/page.py", line 81, in _merge_dependencies

    dependencies = dependencies.union(chart._js_dependencies)
AttributeError: 'Overlap' object has no attribute '_js_dependencies''`

以下是我的源代码
```
overlap = Overlap()

close = zip(*a)[2]
candle = [[x[1], x[2], x[3], x[4]] for x in a]
candlestick = Kline(j[0] + "-" + j[2], width=width1*10/11, height = (height1*10/11) / len(items))
candlestick.add(j[0], time, candle, is_datazoom_show=True, datazoom_type="slider")
overlap.add(candlestick)

if len(close)>10:
    ma10 = calculateMa(close, 10)
    line1 = Line(title_color="#C0C0C0")
    line1.add(j[0] + "-" + "MA10", time, ma10)
    overlap.add(line1)

if len(close)>20:
    ma20 = calculateMa(close, 20)
    line2 = Line(title_color="#C0C0C0")
    line2.add(j[0] + "-" + "MA20", time, ma20)
    overlap.add(line2)

if len(close)>30:
    ma30 = calculateMa(close, 30)
    line3 = Line(title_color="#C0C0C0")
    line3.add(j[0] + "-" + "MA30", time, ma30)
    overlap.add(line3)

page.add(overlap)
```

**Comment by chenjiandongx** [comment]
@Seedarchangel 请贴上所有的代码

**Comment by Seedarchangel** [comment]
多谢，是指从github安装吗？

**Comment by chenjiandongx** [comment]
v0.2.0 版本已发布 请更新使用
