### ISSUE TITLE
https://chfw.github.io/jupyter-echarts/echarts 挂了

### ISSUE THREAD

**Issue by fengshaomin** [chenjiandongx/pyecharts#125]
host地址 https://chfw.github.io/jupyter-echarts/echarts  挂了。
麻烦问一下如何保持使用本地js的方案，我是前端小小白，用pyechart就是觉得简单，如果还要学一段前端的npm安装，便利性就打了折扣。

**Comment by chenjiandongx** [comment]
@fengshaomin 忽略这个新特性 就跟往常一样了

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/documentation.md#jupyter-notebook-输出问题

**Comment by chfw** [comment]
And unless you would like to develop jupyter-echarts, you will go to pub with `npm`. Otheriwse, you may well stay in Python camp.
