### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#126]
C:\Anaconda3>cd C:\Anaconda3\pyecharts-master

error: [WinError 2] 系统找不到指定的文件。: 'C:\\Anaconda3\\pyecharts-master\\pyecharts/templates/js/echarts'

js下没有echarts。

**Comment by chenjiandongx** [comment]
你是源码安装的吗？

**Comment by dengyingguo** [comment]
@chenjiandongx   我讲下具体方式

我将pyecharts下载下来解压之后，用cmd来安装的。我打开js文件夹看了，下面也是空文件

**Comment by chenjiandongx** [comment]
```
$ git clone --recursive https://github.com/chenjiandongx/pyecharts.git
$ cd pyecharts
$ python setup.py install
```
请按照这个步骤来

**Comment by dengyingguo** [comment]
@chenjiandongx   没用你这个方法，

我用下面的方法解决了。
C:\Anaconda3>python -m pip install https://github.com/chenjiandongx/pyecharts/archive/master.zip

**Comment by chenjiandongx** [comment]
ok 解决了就好

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/documentation.md#jupyter-notebook-输出问题
