### ISSUE TITLE
能否实现Recharts的数据图切换功能

### ISSUE THREAD

**Issue by jaystone776** [chenjiandongx/pyecharts#127]
Recharts也是基于Echarts的，不过是R语言用的，会实现图上面有一堆按钮，可以快速切换数据视图、柱形图平铺、堆栈、折线图切换这些功能，不知道pyecharts是否也可以加上。没法截图，发个链接看看
https://madlogos.github.io/recharts/Basic_Plots_03_Line_cn.html#-en

**Comment by chenjiandongx** [comment]
暂时不会考虑 或者你考虑提供一下实现 PR？ :)

**Comment by chenjiandongx** [comment]
@jaystone776 请更新到 0.2.1 版本使用该新特性，`pip install pyecharts==0.2.1`

**Comment by chfw** [comment]
I am afraid I don't get much benefit from the added buttons :(. Only data button do something. But other buttons has no effect. And the tooltip of the button overlaps the icon below.

```
from pyecharts import Radar

schema = [ 
    ("Sales", 6500), ("Administration", 16000), ("IT", 30000), ("Customer Service", 38000), ("Research", 52000), ("Marketing", 25000)]
v1 = [[4300, 10000, 28000, 35000, 50000, 19000]]
v2 = [[5000, 14000, 28000, 31000, 42000, 21000]]
radar = Radar()
radar.config(schema)
radar.add("Budget", v1, is_splitline=True, is_axisline_show=True)
radar.add("Expenditure", v2, label_color=["#4e79a7"], is_area_show=False, legend_selectedmode='single')
radar.show_config()
radar.render()

```
<img width="480" alt="screen shot 2017-08-26 at 02 56 59" src="https://user-images.githubusercontent.com/4280312/29737695-530611f4-8a0a-11e7-8d8d-9d8f7cce3e19.png">

**Comment by chenjiandongx** [comment]
so, what's your suggestion?

**Comment by chfw** [comment]
Only show the buttons that does what it says.

**Comment by chenjiandongx** [comment]
Do you try to test other charts, like Bar, Line or Kline? On that charts,it look awesome.
