### ISSUE TITLE
'Line3D' object has no attribute 'get_js_dependencies'

### ISSUE THREAD

**Issue by Saliva520319** [chenjiandongx/pyecharts#128]
django那个，我用ipython看没找到这个方法

**Comment by chenjiandongx** [comment]
你好 请问你使用的是哪个版本的 pyecharts，可使用 pyecharts.__version__ 查看

**Comment by chenjiandongx** [comment]
v0.2.0 版本已发布 请更新使用

**Comment by Saliva520319** [comment]
我连看你代码里吧这个改成_js_dependencies就可以了。代码里Line3D有这个set属性。

**Comment by Saliva520319** [comment]
0.1.9.7，阿里云镜像自动更新的就是这个。那个依赖也有问题，我就自己加的本地静态文件echarts和echarts-gl

**Comment by chenjiandongx** [comment]
使用最新版吧 优化了很多东西

**Comment by Saliva520319** [comment]
好的 @chenjiandongx
