### ISSUE TITLE
简直屌爆了，非常感谢！

### ISSUE THREAD

**Issue by tcsds** [chenjiandongx/pyecharts#13]
非常感谢，一直想用Echarts ，不过我不会JS，也不想学，有这个包真是太好了。
有点小疑问，怎么做Echarts3.0示例中的图呢？例如，http://gallery.echartsjs.com/editor.html?c=xB1ffK8XUZ。
非常感谢。

**Comment by chenjiandongx** [comment]
嗯 你好 你给的链接无效

**Comment by tcsds** [comment]
实际上就是echarts-GL的图，比如：http://gallery.echartsjs.com/editor.html?c=xrJHCfsfE-
觉得很酷炫~~~谢谢

**Comment by chenjiandongx** [comment]
GL 的图有的确实很酷炫，这种暂时还没能用 pyecharts 实现。
