### ISSUE TITLE
树图

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#132]
是否会考虑树图功能呢

**Comment by chenjiandongx** [comment]
后续版本可以考虑加入

**Comment by dengyingguo** [comment]
@chenjiandongx   谢谢。

**Comment by chenjiandongx** [comment]
@dengyingguo 所以你 https://github.com/chenjiandongx/pyecharts/issues/104 的问题解决了吗 请及时回复

**Comment by chenjiandongx** [comment]
@dengyingguo 新版本 v0.2.6 已发布，请更新使用

**Comment by zhdhhh** [comment]
大佬 我不想要矩形树图，如何设置为树图呢？万分感谢。。。
