### ISSUE TITLE
0.2.1 移动鼠标光标在图例上柱形图都不显示数据标签了

### ISSUE THREAD

**Issue by zhangyi7456** [chenjiandongx/pyecharts#133]
如题，折线图依旧正常显示。只是所有柱形图都不再显示了，

**Comment by chenjiandongx** [comment]
我这边都是能正常显示的

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/29739302-ff6be2c2-8a6c-11e7-97a3-73ded4ae1750.png)

**Comment by zhangyi7456** [comment]
不是，是光标放在图例上，以前都是显示的

**Comment by chenjiandongx** [comment]
好的 我会解决这个问题的

**Comment by chenjiandongx** [comment]
终于找到问题了，echarts 版本的问题，新版本将 echarts 更新到了官方最新的 3.7.0 导致了这个问题

**Comment by zhangyi7456** [comment]
折线图不受影响，所有柱形图都扑街了，很喜欢用这个功能

**Comment by chenjiandongx** [comment]
放心 会修复的

**Comment by zhangyi7456** [comment]
赞，加油看好你

**Comment by chenjiandongx** [comment]
做个调查，喜欢新增的工具栏吗？

**Comment by zhangyi7456** [comment]
挺好的，我用这个库做报告，所以对表格有需求，之前是在副标题用换行符堆数据，

**Comment by chenjiandongx** [comment]
[pyecharts-0.2.1.tar.gz](https://github.com/chenjiandongx/pyecharts/files/1253477/pyecharts-0.2.1.tar.gz)
下载这个包 然后用 pip 安装试一下

**Comment by chfw** [comment]
Here is the new features of 3.7.0: https://github.com/ecomfe/echarts/releases/tag/3.7.0

**Comment by chenjiandongx** [comment]
@chfw 我更改了本地的 git submodule，但是没有权限推送不上去远程仓库，现在 Travis Ci 都不通过了 😂

**Comment by chfw** [comment]
Hey, please have a look at the picture below. echarts version is 3.7.0. I have them displayed OK. Where is the problem?

<img width="831" alt="screen shot 2017-08-26 at 23 04 03" src="https://user-images.githubusercontent.com/4280312/29745465-0953d06a-8ab3-11e7-8d40-a8369b2879fd.png">

<img width="966" alt="screen shot 2017-08-26 at 23 06 15" src="https://user-images.githubusercontent.com/4280312/29745476-33e2ef82-8ab3-11e7-9baa-24317a0bf3e1.png">

**Comment by chenjiandongx** [comment]
@chfw 
1.Bar图的话是点击上面的图例 现在不显示数据了 不是指 tooltip
2.guage图的话是现在标签+刻度都不显示了
![image](https://user-images.githubusercontent.com/19553554/29747103-f1b31588-8b20-11e7-8605-3a373ac23387.png)
3.其他肯定还是有一些问题的 只是暂时没发现而已

主要原因是 3.7.0 的部分接口重新整合了，测试是肯定不会报错的，数据又没误。

**Comment by huangyux1025** [comment]
![image](https://user-images.githubusercontent.com/31463771/29854669-0e2948bc-8d7a-11e7-9016-1e0b21407640.png)
云词图也有出现颜色问题，但是鼠标选中其中一个圆点中会有颜色出来，可能也是版本问题，
仪表盘不显示数字问题，如果用IE浏览器打开是可以的。但是字体不对，是默认字体

**Comment by chenjiandongx** [comment]
@huangyux1025 
下个 release 的话会回退 Echarts 版本到 3.6.2 的，或者你可以尝试下上面回复我重新打的包

**Comment by chenjiandongx** [comment]
版本请更新，请及时更新使用
