### ISSUE TITLE
The description of the program in English

### ISSUE THREAD

**Issue by Meantub** [chenjiandongx/pyecharts#14]
Original: "Python Echarts Potting Library"

"Potting" is meant to be "Plotting"

New: "Python Echarts Plotting Library"

**Comment by chenjiandongx** [comment]
thanks, now description is "Python Echarts Plotting Library"

**Comment by mgaitan** [comment]
@chenjiandongx the lib seems astonishing, you should consider to start document it in english to boost its popularity and user base, and find contributors.
