### ISSUE TITLE
Django中可否使用render方法加载进templates中定义的文件？

### ISSUE THREAD

**Issue by sailf** [chenjiandongx/pyecharts#140]
def index(request):
    # template = loader.get_template('myfirstvis/pyecharts.html')
    fun=funel()
    context = dict(
        myechart=fun.render_embed(),
        host='http://yun.chunfans.com/echarts',
        script_list=fun.get_js_dependencies()
    )
    return render(request, 'pyecharts.html', locals())

**Comment by chenjiandongx** [comment]
目前好像没有这种操作

**Comment by chfw** [comment]
不明白。能进一步说说具体是什么意思吗?

**Comment by sailf** [comment]
@chenjiandongx @chfw 大概看了下  我想要的是类似这个功能 问题没描述清楚 https://github.com/kinegratii/django-echarts/issues/1

**Comment by chfw** [comment]
了解。pyecharts能把base._options变成public.然后，后面发生什么可以留给开发人员。是这个意思吗？

**Comment by chenjiandongx** [comment]
@sailf 已提供 options 参数，封装返回 self._option
