### ISSUE TITLE
瀑布图

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#141]
考虑加瀑布图不

**Comment by chenjiandongx** [comment]
没记错的话，树图也是你提的 issue 吧 :)

**Comment by dengyingguo** [comment]
嗯嗯，

**Comment by chenjiandongx** [comment]
@dengyingguo 瀑布图 跟 主题河流图（ThemeRiver） 是一个意思吗？

**Comment by dengyingguo** [comment]
![image](https://user-images.githubusercontent.com/24351777/29905401-1799c698-8e41-11e7-94c8-ff74c56b6db5.png)

**Comment by dengyingguo** [comment]
瀑布图是这种，和河流图不太一样。

**Comment by chenjiandongx** [comment]
这种其实只是使用了 柱状图，设置了 `is_stack` 属性为 True，并且其中一个 `add()` 方法的颜色设置为透明而已

**Comment by chenjiandongx** [comment]
@dengyingguo 我给你个简单示例吧
```
from pyecharts import Bar

attr = ["{}月".format(i) for i in range(1, 8)]
v1 = [0, 100, 200, 300, 400, 220, 250]
v2 = [1000, 800, 600, 500, 450, 400, 300]
bar = Bar("瀑布图示例")
bar.add("", attr, v1, label_color=['rgba(0,0,0,0)'], is_stack=True)
bar.add("", attr, v2, is_label_show=True, is_stack=True)
bar.render()
```
![image](https://user-images.githubusercontent.com/19553554/29906037-d1d6d1e2-8e44-11e7-8894-550c378c98ac.png)

**Comment by dengyingguo** [comment]
@chenjiandongx 谢谢
