### ISSUE TITLE
关系图，不显示“连线”

### ISSUE THREAD

**Issue by sanshanxiashi** [chenjiandongx/pyecharts#143]
我运行如下代码：
from pyecharts import Graph

nodes = [{"name": "结点1", "symbolSize": 10},
         {"name": "结点2", "symbolSize": 20},
         {"name": "结点3", "symbolSize": 30},
         {"name": "结点4", "symbolSize": 40},
         {"name": "结点5", "symbolSize": 50},
         {"name": "结点6", "symbolSize": 40},
         {"name": "结点7", "symbolSize": 30},
         {"name": "结点8", "symbolSize": 20}]
links = []
for i in nodes:
    for j in nodes:
        links.append({"source": i.get('name'), "target": j.get('name')})
graph = Graph("关系图-力引导布局示例")
graph.add("", nodes, links, repulsion=8000)
graph.render()

可是，只有节点，没有连线，是咋回事？

![image](https://user-images.githubusercontent.com/10112380/29920460-23e2f458-8e80-11e7-8374-4a8e404aa5b7.png)

**Comment by chenjiandongx** [comment]
可以自行设置 line_color 属性，如 line_color='#aaa'

**Comment by sanshanxiashi** [comment]
😔晕，居然默认是白色啊

**Comment by chenjiandongx** [comment]
@sanshanxiashi 
惊不惊喜 ：)

**Comment by sanshanxiashi** [comment]
惊喜得我放弃pyecharts，去自己写echarts啦。。

**Comment by sanshanxiashi** [comment]
@chenjiandongx 你的qq可以加一下吗？

**Comment by chenjiandongx** [comment]
😂 怪我，怪我，pyecharts 还是挺方便的

**Comment by sanshanxiashi** [comment]
@chenjiandongx 是挺方便的，字词！

**Comment by chenjiandongx** [comment]
@sanshanxiashi 
用邮箱吧

**Comment by sanshanxiashi** [comment]
@chenjiandongx 为啥我拖拽一个节点的时候，整个图都会动啊？能不能拖拽一个点，线伸长？

**Comment by chenjiandongx** [comment]
不知道 好像没有这种操作
