### ISSUE TITLE
无法添加地图

### ISSUE THREAD

**Issue by haown1992** [chenjiandongx/pyecharts#144]
按照文档所示添加地图，没有报错，但是就是无法显示。不论是在notebook还是保存图片在本地都一样。（notebook已按照文档方法启用了）

**Comment by chfw** [comment]
请告知具体情况，python version, 可复现的代码。以下是从https://github.com/chenjiandongx/pyecharts/issues/97贴过来的：

Try: refresh your page and then click 'Cell->Run all'. Please also remember that: **each failed page will be cached for 10 minutes by Jupyter**. So either you could open a new test page and run the same code again or wait for a while and come back.

And if echarts has been installed well, you can test it using this link: 
http://localhost:8888/nbextensions/echarts/echarts.min.js

Debug: right click on the big white area. Please show me the <script>...</script> area.
<img width="597" alt="screen shot 2017-08-16 at 09 17 29" src="https://user-images.githubusercontent.com/4280312/29354092-4c4eecee-8264-11e7-98bb-06ec1b4c06b6.png">

**Comment by haown1992** [comment]
![image](https://user-images.githubusercontent.com/23076943/29938135-5849270a-8eba-11e7-873d-eb005362df03.png)
![image](https://user-images.githubusercontent.com/23076943/29938356-1137e832-8ebb-11e7-85b4-3db056f15304.png)

python 3.6.1

感谢您的回复~~

**Comment by haown1992** [comment]
啊，非常感谢~~
其实我一开始是加载深圳的地图的，发现出了问题才按照文档所示加载太原，想看看是不是自己操作错误，怎料太原也出错了~~~我升级到2.2.0 试试看
其次， http://localhost:8888/nbextensions/echarts/taiyuan_detail.js 打开后如下：
![image](https://user-images.githubusercontent.com/23076943/29939093-516b424e-8ebd-11e7-89a8-77eacc545ed5.png)

再次感谢您的帮助~~

**Comment by chfw** [comment]
问题找到了，请把`registerMap('taiyuan'`改成`registerMap('太原‘｀，然后再装一遍nbextensions

**Comment by chfw** [comment]
颗粒度超过了我的理解能力。现在是细分到了二线城市。再放大下一级是县区，这个工作两比较大。二线城市花了我一星期的业余时间。

**Comment by haown1992** [comment]
非常感谢您的无私奉献~~真的很高兴遇到你们这样无私的开发者~ @chfw

**Comment by chenjiandongx** [comment]
@haown1992 
现在地图部分的文档已经更新，请移步至 https://github.com/chenjiandongx/pyecharts/blob/dev/docs/zh-cn/user-customize-map.md
