### ISSUE TITLE
在0.2.2版本中，is_data_zoom_show组件无法添加入Overlap中显示

### ISSUE THREAD

**Issue by Seedarchangel** [chenjiandongx/pyecharts#145]
相同的代码在0.2.1版本正常显示data_zoom,在0.2.2则不显示
源代码`
overlap = Overlap()#for k线

                close = zip(*a)[2]

                candle = [[x[1], x[2], x[3], x[4]] for x in a]

                candlestick = Kline(j[0] + "-" + j[2], width=width1*10/11, height = (height1*10/11)／len(items))

                candlestick.add(j[0], time, candle, is_datazoom_show=True,yaxis_interval = 1)

                overlap.add(candlestick)

                if len(close)>10:

                    ma10 = calculateMa(close, 10)

                    line1 = Line(title_color="#C0C0C0")

                    line1.add(j[0] + "-" + "MA10", time, ma10, is_datazoom_show=True)

                    overlap.add(line1)

                if len(close)>20:

                    ma20 = calculateMa(close, 20)

                    line2 = Line(title_color="#C0C0C0")

                    line2.add(j[0] + "-" + "MA20", time, ma20, is_datazoom_show=True)

                    overlap.add(line2)

                if len(close)>30:

                    ma30 = calculateMa(close, 30)

                    line3 = Line(title_color="#C0C0C0")

                    line3.add(j[0] + "-" + "MA30", time, ma30, is_datazoom_show=True)

                    overlap.add(line3)

                page.add(overlap)`

**Comment by zhangyi7456** [comment]
补充一下，是data_zoom在所有图都不显示新版本里

**Comment by chenjiandongx** [comment]
嗯，查出来了，这是我修改后落下的问题。已经更正

**Comment by chenjiandongx** [comment]
这个问题看起来还是挺严重的，要考虑推出个修复版本了

**Comment by chenjiandongx** [comment]
修复版本 v0.2.3 已推出，请更新使用
