### ISSUE TITLE
运行文档关系图示例出错

### ISSUE THREAD

**Issue by yhfwww** [chenjiandongx/pyecharts#146]
运行文档关系图示例出错:
具体是：图像显示节点之间没有连接线；HTML数据视图中显示

结点1	NaN
结点2	NaN
结点3	NaN
结点4	NaN
结点5	NaN
结点6	NaN
结点7	NaN
结点8	NaN

`from pyecharts import Graph

nodes = [{"name": "结点1", "symbolSize": 10},
         {"name": "结点2", "symbolSize": 20},
         {"name": "结点3", "symbolSize": 30},
         {"name": "结点4", "symbolSize": 40},
         {"name": "结点5", "symbolSize": 50},
         {"name": "结点6", "symbolSize": 40},
         {"name": "结点7", "symbolSize": 30},
         {"name": "结点8", "symbolSize": 20}]
links = []
for i in nodes:
    for j in nodes:
        links.append({"source": i.get('name'), "target": j.get('name')})
graph = Graph("关系图-力引导布局示例")
graph.add("", nodes, links, repulsion=8000)
graph.render()`

**Comment by chenjiandongx** [comment]
请使用 `pip install pyecharts==0.2.3` 安装最新版，就可以正常使用了

**Comment by yhfwww** [comment]
谢谢，有效解决！
