### ISSUE TITLE
颜色和字体大小

### ISSUE THREAD

**Issue by hushuhe** [chenjiandongx/pyecharts#148]
大神。求问下：
1.图例字体的颜色要如何设置？
2.雷达图的每个维度的文字描述，字体大小如何设置？

**Comment by chenjiandongx** [comment]
@hushuhe 
你好，目前这两个配置选项都没有。

**Comment by hushuhe** [comment]
@chenjiandongx  谢谢，辛苦大神了！

**Comment by chenjiandongx** [comment]
@hushuhe 
![image](https://user-images.githubusercontent.com/19553554/29997313-a7e12fd6-9042-11e7-82e1-28051f0a1bc4.png)

**Comment by hushuhe** [comment]
@chenjiandongx   成功使用，多谢！

**Comment by chenjiandongx** [comment]
新版本 v0.2.4 已发布
