### ISSUE TITLE
pyecharts 0.2.3导入报错

### ISSUE THREAD

**Issue by huangyux1025** [chenjiandongx/pyecharts#149]
![default](https://user-images.githubusercontent.com/31463771/29966765-f096bb4a-8f45-11e7-8ec6-65f754e2cb84.png)
安装没有问题，但是import pyecharts 报错，我还有其他的包要安装吗？
![default](https://user-images.githubusercontent.com/31463771/29967003-02a3a7de-8f47-11e7-8533-e18114c60f41.png)

**Comment by chenjiandongx** [comment]
·pip install pillow` 少了安装 pillow

**Comment by chfw** [comment]
奇怪了

**Comment by huangyux1025** [comment]
可以了，我删除了所有，相关包，再来一次就好了
![default](https://user-images.githubusercontent.com/31463771/29968120-c577625a-8f4c-11e7-9a5d-5c17f0d325a2.png)

**Comment by chenjiandongx** [comment]
@huangyux1025 
ok : ) enjoy it!
