### ISSUE TITLE
pyecharts+Django 生成的图表可以是响应式的吗？

### ISSUE THREAD

**Issue by JasonHanG** [chenjiandongx/pyecharts#150]
<img width="985" alt="2017-09-01 8 12 42" src="https://user-images.githubusercontent.com/22115196/29969278-f9972106-8f51-11e7-8145-190777e9c27f.png">  
问题是，chart.render_embed() 输出的图像，可以成为响应式的吗？    
当前情况是：结合bootstrap写的页面，一个row里面放两张图，图在初始化生成时候大小是默认的。   
最终的页面打开后，13寸小屏幕下，图就显示不全了，也没有滚动条，无法拖动看到后半部分（如上图）。虽然大屏幕24寸时显示ok,但貌似也是因为恰好一行两张图比较巧合能够排满而已。        
请问，这个情况有解决方案吗？或者是代码写的有问题（以我很初级的前端知识，这似乎和响应式有关？）

django template 文件中输出图像部分代码如下：
```
{% for chart in charts %}
    {% if not forloop.counter|divisibleby:2 %}
        <div class="row">
            <div class="col-md-6"> {{ charts|safe }}</div>
            {% else %}
            <div class="col-md-6"> {{ charts|safe }}</div>
        </div>
    {% endif %}
{% endfor %}
```

**Comment by chenjiandongx** [comment]
尝试一下在初始化图的时候使用 `width` 和 `height` 调整一下大小？

**Comment by kinegratii** [comment]
@JasonHanG 

可以将html结构换一种写法，目前展开后为
```
<div class="row">
    <div class="col-md-6">Chart1</div>
    <div class="col-md-6">Chart2</div>
</div>
<div class="row">
    <div class="col-md-6">Chart3</div>
<!-- 如果只有3的话，将不渲染以下两行-->
    <div class="col-md-6">Chart4</div>
</div>
```
这样还有一个问题，当charts为奇数时，HTML结构是错误，最后一行的 `<div class="row">`没有闭合标签。

可以改成以下写法

```
<div class="row">
    {% for chart in charts %}
        <div class="col-md-6"> {{ charts|safe }}</div>
    {% endfor %}
</div>
```
最终渲染的HTML代码如下：
```
<div class="row">
    <div class="col-md-6">Chart1</div>
    <div class="col-md-6">Chart2</div>
    <div class="col-md-6">Chart3</div>
    <div class="col-md-6">Chart4</div>
</div>
```
而这段代码是支持响应式的，即大屏每行2个，小屏每行一个。
