### ISSUE TITLE
0.2.2版的Grid()错误

### ISSUE THREAD

**Issue by haown1992** [chenjiandongx/pyecharts#151]
![image](https://user-images.githubusercontent.com/23076943/29971492-f8ec090c-8f5a-11e7-80ef-282e086c5478.png)
我在用到Grid时似乎出现了点问题，如下：
1.第一幅图的颜色我明明设置过了，但是在最终出现的图形上并没有体现出来。（不过单独显示的话是成功的）
2.两幅图的标题重叠了，正常来说应该是一图一个标题~~
感谢您的无私奉献~~

**Comment by chenjiandongx** [comment]
@haown1992 
1.第一个的话暂时建议在第一个 `line.add()` 的时候这样写，1label_color=['#698088', 'deepskyblue']`
2.这看来不是错误，你应该设置 `title_top` 让其中一个标题下移。看起来是重叠了

**Comment by haown1992** [comment]
啊~ 非常感谢您的回复~
1.第一个问题，在第一个 `line.add()` 这么写，似乎不行，不过令人开心的是在最后一个这么写是OK的~
2.这个确实是我疏忽了，我发现文档里确实有设置这个~ 耽误您时间了 不好意思

最后，再次感谢您的工作~

**Comment by chenjiandongx** [comment]
@haown1992 
刚才没细看你的代码，你的 grid.add() 是先加入的 bar，所以你应该在 bar 中设置 label_color=['#698088', 'deepskyblue'] 你再尝试一下

**Comment by chenjiandongx** [comment]
@haown1992 
如果每个提问题人都跟你一样有礼貌并且能及时跟进的话，我还是很乐意解答的

**Comment by chenjiandongx** [comment]
@haown1992 
如果每个提问题人都跟你一样有礼貌并且能及时跟进的话，我还是很乐意解答的

**Comment by haown1992** [comment]
@chenjiandongx 
是的，在bar中设置就完全没有问题了。
另，其他提问者或许是因困扰的问题没有解决而有些心烦吧~所以态度可能不好~ 相信大多数人都是非常感谢你们的贡献的~ 希望大神继续加油 等以后我技术有成也会像你们一样为开源社区贡献自己力量的~

**Comment by chenjiandongx** [comment]
加油
