### ISSUE TITLE
geo的坐标 not found 问题

### ISSUE THREAD

**Issue by dbdb5269** [chenjiandongx/pyecharts#152]
作者您好，我在pycharm +pyecharts0.2.3版本下执行

from pyecharts import Geo

data = [
("海门", 9),("鄂尔多斯", 12),("招远", 12),("舟山", 12),("齐齐哈尔", 14),("盐城", 15),
("赤峰", 16),("青岛", 18),("乳山", 18),("金昌", 19),("泉州", 21),("莱西", 21),
("日照", 21),("胶南", 22),("南通", 23),("拉萨", 24),("云浮", 24),("梅州", 25)...]
geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center",
width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=15, is_visualmap=True)
geo.show_config()
geo.render()
这段demo
输出了
海门 coordinates is not found
鄂尔多斯 coordinates is not found
招远 coordinates is not found
舟山 coordinates is not found
齐齐哈尔 coordinates is not found
盐城 coordinates is not found
赤峰 coordinates is not found
青岛 coordinates is not found
乳山 coordinates is not found
想问一下是为什么呢？
谢谢

**Comment by chenjiandongx** [comment]
请问你使用的是 Python2 吗？

**Comment by dbdb5269** [comment]
是的,OS X自带的Python 2.7.10

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/29995363-1094f7e8-901a-11e7-8987-dacefea64770.png)

**Comment by dbdb5269** [comment]
感谢您的帮助，十分感谢

**Comment by chenjiandongx** [comment]
enjoy it! :)

**Comment by dbdb5269** [comment]
![image](https://user-images.githubusercontent.com/13082701/29995516-7a400518-901d-11e7-9cf2-9d0e599d7070.png)
希望只能字体颜色从红色可以改成白色，红色是在不太好看

**Comment by dbdb5269** [comment]
![image](https://user-images.githubusercontent.com/13082701/29995524-9eff4be8-901d-11e7-989c-18604a04d71d.png)
希望红色字体可以改成白色或者其他字体，红色不是很好看

**Comment by chenjiandongx** [comment]
嗯.... 红色看起来好像确实不太好看，已采纳你的建议，下个版本开始将会变成白色。
