### ISSUE TITLE
饼图怎么在图上每一块显示数值大小呢？

### ISSUE THREAD

**Issue by ly1102** [chenjiandongx/pyecharts#155]
我找了文档也没有找到对应的说明，请问一下具体参数名是什么？

**Comment by chenjiandongx** [comment]
is_label_show 参数设置为 True 可以显示

**Comment by ly1102** [comment]
@chenjiandongx 那个只是显示了所占百分比，没有显示数值的大小，比如男女比例2000:1000，显示的66.7%和33.3%，需要鼠标放上去才显示2000和1000.

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/30012031-207b2a82-916f-11e7-83e4-38bae14adfaa.png)

**Comment by ly1102** [comment]
谢谢，之前没看懂这个，现在会了。

**Comment by ChenKevin0123** [comment]
你好，没看懂该怎么写？是pie.add()的时候参数多加一个label_formatter = 什么吗？
