### ISSUE TITLE
is_add_yaxis 添加第二根轴时第一根轴变形

### ISSUE THREAD

**Issue by Seedarchangel** [chenjiandongx/pyecharts#156]
此为只显示一条数据时
<img width="876" alt="screen shot 2017-09-03 at 3 52 57 pm" src="https://user-images.githubusercontent.com/27750749/30006539-0b67330c-90c0-11e7-98b6-67cf7f932d8d.png">
当显示第二条数据时第一条数据被变形
<img width="880" alt="screen shot 2017-09-03 at 3 52 48 pm" src="https://user-images.githubusercontent.com/27750749/30006542-1a7fe730-90c0-11e7-95fd-6e0027ac224a.png">
使用pyecharts 0.2.0没有出现这个问题。
源代码：
`overlap = Overlap()

                    form = [e[1] for e in a]

                    bar = Bar(j[0] + "-" + j[2], width=width1 * 10 / 11, height=(height1 * 10 / 11) /len(items))

                    bar.add(j[0] + "-" + j[2], time, form, is_datazoom_show=True,datazoom_type="slider",yaxis_min="dataMin", yaxis_max="dataMax")
                    
                    overlap.add(bar)

                    line = Line(j[0] + "price", width=width1 * 10 / 11, height=(height1 * 10 / 11) / len(items))
                    
                    price = [e[3] for e in a]
                    
                    line.add(j[0] + "price", time, price, is_datazoom_show=True, datazoom_type="slider",
                             yaxis_min="dataMin", yaxis_type="value")
                    
                    overlap.add(line,yaxis_index=1, is_add_yaxis=True)

                    page.add(overlap)`

**Comment by chenjiandongx** [comment]
你现在使用的是 pyecharts 的哪个版本

**Comment by Seedarchangel** [comment]
0.2.3

**Comment by chenjiandongx** [comment]
能否将数据打包发到我邮箱 我等下测试一下 这问题感觉有点奇怪

**Comment by chenjiandongx** [comment]
感觉是你增加了 y 轴 但是datazoom 没有指定新增的y轴共用一个datazoom 组件

**Comment by Seedarchangel** [comment]
好，源码在https://github.com/Seedarchangel/TuChart，你看看能不能直接下载，然后`main.py`。

**Comment by Seedarchangel** [comment]
这个情况用0.2.2之前的版本似乎没有出现过，请问有解决办法吗_(:з」∠)_

**Comment by chenjiandongx** [comment]
@Seedarchangel 
能否直接打包一份实时数据给我，我在这边测试一下。

**Comment by Seedarchangel** [comment]
好，我写个脚本

**Comment by chenjiandongx** [comment]
@Seedarchangel 
如果你将滑动块拉到至最大，也就是相当于没有到datazoom的情况，两个系列的图能否正常显示。

**Comment by Seedarchangel** [comment]
@chenjiandongx 还是一样的，不能正常显示

**Comment by Seedarchangel** [comment]
@chenjiandongx 我写了个脚本，但是数据错了，实在是太奇怪了

**Comment by chenjiandongx** [comment]
如果两个都撤销datazoom组件的话是不是就能正常显示了
数据错了具体值的是什么？

**Comment by Seedarchangel** [comment]
两个都撤销的话依旧没有差别，似乎不是datazoom的问题。数据错了是我脚本的问题啦，恐怕我项目里的码单独拿出来写还不太可行

**Comment by Seedarchangel** [comment]
使用0.2.0可以正常使用，画的图是这样的

<img width="884" alt="screen shot 2017-09-04 at 12 27 46 am" src="https://user-images.githubusercontent.com/27750749/30012746-ec606846-9107-11e7-80f3-1feaf232e002.png">

**Comment by chenjiandongx** [comment]
两个单独显示的话就是没问题 然后一并显示就会出现问题是吧 然后在之前的版本是正常的？

**Comment by Seedarchangel** [comment]
@chenjiandongx 是的

**Comment by Seedarchangel** [comment]
@chenjiandongx 
不介意加微信吗

seedarchangel
