### ISSUE TITLE
饼图在Grid下无法正常显示

### ISSUE THREAD

**Issue by ly1102** [chenjiandongx/pyecharts#157]
`
from pyecharts import Bar, Line, Scatter, EffectScatter, Grid, Pie

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar1 = Bar("柱状图示例")
bar1.add("商家A", attr, v1, is_stack=True, is_label_show=True)
# bar1.add("商家B", attr, v2, is_stack=True, legend_pos="80%")
bar2 = Bar("柱状图示例")
bar2.add("商家A", attr, v1, is_stack=True, is_label_show=True)
# bar2.add("商家B", attr, v2, is_stack=True, legend_pos="80%")
bar3 = Bar("柱状图示例")
bar3.add("商家A", attr, v1, is_stack=True, is_label_show=True)
# bar3.add("商家B", attr, v2, is_stack=True, legend_pos="80%")
bar4 = Bar("柱状图示例")
bar4.add("商家A", attr, v1, is_stack=True, is_label_show=True)
# bar4.add("商家B", attr, v2, is_stack=True, legend_pos="80%")

grid = Grid()
grid.add(bar1, grid_bottom="60%", grid_left="60%")
grid.add(bar2, grid_bottom="60%", grid_right="60%")
grid.add(bar3, grid_top="60%", grid_left="60%")
# grid.add(bar4, grid_top="60%", grid_right="60%")
grid.render()`
这个代码是从文档拷贝下来的，我想要一个页面用Grid显示3个图，会出现图相互重叠的情况，并且如果此时加上另一个类型的图，所有的图会无法显示出来。如这个代码显示的，现在的正常的几个图片，但是把第一个Bar()， 换成了Pie()， 页面就会出现异常。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/30011813-5de0129a-916d-11e7-9d50-da953df9e61d.png)

**Comment by ly1102** [comment]
哈哈哈哈，尴尬了
