### ISSUE TITLE
page或者grid的时候，可以放Timeline图吗？

### ISSUE THREAD

**Issue by nejinn** [chenjiandongx/pyecharts#158]
首先非常感谢作者。今天第一天接触。基本学完了。
有几个问题想请教一下
page或者grid的时候，可以放Timeline图吗？
page和grid可以混合用吗？因为grid支持图表类型有限，所以有这个想法。
toolbox功能不是所有的图都有的把？
顺便，希望echarts可以实现指标卡的功能。

**Comment by chenjiandongx** [comment]
@nejinn 
感谢你的提醒，从下个版本开始，Page 图将支持加入 Grid，Timeline，Overlap 图
![2017-09-04_18-42-46](https://user-images.githubusercontent.com/19553554/30023245-27f9d10a-91a1-11e7-8089-c873b95277e1.gif)

**Comment by chenjiandongx** [comment]
@nejinn 
toolbox 每种图都会提供基础两种工具，【下载】【数据视图】，剩余可以自己指定是否提供，因为不是其他不是所有图都有效。这点在文档中已经说明。

**Comment by nejinn** [comment]
@chenjiandongx 
您好，非常感谢您。
指标卡其实是一种直接显示指标跟数值的图。类似于只有2词的词云图。一个词是指标，一个词是数值。
不知道怎么放图，见谅。

**Comment by chenjiandongx** [comment]
贴图直接复制到评论区或者直接把图片拉到评论区即可

**Comment by nejinn** [comment]
![screenshot 3](https://user-images.githubusercontent.com/31615794/30040985-9f9fcc7e-9218-11e7-8b23-91f1337fe6a1.png)
这个样子的。
这里是2张指标卡。
