### ISSUE TITLE
jupyter下geo和map显示为空白

### ISSUE THREAD

**Issue by ziliwang** [chenjiandongx/pyecharts#159]
![image](https://user-images.githubusercontent.com/13744942/30045323-2d8d2ac8-9236-11e7-84ba-95997c0cad50.png)

**Comment by chenjiandongx** [comment]
maptype 改为 '广东' 试试

**Comment by sooluck** [comment]
maptype是广东不是四川。

**Comment by ziliwang** [comment]
一样的，没变化还是空白

**Comment by chenjiandongx** [comment]
你是通过什么方式安装的 pip 还是源码

**Comment by ziliwang** [comment]
![image](https://user-images.githubusercontent.com/13744942/30045955-e6c1d9c8-9239-11e7-97af-6955b12de994.png)

**Comment by ziliwang** [comment]
pip安装的

**Comment by chenjiandongx** [comment]
要不这样吧 你先卸载干净 然后再重新使用 `pip install pyecharts==0.2.3` 试试看

**Comment by ziliwang** [comment]
问题还在，我有两台机器，环境差不多，一台可以正常运行，一台不可以

**Comment by chenjiandongx** [comment]
如果真是这样 那就建议使用 readme 中说明的源码安装方式了 那种方式应该就没有问题

**Comment by ziliwang** [comment]
解决了谢谢。

**Comment by chfw** [comment]
装pyecharts之后再装jupyter notebook,然后运行notebook,会出现这个情况。因为没有jupyter notebook 情况下，jupyter notebook 扩展是不装的。

**Comment by ziliwang** [comment]
我的解决办法是把版本刷回1.9.5就正常了，2.3依旧存在

**Comment by chenjiandongx** [comment]
是这样的 0.2.3 版本需要确保机器已经安装了 notebook 环境 如果没用 请执行`pip install notebook ` 先安装 再通过pip 安装最新版的 pyecharts

**Comment by ziliwang** [comment]
环境已经装了jupyter，notebook也装了，执行`pip3 install notebook --upgrade`，后再`pip3 install pyecharts==0.2.3`

**Comment by chenjiandongx** [comment]
这样操作后还不行吗？ 有没试过源码安装？

**Comment by ziliwang** [comment]
试过，也是一样的

**Comment by chenjiandongx** [comment]
你用render()方法出来的文件也是不能正常显示吗 还是说只是jupyter 有问题

**Comment by ziliwang** [comment]
重新安装jupyter正常了，thx

**Comment by chenjiandongx** [comment]
0.2.3 版本正常运行了吗？

**Comment by ziliwang** [comment]
嗯，是的。应该是jupyter的问题，我卸载后重装一次就好了。建议geo能支持经纬度，城市太少了，做全球范围的展示，自建城市有点麻烦。

**Comment by chfw** [comment]
@ziliwang ，可以给发PR嘛。人多，智多。

**Comment by chenjiandongx** [comment]
@ziliwang 
首先，pyecharts 已经内置了全国 3000+ 个地区的经纬度坐标了。
其次，也已经提供了自定义地区坐标的功能。自己按需添加。
最后，如果你愿意，也可以来扩充地区列表。

**Comment by qindiandadudu** [comment]
@ziliwang 目前使用0.2.6版本也遇到了同样的问题     笔记本和台式机都是不能显示。难道只能重装jupyter吗？

**Comment by chfw** [comment]
@ziliwang, let's see what happened with your browsers first.
