### ISSUE TITLE
生成的render.html文件的<title>参数能不能添加呢？

### ISSUE THREAD

**Issue by ly1102** [chenjiandongx/pyecharts#160]
因为画太多图了，打开了很多，然后在浏览器上，看到的title全是ECharts，不容易区分，不知道是否可以在render函数加个page_title的参数。。。

**Comment by chenjiandongx** [comment]
你指的是使用 Page 的时候吗？

**Comment by chfw** [comment]
`<head><title>"my super cool echarts"</title></head>`

**Comment by chenjiandongx** [comment]
不过把 render 重新命名不就一个意思吗，也可以区分。都支持传入参数修改

**Comment by ly1102** [comment]
![image](https://user-images.githubusercontent.com/15363304/30060461-0358f6b6-9276-11e7-8bd7-90779de37af6.png)
像这样，虽然html的文件名不一样，但是在浏览器的标签栏，就全是ECharts。如果要修改title标签，应该用什么参数呢？我在Grid和bar等画图的render函数的参数没有看到设置page title的参数。

**Comment by sooluck** [comment]
这个在生成的html代码当中是在头部的
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>ECharts</title>`
如果pyecharts没有提供title参数修改的话，可以暂时用替换头部的方法来解决。

**Comment by chenjiandongx** [comment]
@ly1102 
那后续版本可以考虑增加个 page_title 或者 chart_title 参数。

**Comment by ly1102** [comment]
@chenjiandongx 恩恩，非常感谢~

**Comment by chenjiandongx** [comment]
```python
attr = ["{}月".format(i) for i in range(1, 8)]
v1 = [0, 100, 200, 300, 400, 220, 250]
v2 = [1000, 800, 600, 500, 450, 400, 300]
bar = Bar("瀑布图示例", page_title='my awesome charts')
bar.add("", attr, v1, label_color=['rgba(0,0,0,0)'], is_stack=True)
bar.add("月份", attr, v2, is_label_show=True, is_stack=True, label_pos='inside')
bar.render()
```
![image](https://user-images.githubusercontent.com/19553554/30063117-18cb91f2-9280-11e7-8c0d-ff085176e27b.png)

![image](https://user-images.githubusercontent.com/19553554/30063109-0fb944d8-9280-11e7-8d80-e41242f72e6f.png)

@ly1102 
如何？

**Comment by nejinn** [comment]
@chenjiandongx 
我发现现在就能改title

![_20170906155342](https://user-images.githubusercontent.com/31615794/30100572-e9f9ce88-931b-11e7-9f04-a71b9be4b076.png)

**Comment by chenjiandongx** [comment]
@nejinn 
当然可以，上面都已经有人说到了。只是提供参数的话方便一点。

**Comment by chfw** [comment]
@chenjiandongx , Page needs title too. Do you want a PR?

**Comment by chenjiandongx** [comment]
@chfw 
see the latest commit, i support it for Page too

**Comment by chenjiandongx** [comment]
新版本 v0.2.4 已发布

**Comment by ly1102** [comment]
@chenjiandongx 不好意思之前你的回复没有收到邮件，刚刚才看到你的回复。辛苦啦，更新得这么快~
