### ISSUE TITLE
python3+pyecharts0.2.3 Geo错误

### ISSUE THREAD

**Issue by tsunami12** [chenjiandongx/pyecharts#161]
#!/usr/bin/python
#!-*- coding:utf-8 -*-
from __future__ import unicode_literals
import os 
import cx_Oracle
from pyecharts import Geo
import json
os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8' 
db = cx_Oracle.connect('username/password@IP:1521/tydb')
cr = db.cursor()
sql1 = "ALTER TABLE YUANXI MODIFY CNAME VARCHAR2(50)"
sql2 = "INSERT INTO YUANXI VALUES('10730','兰州大学','甘肃','985')"
sql3 = "SELECT ADDRESS FROM YUANXI"
rs = cr.execute(sql3)
db.commit()
data = {}
for x in rs:
	# print(json.dumps(x,encoding = 'utf-8',ensure_ascii = False))
	if x in data.keys():
		data[x] += 1
	else:
		data[x] = 1
geo = Geo("985高校地区分布图")
attr, value = geo.cast(data)
geo.add("",attr,value,maptype = 'china')
geo.render()
cr.close()
db.close()

出现的错误：
北京 coordinates is not found
天津 coordinates is not found
湖南 coordinates is not found
陕西 coordinates is not found
辽宁 coordinates is not found
吉林 coordinates is not found
黑龙江 coordinates is not found
上海 coordinates is not found
江苏 coordinates is not found
浙江 coordinates is not found
安徽 coordinates is not found
福建 coordinates is not found
山东 coordinates is not found
湖北 coordinates is not found
四川 coordinates is not found
重庆 coordinates is not found
广东 coordinates is not found
甘肃 coordinates is not found
[Finished in 0.5s]

**Comment by chenjiandongx** [comment]
请把 attr 输出来看一下

**Comment by tsunami12** [comment]
[('北京',), ('天津',), ('湖南',), ('陕西',), ('辽宁',), ('吉林',), ('黑龙江',), ('上海',), ('江苏',), ('浙江',), ('安徽',), ('福建',), ('山东',), ('湖北',), ('四川',), ('重庆',), ('广东',), ('甘肃',)]

发送自 Windows 10 版邮件应用

发件人: chenjiandongx
发送时间: 2017年9月6日 16:19
收件人: chenjiandongx/pyecharts
抄送: tsunami12; Author
主题: Re: [chenjiandongx/pyecharts] python3+pyecharts0.2.3 Geo错误 (#161)

请把 attr 输出来看一下

**Comment by chenjiandongx** [comment]
请自行转换成 ['北京','天津',...] 这样的格式

**Comment by tsunami12** [comment]
还是不行

**Comment by tsunami12** [comment]
['北京', '天津', '湖南', '陕西', '辽宁', '吉林', '黑龙江', '上海', '江苏', '浙江', '安徽', '福建', '山东', '湖北', '四川', '重庆', '广东', '甘肃']
湖南 coordinates is not found
陕西 coordinates is not found
辽宁 coordinates is not found
黑龙江 coordinates is not found
江苏 coordinates is not found
浙江 coordinates is not found
安徽 coordinates is not found
福建 coordinates is not found
山东 coordinates is not found
湖北 coordinates is not found
四川 coordinates is not found
广东 coordinates is not found
甘肃 coordinates is not found
[Finished in 0.5s]

**Comment by chenjiandongx** [comment]
把 attr 直接替换成这个 ['北京', '天津', '湖南', '陕西', '辽宁', '吉林', '黑龙江', '上海', '江苏', '浙江', '安徽', '福建', '山东', '湖北', '四川', '重庆', '广东', '甘肃'] 试试看

**Comment by tsunami12** [comment]
有一部分点的坐标是能找到的，有一部分是找不到的，这点让我很费解，之前出错误的时候是所有点的坐标都找不到

发送自 Windows 10 版邮件应用

发件人: chenjiandongx
发送时间: 2017年9月6日 16:29
收件人: chenjiandongx/pyecharts
抄送: tsunami12; Author
主题: Re: [chenjiandongx/pyecharts] python3+pyecharts0.2.3 Geo错误 (#161)

请自行转换成 ['北京','天津',...] 这样的格式

**Comment by tsunami12** [comment]
直接替换之后除了“北京”、吉林、天津、上海和重庆能在图上显示出来之外，其他的点坐标都找不到

**Comment by chenjiandongx** [comment]
是这样的，Geo 是提供【城市】坐标，具体到省的话可能有些是没有的，因为省的坐标定在哪个城市是个问题。所以这种情况，建议使用 Map 图

**Comment by tsunami12** [comment]
原来是这样的呀，换成Map确实就全部显示了，谢谢大神！

发送自 Windows 10 版邮件应用

发件人: chenjiandongx
发送时间: 2017年9月6日 17:20
收件人: chenjiandongx/pyecharts
抄送: tsunami12; Author
主题: Re: [chenjiandongx/pyecharts] python3+pyecharts0.2.3 Geo错误 (#161)

是这样的，Geo 是提供【城市】坐标，具体到省的话可能有些是没有的，因为省的坐标定在哪个城市是个问题。所以这种情况，建议使用 Map 图

**Comment by chenjiandongx** [comment]
:)
