### ISSUE TITLE
如何使用多个自定义经纬度

### ISSUE THREAD

**Issue by guoxulong** [chenjiandongx/pyecharts#164]
geo_cities_coords用户自定义地区经纬度，怎么实现
![default](https://user-images.githubusercontent.com/26757538/30144274-b7f05b04-93bc-11e7-956f-415b809887bf.png)

将多个自定义经纬度在地图上画点

**Comment by chenjiandongx** [comment]
Python2 or Python3？

**Comment by guoxulong** [comment]
python3

**Comment by chenjiandongx** [comment]
pyecharts 是哪个版本

**Comment by guoxulong** [comment]
0.2.3

**Comment by chenjiandongx** [comment]
Ok 我等下用电脑测试一下

**Comment by chenjiandongx** [comment]
所给的 geo_cities_coords 应该是一个字典 键为地区名 值为坐标列表

**Comment by guoxulong** [comment]
![default](https://user-images.githubusercontent.com/26757538/30144788-f4fc7606-93bf-11e7-9301-0a7ee829d096.png)
只是自定义一个经纬度的话是可以，但现在是想实现多个（例如：把广州市所有的地铁点都标记出来），当字典长度大于1时就不行了

**Comment by chenjiandongx** [comment]
geo_cities_coords={"A":[a,b],"B":[c,d]}

**Comment by guoxulong** [comment]
3Q，大神

**Comment by guoxulong** [comment]
又有2个问题：1、geo自定义经纬度后无法实现缩放；2、map不能自定义经纬度？

**Comment by chenjiandongx** [comment]
@guoxulong 
1. 如果其他行自定义不行那就是不行了。
2.Echarts 官方没有提供

关于以上两个，是 Echarts 本身的内容，如对此有需求，可到 Echarts 下提交 issue
