### ISSUE TITLE
No data label config or paramter for radar plot.

### ISSUE THREAD

**Issue by dofine** [chenjiandongx/pyecharts#165]
`is_label_show` doesn't seem to work for radar plot.

**Comment by chenjiandongx** [comment]
是的 radar 这个参数是无效的 echarts 本身这个有问题 显示不出来

**Comment by dofine** [comment]
Hi, just digged into the source code for `radar.py`, seems there lacks a line  
https://github.com/chenjiandongx/pyecharts/blob/master/pyecharts/charts/radar.py#L82
to set `label` in the option?

Similarly for `pie.py` : https://github.com/chenjiandongx/pyecharts/blob/master/pyecharts/charts/pie.py#L91

And echarts works as I played it on the test page Baidu offered.

**Comment by chenjiandongx** [comment]
@dofine 
hey,I add label options in radar.py and try it again.
![image](https://user-images.githubusercontent.com/19553554/30192148-2ef05888-9478-11e7-9bda-2eadf2205a90.png)
It works this time.
note: if you put too much data in `add()`,while you set `is_label_show=True`,label text still can't be show.

anyway, I hava add it for Radar chart,you will see it next release.

**Comment by nejinn** [comment]
@chenjiandongx 
0.2.4什么时候出来

**Comment by chenjiandongx** [comment]
@nejinn  TODAY

**Comment by chenjiandongx** [comment]
@nejinn @dofine 新版本 v0.2.4 已发布
