### ISSUE TITLE
render()可不可以提供一个选项来只生成script标签的内容

### ISSUE THREAD

**Issue by Petersonjoe** [chenjiandongx/pyecharts#168]
最近用web.py在搭一个内部网站，想用您这个类库来进行可视化（说实话，这个库很炫）。但是我需要将很多图集成在一个页面，又很懒不想一个一个render()来生成不同的js内容，然后再整合。请问能否在render()中提供参数，render()方法只生成script标签相关的内容，这样图形布局可以更灵活。

**Comment by chenjiandongx** [comment]
使用 options 参数可以返回所有配置项内容

**Comment by Petersonjoe** [comment]
谢谢，我在temple.py中找到了html的header和其他配置了，我想这里修改一下就可以定制html最终渲染的结果了吧。
