### ISSUE TITLE
python3.6

### ISSUE THREAD

**Issue by littleking008** [chenjiandongx/pyecharts#17]
TypeError: Object of type 'int64' is not JSON serializable

**Comment by chenjiandongx** [comment]
please show me the complete code

**Comment by littleking008** [comment]
在add命令时，我如果用从dataframe里面读取数据作为参数，就会报错。但是直接用该数据就不会错。
比如data是个dataframe，其中一列是地名，另一列是人数。那么我画bar图，命令如下：
bar.add("分布", list(df['地名']),list(df['人数']))
就会报错。

**Comment by chenjiandongx** [comment]
要不你就先转换后 在调用 add() 吧，所有的配置项在最后会保存为一份 json 格式的 “字典”

**Comment by littleking008** [comment]
报错代码：
bar.add("服装",list(df['province']),list(df['number']))
不报错代码：
bar.add("服装", ['北京', '上海', '福建'],[2, 1, 1])

请问如何转换，新手上路，还不太懂json

**Comment by chenjiandongx** [comment]
type(list(df['number'])) 是 int64 类型的吗

**Comment by littleking008** [comment]
对，是的。

**Comment by chenjiandongx** [comment]
那试试 int() 转换看看吧

**Comment by littleking008** [comment]
好的，我试试，感谢解答

**Comment by littleking008** [comment]
恩，搞定了。原来是int的问题。。感激ing

**Comment by chenjiandongx** [comment]
嗯 那没问题我就关闭这个 issue 了
