### ISSUE TITLE
0.2.4 版本  jupyter notebook 无法显示

### ISSUE THREAD

**Issue by zealotCE** [chenjiandongx/pyecharts#170]
按照文档中的代码，运行后没有反应

![sp170909_121517](https://user-images.githubusercontent.com/26129403/30236938-ce39fe5e-9558-11e7-9d3a-ab9ad06a9212.png)
![gmci 3d9nn8 wai zo_z b](https://user-images.githubusercontent.com/26129403/30236937-ce36dde6-9558-11e7-99cc-3f925d371249.png)
![sp170909_121446](https://user-images.githubusercontent.com/26129403/30236939-ce6a342a-9558-11e7-999e-527422e7112e.png)

**Comment by chfw** [comment]
没有仔细看文档。

最后一行请写: line

**Comment by zealotCE** [comment]
@chfw  谢谢，可以正常了
