### ISSUE TITLE
并没有找到grid和page混合用的说明书，于是我自己想了想，大家看看对不对。

### ISSUE THREAD

**Issue by nejinn** [chenjiandongx/pyecharts#171]
把grid当成一个图表就行，add到page里面。
就是page(grid)
但是grid不要用grid.render

**Comment by chenjiandongx** [comment]
是的 把 grid 当成一个图加进去就可以 明天我更新一下文档补充说明一下

**Comment by nejinn** [comment]
对于html打开显示的title
可以用 page_title=""修改。
我想每种类型的图表都有一个 page_title参数，但是 page_title一定要放第一个图片中。
比如可以:bar=Bar( page_title='my awesome charts')
page=Page( page_title='my awesome charts')

**Comment by nejinn** [comment]
@chenjiandongx 
比我还勤快。
暂时没有发现别的新功能了。

**Comment by chenjiandongx** [comment]
每个实例都只有一个 page_title 自定义类也一样

**Comment by nejinn** [comment]
grid可以画词云图！！！！

**Comment by nejinn** [comment]
grid画词云图的时候，出现一个问题：

grid = Grid()
grid.add(wordcloud, grid_left="60%")
grid.add(wordcloud1, grid_right="60%")
grid.render()

![image](https://user-images.githubusercontent.com/31615794/30242610-33723d18-95cc-11e7-9e94-e8790b84a0fd.png)

2个ci'yun词云图重叠。
请问代码有错吗

**Comment by chenjiandongx** [comment]
@nejinn 
Grid 是按网格布局来分的，而词云图没有这种布局，所以他们就画一起了吧。
