### ISSUE TITLE
jupypter notebook 无法渲染

### ISSUE THREAD

**Issue by miaozaiye** [chenjiandongx/pyecharts#172]
在jupiter notebook 中使用 render_notebook(), 提示“AttributeError: 'Bar' object has no attribute 'render_notebook'”

**Comment by nejinn** [comment]
是bar.render_notebook()吧？

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/30245972-ecc8353c-961d-11e7-91ee-832f206563a8.png)

老铁们，文档不是写给我自己看的啊

**Comment by nejinn** [comment]
@chenjiandongx 
文档更新了吗

**Comment by chenjiandongx** [comment]
文档一直以来都是同步更新的

**Comment by chfw** [comment]
请诸位一定要看文档。这个库和大家一起成长，自然文档也在变动。

**Comment by miaozaiye** [comment]
是的，用的 bar.render_notebook(),提示“AttributeError: 'Bar' object has no attribute 'render_notebook'”
