### ISSUE TITLE
是否支持boundaryGap 参数？

### ISSUE THREAD

**Issue by pkufool** [chenjiandongx/pyecharts#173]
您好，我尝试了很久都没找到这个功能，请问是否已经支持了，如果不支持后期是否考虑加入。谢谢您！

**Comment by nejinn** [comment]
我其实不太懂啊，没接触过jupyter，python也是直接出来一个html，跟jupyter的html有差别吗

**Comment by chenjiandongx** [comment]
@pkufool 
这个参数具体效果怎么样我也不太清楚，你是想在非类目轴中使用这个功能吗

**Comment by pkufool** [comment]
@chenjiandongx 就是x轴第一个标签是在x=0的地方，参考这个链接（http://echarts.baidu.com/demo.html#area-stack） 在xAxis里可以设置，因为我个人觉得如果画折线堆积图存在gap的话会比较难看。辛苦您看一下。谢谢啦！

**Comment by pkufool** [comment]
@nejinn 这个问题跟jupyter没有关系，谢谢您后面的话是赞扬作者的工作的，怪我没表达清楚。sorry哈。

**Comment by chenjiandongx** [comment]
@pkufool 它针对类目轴和非类目轴的效果不太一样，两者的数据类型也不一样。嗯，后续版本可以考虑加入该配置项

**Comment by pkufool** [comment]
@chenjiandongx 辛苦辛苦！期待！

**Comment by chenjiandongx** [comment]
@pkufool 
```
from pyecharts import Line

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 10, 100]
v2 = [55, 60, 16, 20, 15, 80]
line = Line("折线图示例")
line.add("商家A", attr, v1, )
line.add("商家B", attr, v2, is_xaxis_boundarygap=False)
line.render()
```
![image](https://user-images.githubusercontent.com/19553554/30423158-98300ec8-9974-11e7-9838-321504becd5a.png)
