### ISSUE TITLE
jupyter显示空白

### ISSUE THREAD

**Issue by nejinn** [chenjiandongx/pyecharts#174]
![image](https://user-images.githubusercontent.com/31615794/30264767-851f3788-970c-11e7-81ff-62c05f2d7c4e.png)

我已经开始怀疑自己理解能力了，为什么会是空白的。

**Comment by chfw** [comment]
First advice: pip uninstall pyecharts and then pip install pyecharts again in your current python environment.

Please also reference: https://github.com/chenjiandongx/pyecharts/issues/97

**Comment by nejinn** [comment]
@chfw 
OMG！it's too hard for me to do that at #97 
Django is ok！

**Comment by chfw** [comment]
Have you tried uninstall or install or not? Do that first. Will get you through. It is very simple.

**Comment by chenjiandongx** [comment]
@nejinn 
你需要三步来解决这个问题
1. 执行 `pip uninstall pyecharts` 卸载 pyecharts
2. 执行 `pip install notebook` 安装 notebook 环境
3. 执行 `pip install pyecharts==0.2.4` 重装最新版 pyecharts

Note：请确认你使用的 notebook 和 pyecharts 在同一个 python 环境内

**Comment by nejinn** [comment]
@chfw 
@chenjiandongx 
可以了====ok

**Comment by chenjiandongx** [comment]
@nejinn 希望使用时多看帮助文档，我花了那么长时间来写和维护文档，目的就是为了帮助用户更好的使用这个项目。

**Comment by nejinn** [comment]
我今天第一次接触jupyter，所以不知道。
文档最好是不要这样写，而是写成每次更新之后，更新的内容放在一起。
讲实话，我至今都没看出来.2.4跟2.3文档差别在哪。。。

**Comment by chenjiandongx** [comment]
@nejinn 
https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md

**Comment by nejinn** [comment]
@chenjiandongx 
我办公室的电脑怎么着都不行
家里电脑倒是一搞就好。
我连python都重装啦，还是空白。

**Comment by nejinn** [comment]
用jupyter nbextension list
只会出现
C:\Users\Administrator>jupyter nbextension list
Known nbextensions:


就没了...

**Comment by nejinn** [comment]
我干脆把电脑系统重新搞了，等会看结果，不行就真没办法了

**Comment by nejinn** [comment]
重装系统也是可以的，艰难啊。

**Comment by chfw** [comment]
把死马当活马医吧，试试这个：
```
from pyecharts import Scatter3D, online

import random
online()  # <--
data = [[random.randint(0, 100), random.randint(0, 100), random.randint(0, 100)] for _ in range(80)]
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
scatter3D = Scatter3D("3D 散点图示例", width=1200, height=600)
scatter3D.add("", data, is_visualmap=True, visual_range_color=range_color)
scatter3D
```

**Comment by nejinn** [comment]
@chfw 
我重装了系统，就可以了

也是很奇怪的

**Comment by chfw** [comment]
好，下次，我推荐给有同样问题的朋友，最后不行了，请重装系统 。。。

**Comment by chnynf** [comment]
同问

**Comment by chfw** [comment]
http://pyecharts.org/#/zh-cn/faq

**Comment by chnynf** [comment]
运行了这些，仍然是空白。。
sudo python3 -m pip install jupyter
sudo python3 -m pip install pyecharts
sudo python3 -m pip install jupyter-echarts-pypkg

**Comment by chfw** [comment]
sudo python3 -m pip uninstall jupyter-echarts-pypkg
sudo python3 -m pip install jupyter-echarts-pypkg --no-cache-dir

**Comment by chnynf** [comment]
![image](https://user-images.githubusercontent.com/37052928/45766174-f91b3100-bc04-11e8-97d1-f12500c446d4.png)

**Comment by chfw** [comment]
<img width="764" alt="screen shot 2018-09-19 at 18 18 35" src="https://user-images.githubusercontent.com/4280312/45769768-7ad88200-bc38-11e8-9934-1df8378d90ab.png">

**Comment by chnynf** [comment]
没有，这个地址not found
可能是装去别的地方了？ 但我所有pip都是用在python3 -m 之后的。这是台aws ec2，我重新建了很多个新的了，也试过了--no-cache-dir，应该不是这个问题

**Comment by chfw** [comment]
你装的python 环境与 jupyter 的运行环境不一致。

`which jupyter` 然后 `jupyter --path`，再查看所有的 data directory 里的 nbextensions.
