### ISSUE TITLE
散点图的标签问题

### ISSUE THREAD

**Issue by VencentCheung** [chenjiandongx/pyecharts#178]
在说问题之前，不得不说是个非常优秀的项目，实现方面，图形酷炫。

如题。在二维和三维的散点图中，几个坐标轴都是数字，想在数据点显示标签。例如一个城市的两个或三个维度的数据点，如何显示这个城市的名称。谢谢指教！！！！！

**Comment by chenjiandongx** [comment]
没太看明白你想表达的，但如果你说的标签的话，看文档
![image](https://user-images.githubusercontent.com/19553554/30512282-5e92588c-9b1e-11e7-8b40-c46a44926016.png)

**Comment by VencentCheung** [comment]
灰常感谢你的及时回复。我看了这个文档，最后一个label_formatter应该是我想要的，但是不知道怎么使用，可否给个例子？

**Comment by VencentCheung** [comment]
![image](https://user-images.githubusercontent.com/21139393/30512537-4cb91848-9b24-11e7-83b3-d4290d500d88.png)
和这个图片一样，书记点显示标签。同时想问一下，二维数据画图，第三个维度的数据大小来决定数据点的大小，最新的版本可以实现这个吗？ @chenjiandongx

**Comment by chenjiandongx** [comment]
@VencentCheung 暂时实现不了这个功能（第三个维度的数据大小来决定数据点的大小）。因为官方并没有提供直接的设置参数，用 Echarts 本身的话是使用了回调方法，而 json 无法 dumps 成 js 函数。

**Comment by VencentCheung** [comment]
@chenjiandongx 谢谢！！！还是想问一下散点图标签如何实现，能否麻烦给个示例？

**Comment by chenjiandongx** [comment]
label_formatter = '{a}'
label_formatter = '{b}'
label_formatter = ‘{a} {b}’
把这些参数多试几个看看效果就明白了

**Comment by VencentCheung** [comment]
@chenjiandongx 我就是尝试过了，和没写效果是一样的，所以我才过来问的

**Comment by chenjiandongx** [comment]
贴码+效果图

**Comment by VencentCheung** [comment]
![image](https://user-images.githubusercontent.com/21139393/30512809-27105eac-9b2a-11e7-889a-032611f6e5d8.png)

attr = ['a','b','c','d','e','f']
v1 = [-4,1,4,5,7,9]
v2 = [-5,2,4,6,7,3]

scatter = Scatter(background_color='#f7f8fa')
scatter.add('散点图示例',v1,v2,label_formatter='{a}{b}')
# scatter.show_config()
scatter.render()
make_a_snapshot('render.html','散点图示例.png')

**Comment by chenjiandongx** [comment]
`is_label_show=True`, please

**Comment by VencentCheung** [comment]
@chenjiandongx 简单说如何数据点标签如何分别显示‘a' 'b''c''d' 'e' 'f'？

**Comment by chenjiandongx** [comment]
@VencentCheung 你之所以看不到标签信息，是因为你没有将 `is_label_show` 设置为 True。

**Comment by VencentCheung** [comment]
@chenjiandongx 我知道这个问题了，is_lable_show = True 但是显示的6个标签都是一样的

**Comment by chenjiandongx** [comment]
很抱歉，没办法实现你所想要的

**Comment by VencentCheung** [comment]
@chenjiandongx 很遗憾不能实现。灰常感谢你的耐心解答

**Comment by chenjiandongx** [comment]
😄

**Comment by VencentCheung** [comment]
@chenjiandongx 以后会支持不？像上例数据点分别显示‘abcdefde’的标签

**Comment by chenjiandongx** [comment]
以后也不会实现该功能，很抱歉

**Comment by VencentCheung** [comment]
@chenjiandongx 散点图如果看不到标签，只有数据点，也失去了该有的意义了。再次感谢

**Comment by chfw** [comment]
如果是echarts实现不了，可以给echarts说明情况，求支持。

**Comment by chenjiandongx** [comment]
@VencentCheung 
![2017-09-17_18-48-57](https://user-images.githubusercontent.com/19553554/30520121-6e426b58-9bd9-11e7-8d06-2bb0bab3d0bc.gif)

已经可以利用第三个维度+Visualmap 决定数据点大小，但是标签问题就解决不了

**Comment by VencentCheung** [comment]
@chenjiandongx 谢谢了。echarts本身不是可以支持吗？你在写这个库转换中遇到什么样的问题了？

**Comment by chenjiandongx** [comment]
@VencentCheung Json 无法转换为 js 回调函数

**Comment by Siffre** [comment]
@chenjiandongx      json转化js回调函数什么意思???

**Comment by wqw547243068** [comment]
同求散点图标签可视化，对于3D散点图，点很多，如果没有标签，数据就区分不开，难以分析定位
![image](https://user-images.githubusercontent.com/3257257/60421591-bfa83500-9c1c-11e9-86fd-f21dc604fcfc.png)

**Comment by wqw547243068** [comment]
> ![image](https://user-images.githubusercontent.com/21139393/30512537-4cb91848-9b24-11e7-83b3-d4290d500d88.png)
> 和这个图片一样，书记点显示标签。同时想问一下，二维数据画图，第三个维度的数据大小来决定数据点的大小，最新的版本可以实现这个吗？ @chenjiandongx

请问你最后是怎么解决的？

**Comment by Anco-ha** [comment]
标签可以显示 但是数据密集的时候  这些名字会堆叠  怎么智能化position呢 ?
