### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'is_grid'

### ISSUE THREAD

**Issue by xiaobai721** [chenjiandongx/pyecharts#18]
bar = Bar("柱状图示例", height=720, is_grid=True)
如上的代码报错：
 File "<ipython-input-7-91b8701f1bb2>", line 6, in <module>
    bar = Bar("柱状图示例", height=720, is_grid=True)
  File "build\bdist.win32\egg\pyecharts\charts\bar.py", line 14, in __init__
    super(Bar, self).__init__(title, subtitle, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'is_grid'

**Comment by chenjiandongx** [comment]
这是 0.1.7 版本新增内容 要使用的话请更新到最新版 pip install pyecharts==0.1.7

**Comment by xiaobai721** [comment]
WindowsError: [Error 2] : 'd:\\anaconda\\lib\\site-packages\\pyecharts-0.1.6-py2
.7.egg'
直接安装失败，请问是什么原因呢？

**Comment by chenjiandongx** [comment]
pip install pyecharts==0.1.7 这样安装出错？

**Comment by xiaobai721** [comment]
是的

**Comment by chenjiandongx** [comment]
使用的是 Windows 系统吗 Python2 还是 Python3

**Comment by xiaobai721** [comment]
win7, python2.7

**Comment by chenjiandongx** [comment]
pip uninstall pyecharts 然后再 pip install pyecharts==0.1.7 试试

**Comment by xiaobai721** [comment]
OK,，搞定了，多谢！

**Comment by liborjiang** [comment]
hi，我之前是安装过pyecharts的。好久没更新了，今天就把原来的卸载了，重新下载安装。一直失败哎。。。mac环境下，pip install pyecharts安装方式。。。

**Comment by chfw** [comment]
我就是在 mac 上给 pyecharts 写代码，怎么会不行呢。请发具体信息：python version, installation log
