### ISSUE TITLE
地图移动和缩放问题

### ISSUE THREAD

**Issue by bailixin** [chenjiandongx/pyecharts#181]
请问可以增加地图移动和缩放的功能吗？

**Comment by chenjiandongx** [comment]
你那边滚动鼠标滑轮地图不会缩放吗？

**Comment by bailixin** [comment]
是滴，不会缩放。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/30779880-46a507f2-a130-11e7-9d1f-69a5d2d7ce3b.png)
请问你设置过这个参数没有

**Comment by bailixin** [comment]
设置了is_roam=True,好像不起作用。

**Comment by chenjiandongx** [comment]
@bailixin Map 还是 Geo ？

**Comment by bailixin** [comment]
谢谢！！！，搞定。

**Comment by bailixin** [comment]
Map可以平移和缩放，Geo好像不行。

**Comment by bailixin** [comment]
看了一下echarts，Geo是支持缩放和平移的。

**Comment by chenjiandongx** [comment]
@bailixin 把链接贴上来，我去看看是怎么配置的

**Comment by bailixin** [comment]
试了一下http://www.echartsjs.com/gallery/editor.html?c=scatter-maps上的demo，添加roam:true是可以缩放的。也可添加自定义经纬度。

**Comment by bailixin** [comment]
![11](https://user-images.githubusercontent.com/29723061/31174225-47a6b410-a93d-11e7-8c54-74d6727a4bfa.jpg)

**Comment by chenjiandongx** [comment]
@bailixin 下个版本开始 Geo 图就能移动和缩放了

**Comment by bailixin** [comment]
@chenjiandongx 谢谢！！！

**Comment by chenjiandongx** [comment]
@bailixin 新版本 v0.2.6 已发布，请更新使用
