### ISSUE TITLE
如何在多张图表间加入文字信息呢？

### ISSUE THREAD

**Issue by renyangfar** [chenjiandongx/pyecharts#184]
如何在图表间加入文字信息对图表进行说明

**Comment by nejinn** [comment]
可以改html文件
<p>xxxxxxxxxxx</p>

**Comment by nejinn** [comment]
!!!!<p>xxxxxxxxxxxxxxxxx</P>!!!!
前后！！！！不要

**Comment by nejinn** [comment]
擦...zhi只能发图片了
![image](https://user-images.githubusercontent.com/31615794/30791481-5e690e5a-a1e5-11e7-9e52-370a0a708faa.png)
