### ISSUE TITLE
结合Page和Map使用，运行page.render()生成文件时，会报错。

### ISSUE THREAD

**Issue by BanksJ** [chenjiandongx/pyecharts#185]
raise Exception("No js library found. Nothing works!")

有同学遇到同样的情况吗？

**Comment by chenjiandongx** [comment]
使用的是 pyecharts 哪个版本，如果不是最新版，请更新到最新版

**Comment by BanksJ** [comment]
0.2.4,是最新版本的

**Comment by BanksJ** [comment]
@chenjiandongx 
是最新版本的，0.2.4
代码没改过，今天突然报这个错

**Comment by chenjiandongx** [comment]
把代码贴上来 我看一下

**Comment by BanksJ** [comment]
`class MapVisual(object):

    # 准备基础数据
    def get_data(self, df):
        '''
        参数类型: df为城市粒度的平台加权数据框,即df_work
        返回值: 字典类型，key为moni_id, value为元组，0号位是省份，1号位是省份对应的零售价，2号位是省份对应的收购价
        '''

        # 获取当前时间
        today = datetime.date.today()
        oneday = datetime.timedelta(days=1)
        point = today - oneday

        # 用途：存储结果
        data = dict()

        # 抽取point时间点的df
        df_point = df[df['date']==point]
        # 按照车型分组
        groups = df_point.groupby('moni_id')
        # 从每一组提取数据
        for name,group in groups:
            # 抽取省份
            attr = list(group['province'])
            # 抽取零售价
            v_r = list(group['retail'])
            # 抽取收购价
            v_b = list(group['buy'])
            # 整合
            data[name] = (attr, v_r, v_b)

        # 返回数据
        return data

    # 绘图
    def draw_map(self, data, basic, ddtype=1):
        '''
        参数类型: data,字典类型，即get_data函数返回值
                  basic,基础数据框，即df_basic,用来匹配车型名
                  ddtype,整型，可选1(零售价)或2(收购价)，默认为1
        '''
        # 初始化Page
        page = Page()

        for car,row in data.items():
            # 读取标题
            name = list(basic[basic['moni_id']==car]['car'])[0]
            point = list(basic[basic['moni_id']==car]['regDate'])[0]
            name = name + str(point)

            # 读取省份信息
            attr = row[0]
            # 读取省份对应的数值信息
            v = [round(i,4) for i in row[ddtype]]

            # 确定图例极值
            up = math.ceil(max(v))
            down = math.floor(min(v))

            # 初始化map对象
            map = Map(name, '数据来源: 车300 精真估', width=1000, height=600)
            # 绘制地图
            map.add('', attr, v, maptype='china', is_visualmap=True, visual_text_color='#000', visual_range=[down, up])
            # 加入page
            page.add(map)

        # 绘制page
        # page.render('地图.html')
        page.render()

        return None`

刚才试了个demo,可以正常使用Page。应该是我的代码的问题。
demo如下：
`# coding: utf-8
from pyecharts import Page,Map

page = Page()

for i in range(3):
    value = [155, 10, 66, 78, 33, 80, 190, 53, 49.6]
    attr = ["福建", "山东", "北京", "上海", "甘肃", "新疆", "河南", "广西", "西藏"]
    map = Map("Map 结合 VisualMap 示例", width=1200, height=600)
    map.add("", attr, value, maptype='china', is_visualmap=True, visual_text_color='#000')
    page.add(map)

page.render()

`

**Comment by chenjiandongx** [comment]
这问题很奇怪 @BanksJ

**Comment by chenjiandongx** [comment]
@BanksJ 先不用在循环里，单个加入 page 会出现这个问题吗

**Comment by BanksJ** [comment]
@chenjiandongx 
单独加入可以，将代码修改如下也可以正常使用。我猜测是变量部分的影响
`        page = Page()

        # for car,row in data.items():
        #     # 读取标题
        #     name = list(basic[basic['moni_id']==car]['car'])[0]
        #     point = list(basic[basic['moni_id']==car]['regDate'])[0]
        #     name = name + str(point)

        #     # 读取省份信息
        #     attr = row[0]
        #     # 读取省份对应的数值信息
        #     v = [round(i,4) for i in row[ddtype]]

        #     # 确定图例极值
        #     up = math.ceil(max(v))
        #     down = math.floor(min(v))

        #     # 初始化map对象
        #     map = Map(name, '数据来源: 车300 精真估', width=1000, height=600)
        #     # 绘制地图
        #     map.add('', attr, v, maptype='china', is_visualmap=True, visual_text_color='#000', visual_range=[down, up])
        #     # 加入page
        #     page.add(map)

        for i in range(3):
            value = [155, 10, 66, 78, 33, 80, 190, 53, 49.6]
            attr = ["福建", "山东", "北京", "上海", "甘肃", "新疆", "河南", "广西", "西藏"]
            map = Map("Map 结合 VisualMap 示例", width=1200, height=600)
            map.add("", attr, value, maptype='china', is_visualmap=True, visual_text_color='#000')
            page.add(map)

        # 绘制page
        # page.render('地图.html')
        page.render()

        return None`

**Comment by chenjiandongx** [comment]
能否将数据打包后发给我测试一下？没有数据我不好测试判断

**Comment by chenjiandongx** [comment]
@BanksJ 如果可以的话，打包成一个单独的 `.py` 文件发送到我邮箱 chenjiandongx@qq.com 我晚上测试一下

**Comment by BanksJ** [comment]
@chenjiandongx 
谢谢你的帮助，我按照你给的思路测试下去，发现是最初数据的问题。
原始数据经过管道清理直接传到这里的，有一个变量在传入过程改变了，不是预期那样，就是函数中的data.
修改后，恢复正常了。
抛出的错误，在我这应该是指，画图没有数据，page页面也没有数据，就没有工作，输出异常。

**Comment by chenjiandongx** [comment]
@BanksJ 那问题是解决了是吗

**Comment by BanksJ** [comment]
@chenjiandongx 
恩恩 是的。 问题解决了。

**Comment by chenjiandongx** [comment]
ok
