### ISSUE TITLE
适合PPT的图片

### ISSUE THREAD

**Issue by VencentCheung** [chenjiandongx/pyecharts#187]
默认参数画图保存以后，插入PPT非常不清晰，什么样的比例配置的图片比较适合PPT的展示？

**Comment by chenjiandongx** [comment]
这个自己调试吧 实际上我也没用过来做 PPT 至于图的大小可以根据自己需求调整 我一般都用截图的

**Comment by chfw** [comment]
https://github.com/ecomfe/echarts/issues/6720
