### ISSUE TITLE
Grid更灵活支持的请教

### ISSUE THREAD

**Issue by zhangyi7456** [chenjiandongx/pyecharts#188]
大神，目前版本里有不少图，都是无法支持Grid类的，比如map、timeline等等；如果能更灵活的支持更多图，可以开发BI仪表盘，不知道大神有没有这方面的计划。

**Comment by Siffre** [comment]
可以先把源码撸一遍,试着自己定制开发

**Comment by chenjiandongx** [comment]
@zhangyi7456 不是所有图都能支持 Grid，是因为并不是所有图都有 grid 属性。BI 仪表盘建议还是用专业的数据分析软件来搞，这不是本项目的目标。
