### ISSUE TITLE
正式发布 0.2.5 版本

### ISSUE THREAD

**Issue by chenjiandongx** [chenjiandongx/pyecharts#189]
## 更新主要内容包括
* #173 为 xyAxis 通用配置项新增 is_xaxis_boundarygap 和 is_yaxis_boundartgap 参数
* #22 为散点图新增 extra_data 参数，可以为数据新增除 x y 轴外的其他维度
* 为 markPoint 新增自定义标记点功能
* 为 visualMap 新增 visual_dimension 参数，可以指定 visualmap 映射到哪个数据维度
* 为 Map 图新增 212个国家和地区
* 部分解决 Overlap 和 Grid 不能一起使用的问题（当 Overlap 为多 x 轴或多 y 轴的时候坐标轴索引仍会出现问题）
#### 欢迎大家更新使用

**Comment by Siffre** [comment]
哈哈，感谢大佬的更新
