### ISSUE TITLE
建议x_axis 和 y_axis 数据类型扩展为iterable，不必限制为list。同时建议增加对pd.Series 和 pd.DataFrame的特殊支持

### ISSUE THREAD

**Issue by xbanke** [chenjiandongx/pyecharts#19]
1、将list放宽到iterable可以方便很多。
2、关于Series，建议自动获取name, index, values属性，分别作为add参数。对于index为timestamp或数值类型，也自动转为string；
3、至于DataFrame，只是在Series上一次绘制多条线。

当然自己扩展也不复杂，个人感觉可能很多人都有这个需求，毕竟pandas的使用相当广泛。

**Comment by chenjiandongx** [comment]
后续的版本应该会考虑更好的适配 Pandas 和 Numpy 的

**Comment by xbanke** [comment]
Thanks.

**Comment by chenjiandongx** [comment]
@xbanke 
版本已更新
