### ISSUE TITLE
HearMap.add()不能配置x轴y轴的名称及其属性,不能设置is_yaxis_inverse

### ISSUE THREAD

**Issue by dickwxyz** [chenjiandongx/pyecharts#195]
heatmap.add("信令数", x_axis=x_axis, xaxis_name = '10月', xaxis_name_pos = 'middle', xaxis_name_gap = 30, 
            y_axis=y_axis, yaxis_name = '小时', yaxis_name_pos = 'middle', yaxis_name_gap = 30, is_yaxis_inverse = True,
            data = data2, 
            is_visualmap = True,
            visual_range=[0,int(pandas['count'].max())],
            visual_text_color="#000",
            visual_orient='horizontal',
            visual_pos='center',visual_top = 'bottom'
            )

**Comment by chenjiandongx** [comment]
@dickwxyz 已修复，下个版本开始就可以正常使用了

![image](https://user-images.githubusercontent.com/19553554/31278366-3e163d76-aad7-11e7-9dc3-5765bb5ba115.png)

**Comment by chenjiandongx** [comment]
@dickwxyz 新版本 v0.2.6 已发布，请更新使用
