### ISSUE TITLE
custom和get_series方法如何引用

### ISSUE THREAD

**Issue by dkazrael0** [chenjiandongx/pyecharts#196]
你好楼主，请问个问题，我在使用自定义图表的时候为什么无法调取custom和get_series方法啊？是还有什么父类需要引用吗？

**Comment by chenjiandongx** [comment]
请把问题描述得详细一点

**Comment by dkazrael0** [comment]
我使用的是pycharm CE的2.7版本环境，pyecharts版本为0.2.5，我在运行你的“用户自定义例子”的代码时，报错提示“'Bar' object has no attribute 'custom'”，请问这个是什么问题呢？该怎么做？

**Comment by chenjiandongx** [comment]
把你的代码贴上来我看一下吧

**Comment by dkazrael0** [comment]
from pyecharts import Bar, Line

attr = ['A', 'B', 'C', 'D', 'E', 'F']
v1 = [10, 20, 30, 40, 50, 60]
v2 = [15, 25, 35, 45, 55, 65]
v3 = [38, 28, 58, 48, 78, 68]
bar = Bar("Line - Bar 示例")
bar.add("bar", attr, v1)
line = Line()
line.add("line", v2, v3)
bar.custom(line.get_series())
bar.show_config()
bar.render()

**Comment by dkazrael0** [comment]
我主要是想尝试是否可以进行双纵坐标作图，共用横坐标区间，请问这样也是通过custom和get_series方法来实现吗？

**Comment by chenjiandongx** [comment]
@dkazrael0 这种方法已经弃用很久了 请重新阅读一下帮助文档
