### ISSUE TITLE
Kline中最大值、最小值标记线的问题

### ISSUE THREAD

**Issue by zrhett** [chenjiandongx/pyecharts#199]
添加Kline时使用了mark_line=['max', 'min']参数，发现图中的最大值最小值标记线指示的是开盘价，请问能否自定义选择使用收盘价的数据呢？
标记线的箭头能否选择隐藏？

图1.程序结果截图：
<img width="451" alt="1" src="https://user-images.githubusercontent.com/16285731/31304317-a488fabe-aae4-11e7-9119-03a89c6a13e0.png">

图2.Echarts网站-官方实例-k线图-2015年上证指数截图：
<img width="306" alt="g3" src="https://user-images.githubusercontent.com/16285731/31304446-8ca9971c-aae6-11e7-8be6-68841a50c290.png">

**Comment by chenjiandongx** [comment]
@zrhett 
下个版本开始，会新增 `mark_line_symbolsize` 和 `mark_line_valuedim` 参数，前者用于指定标记两端符号的大小，后者用于指定维度( open, close, highset, lowest ) 
### 默认
![image_62](https://user-images.githubusercontent.com/19553554/31305210-8e3d22ee-ab66-11e7-8ccb-c545d4486534.png)

### 调整参数
`mark_line_symbolsize=0`, `mark_line_valuedim='close'`
![image_63](https://user-images.githubusercontent.com/19553554/31305215-b68c02b0-ab66-11e7-8f90-8636add2bd9d.png)
