### ISSUE TITLE
用Pyecharts设计可编辑文本的问题

### ISSUE THREAD

**Issue by zhangyi7456** [chenjiandongx/pyecharts#200]
BI工具里有一个功能是可以用文字展示主要指标值的；我利用line不填写数据，只显示主副标题，可以部分实现这个问题。但是坐标轴无法设置颜色，就一直有条线在里面，不知道有没有办法实现。
![1507533143 1](https://user-images.githubusercontent.com/26074889/31328045-78f845f8-ad05-11e7-83cb-c7701d64b9c7.jpg)

**Comment by chenjiandongx** [comment]
@zhangyi7456 
下个版本开始，会新增 `is_xaxis_show` 和 `is_yaxis_show` 两个参数，用于控制是否显示 x 轴或 y 轴

下面这个是取消 x y 轴后的效果
![image](https://user-images.githubusercontent.com/19553554/31328780-5a368c0c-ad09-11e7-9467-725c9392ebde.png)

**Comment by zhangyi7456** [comment]
鼓掌！这个已经很受用了。现在的版本组合和自定义真是越来越好。感谢您的回复！

**Comment by chenjiandongx** [comment]
@zhangyi7456 新版本 v0.2.6 已发布，请更新使用
