### ISSUE TITLE
是否支持不等距折线图？

### ISSUE THREAD

**Issue by liuyuanlin** [chenjiandongx/pyecharts#202]
我查看了实例，没有提及到不等距折线图，在相关通用参数中也未见说明。请问是否支持不等距折线图，或者后续版本是否计划支持？

**Comment by chfw** [comment]
请问echarts有不等距折线图吗，请分享截图和设置。

**Comment by chfw** [comment]
https://github.com/ecomfe/echarts/issues/6817#issuecomment-336373054

**Comment by Ovilia** [comment]
是的，请根据上面的例子修改 formatter，目前没有更好的方法
