### ISSUE TITLE
Update developer's guide

### ISSUE THREAD

**Issue by chfw** [chenjiandongx/pyecharts#204]
As pyecharts becomes more popular, the developer's guide needs to be updated on the latest development mode: 

1. dev branch for new features and PR
2. master branch for new release.

https://github.com/chenjiandongx/pyecharts/pull/203

**Comment by chenjiandongx** [comment]
fixed

**Comment by chfw** [comment]
Please add a PR template
![image](https://user-images.githubusercontent.com/4280312/31523180-e8a8fce8-afa9-11e7-8594-6caebc6de9b3.png)

**Comment by chenjiandongx** [comment]
@chfw  https://github.com/chenjiandongx/pyecharts/commit/8f9291dbba1075f3cb61e634e1285848b9c7c0b4 这样？看来得合并到 master 才有效

**Comment by chfw** [comment]
嗯 咱不急。遵守我们的流程先。
