### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'../pyecharts/pyecharts/templates/js/echarts/registry.json'

### ISSUE THREAD

**Issue by rubinliudongpo** [chenjiandongx/pyecharts#206]
I cannot find echarts/registry.json to run any test case.

**Comment by chenjiandongx** [comment]
如果你直接 clone 仓库是没有 echarts 这个文件夹的，需要 git clone --recursive

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/en-us/doc_for_pyechart_developer.md#why-the-folder-pyechartstemplatesjs-is-empty
