### ISSUE TITLE
饼图的title顺序问题

### ISSUE THREAD

**Issue by sleep128** [chenjiandongx/pyecharts#21]
comment_list = ["小于10min", "10min-20min", "20min-30min", "大于30min"]
![image](https://user-images.githubusercontent.com/16074847/28663152-198be3a4-72ef-11e7-8e3c-737715339f3e.png)

**Comment by chenjiandongx** [comment]
可否把问题讲具体一点

**Comment by sleep128** [comment]
comment_list里“大于30min”我放在最后，垂直显示的顺序为什么跟定义的顺序不一样啊

**Comment by chenjiandongx** [comment]
请问你现在用的是什么版本 最新版 0.1.7 吗

**Comment by sleep128** [comment]
是用的0.1.7的，python3,Windows

**Comment by chenjiandongx** [comment]
刚看了代码 因为我用了 set() 去重导致顺序不一致

**Comment by chenjiandongx** [comment]
下个版本会解决这个问题的

**Comment by sleep128** [comment]
好的，thanks.

**Comment by chenjiandongx** [comment]
已更新为 0.1.8 版本，欢迎使用
