### ISSUE TITLE
正式发布 0.2.6 版本

### ISSUE THREAD

**Issue by chenjiandongx** [chenjiandongx/pyecharts#210]
* ### version 0.2.6 - 2017.10.14

    #### Added
    * 为 [文档](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/documentation.md) 新增 [使用技巧](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/documentation.md#使用技巧) 介绍
    * [issue#194](https://github.com/chenjiandongx/pyecharts/issues/194) 新增 `is_map_symbol_show` 参数，用于控制 Map 图 [红点的显示](https://www.oschina.net/question/1416804_245423)
    * [issue#192](https://github.com/chenjiandongx/pyecharts/issues/192) 新增 `label_emphasis_pos`, `label_emphasis_textsize`, `label_emphasis_textcolor` 参数，用于解决 Geo 图 tooltip 不能只显示城市名和数值的问题
    * [issue#132](https://github.com/chenjiandongx/pyecharts/issues/132) 新增图形类型树图
    * [issue#181](https://github.com/chenjiandongx/pyecharts/issues/181) 为 Geo 图新增 `is_roam` 参数解决不能缩放和移动的问题
    * [issue#199](https://github.com/chenjiandongx/pyecharts/issues/199) 为 markLine 新增 `mark_line_symbolsize` 和 `mark_line_valuedim` 参数，解决不能指定维度以及标记大小不能调整的问题
    * [issue#200](https://github.com/chenjiandongx/pyecharts/issues/200) 为 xyAxis 通用配置项新增 `is_xaxis_show` 和 `is_yaxis_show` 参数，（控制是否显示 x 轴或 y 轴）解决设计可编辑文本的问题
    * [issue#201](https://github.com/chenjiandongx/pyecharts/issues/201) 为 Bar 图新增 `bar_category_gap` 参数，提供绘制直方图的方案
    * [issue#208](https://github.com/chenjiandongx/pyecharts/issues/208) 为 dataZoom 通用配置项 `datazoom_type` 新增类型 'both'（同时拥有 'slider' 以及 'inside')
    * [issue#208](https://github.com/chenjiandongx/pyecharts/issues/208) 为 HeatMap 图新增 **日历热力图**

    #### Changed
    * 将 label 通用配置项的 `is_emphasis` 参数更改为 `is_label_emphasis`
	* show_config() 修改用 JSON 显示

    #### Fixed
    * [issue#195](https://github.com/chenjiandongx/pyecharts/issues/195) 修复 HeatMap 图配置 x、y 轴属性无效的问题

**Comment by chfw** [comment]
姊妹发布：https://www.npmjs.com/package/pyecharts.js

**Comment by linchart** [comment]
好像最新版本的无法在notebook里面内嵌结果图表？
from pyecharts import Bar
bar = Bar('class type')
bar.add('Class',x_axis=['one','two'],y_axis=[20, 5])
bar.render()
运行以上程序，只会在当前路径下生成render.html文件

**Comment by chfw** [comment]
@linchart , you have outdated info. please re-read the user guide. In short, please simply call:

```
bar # bar.render()
```

**Comment by linchart** [comment]
@chfw  it worked ,thank u.
