### ISSUE TITLE
Geo自定义坐标后生成的html文件没有匹配的value数据

### ISSUE THREAD

**Issue by dickwxyz** [chenjiandongx/pyecharts#211]
版本0.2.6
from pyecharts import Geo
import pandas as pd
count_bs = pd.read_csv('/home/dq/桌面/访客数据结果/count_bs.csv', encoding='utf8')
data = []
for i in range(len(count_bs)):
    data.append((str(count_bs.loc[i,'bdgrid']), count_bs.loc[i,'count']))
cities_coords = {}
for i in range(len(count_bs)):
    cities_coords[str(count_bs.loc[i,'bdgrid'])] = [count_bs.loc[i,'center_lon'], count_bs.loc[i,'center_lat']]

geo = Geo("上海栅格基站数",  title_color="#fff", title_pos="center",
          width=1200, height=700, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr = attr, value = value, 
        geo_cities_coords = cities_coords, type="heatmap", maptype='上海', 
        visual_range=[0, 60], visual_text_color="#fff",
        symbol_size=5, is_visualmap=True )
geo.render('/home/dq/桌面/栅格基站数.html')

**最终的geo_cities_coords数据**为
{'8987': [121.55245589729095, 30.878410193884392, 1],
 '29452': [121.26307650851156, 31.305587688494573, 2],
 '27992': [121.53667156699392, 31.274111452049603, 7],
}
但是html文件中的data显示为
"type": "heatmap",
            "name": "55381",
            "data": [
                {
                    "name": "26254",
                    "value": [
                        121.4840571326704,
                        31.23813861039822,
                        null
                    ]
                },
                {
                    "name": "26255",
                    "value": [
                        121.48931857610272,
                        31.23813861039822,
                        null
                    ]
                },
                {
                    "name": "26472",
                    "value": [
                        121.49458001953508,
                        31.242635215604643,
                        null
                    ]
对应的value显示为null,请问是什么问题?

**Comment by chenjiandongx** [comment]
如果自定义了坐标，就会覆盖原来预先保留的坐标。你这看起来好像数据不太对，
![image](https://user-images.githubusercontent.com/19553554/31574951-b20eae16-b10d-11e7-8c85-8d09d6d45f3b.png)
首先得确保有该 **城市或地区** 名字，然后在 data 中才会有相应的坐标点

**Comment by dickwxyz** [comment]
原来构造的cities_coords数据像这样
{'8987': [121.55245589729095, 30.878410193884392],
 '29452': [121.26307650851156, 31.305587688494573],
 '27992': [121.53667156699392, 31.274111452049603]}
经过Geo.add()之后会变成
{'8987': [121.55245589729095, 30.878410193884392, 1],
'29452': [121.26307650851156, 31.305587688494573, 2],
'27992': [121.53667156699392, 31.274111452049603, 7],
}
多了value, 但是生成的html文件里value值变成了null

**Comment by dickwxyz** [comment]
也有可能是百度不让用了
http://echarts.baidu.com/download-map.html

**Comment by chenjiandongx** [comment]
为什么你字典的 Key 是数值而不是地区？

**Comment by puplis** [comment]
类似的问题
有些地震数据，数据中提供了地震点的经纬坐标，但是并不知到具体地点名称（姑且定义为点1，以此类推），感觉应该能实现将这些点标记在geo地图上，但是不知道数据应该以怎么样的形式才能实现？
期待您的解答

**Comment by chenjiandongx** [comment]
能否贴上数据 我测试一下

**Comment by puplis** [comment]
Date | Latitude | Longitude | Class
-- | -- | -- | --
0 | 0.572430556 | 19.246 | 6
1 | 0.479039352 | 1.863 | 5.8
2 | 0.754143519 | -20.579 | 6.2
3 | 0.784525463 | -59.076 | 5.8
4 | 0.564467593 | 11.938 | 5.8
5 | 0.567037037 | -13.405 | 6.7
6 | 0.564178241 | 27.357 | 5.9
7 | 0.970625 | -13.309 | 6
8 | 0.480983796 | -56.452 | 6
9 | 0.446724537 | -24.563 | 5.8
10 | 0.873391204 | -6.807 | 5.9
11 | 0.007835648 | -2.608 | 8.2
12 | 0.399652778 | 54.636 | 5.5
13 | 0.227152778 | -18.697 | 5.6
14 | 0.664479167 | 37.523 | 6
15 | 0.142361111 | -51.84 | 6.1
16 | 0.209282407 | 51.251 | 8.7
17 | 0.253460648 | 51.639 | 6
18 | 0.275763889 | 52.528 | 5.7
19 | 0.277453704 | 51.626 | 5.8
 @chenjiandongx 想处理的数据大概就这几项

**Comment by chenjiandongx** [comment]
@puplis 
效果
![2017-10-19_15-03-30](https://user-images.githubusercontent.com/19553554/31758190-ed58c914-b4de-11e7-9cac-390f7dde68fb.gif)

代码
```
coords = {
       "0": [0.572430556, 19.246],
       "1": [0.479039352, 1.863],
       "2": [0.754143519, -20.579]
   }

geo = Geo(**chart_init)
geo.add("", ["0", "1", "2"], [6, 5.8, 6.2], is_visualmap=True,
        geo_cities_coords=coords, maptype="world")
geo.render()
```

**Comment by puplis** [comment]
十分感谢😀

发自我的 iPad

**Comment by dickwxyz** [comment]
问题已经解决, value的数据类型需要int,而不是numpy.int64.谢谢开发者
