### ISSUE TITLE
渲染后图的高和宽如何实现自适应??

### ISSUE THREAD

**Issue by Siffre** [chenjiandongx/pyecharts#215]
![selection_006](https://user-images.githubusercontent.com/12948798/31584248-bf4e9132-b170-11e7-8eef-b1b62183bf7a.png)

这是设置宽高的情况下,宽高不能用样式进行控制,该如何呢??

**Comment by Siffre** [comment]
把源码看了一遍,只能自己修改源码了,源码安装的方式进行样式修改了

**Comment by Siffre** [comment]
自己改后,遇到这样的问题,js不能处理python的内容,求大佬们帮忙


![selection_008](https://user-images.githubusercontent.com/12948798/31585626-7da31072-b18a-11e7-8507-466f18c73fd2.png)

![selection_007](https://user-images.githubusercontent.com/12948798/31585628-8c181b02-b18a-11e7-97e1-ae1e44d8cfbb.png)

**Comment by kinegratii** [comment]
看不到python代码，但我估计是options变量没有转化为json字符串。

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> a = {'a':True}
>>> json.dumps(a)
'{"a": true}'
>>> str(a)
"{'a': True}"
>>>
```

**Comment by Siffre** [comment]
@kinegratii 解决了,单独抽出来,忘记转化JSON啦,╮(╯▽╰)╭

**Comment by Siffre** [comment]
@kinegratii 自适应还是没有解决, 我看了生成的画板时绝对位置,很难改动

**Comment by kinegratii** [comment]
可以将图表放置在一个响应式容器内，如Bootstrap的row类中，
```
<div class="row">
    <div class="col-md-12">
        <div id="{{ chart_id }}"></div>
    </div>
</div>
```

**Comment by SongZhuhai** [comment]
不是指div的自适应，画板的宽和高确定后，就算div自适应了也没用
Echart有个画板的自适应设置，resize，可以考虑加入
现在也是自己建立模版实现的，抛弃了pyechart
所以建议提高自由度

**Comment by kinegratii** [comment]
@chenjiandongx @chfw 请看看 **echarts画板自适应** 这个功能实现的可行性。

**Comment by chenjiandongx** [comment]
@SongZhuhai 能否给出具体实现的例子的链接，我好参考一下

**Comment by ywq111** [comment]
@chenjiandongx 
自适应的做法，我是修改了模板中的两个文件，实现一个页面单个和多个图表都能自适应。
[templates.tar.gz](https://github.com/chenjiandongx/pyecharts/files/1501249/templates.tar.gz)

**Comment by chenjiandongx** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_flask.md

**Comment by chenjiandongx** [comment]
新增了图形自适应文档

**Comment by Jasonon** [comment]
这个链接失效 有自适应的例子么，谢谢！

**Comment by Ye-byte** [comment]
@chenjiandongx  你好，这个文档还有吗？我使用了3.0版本的pyecharts，修改了macro无法完成自适应，谢谢
