### ISSUE TITLE
Bar3D、Geo 在jupyter notebook中不显示图片问题

### ISSUE THREAD

**Issue by qindiandadudu** [chenjiandongx/pyecharts#219]
1.  jupyter notebook使用的是当前最新版本
2.  pyecharts使用的是0.2.6\0.2.5\0.2.3

问题：  线图（Line）、箱图、柱状图、仪表盘等都正常显示，Bar3D\Geo地图无法再jupyter notebook中显示。另render（）方法生成的html文件在浏览器中打开正常显示。试用了问题列表中一系列的解决方案没有解决
@chenjiandongx 
![funnel](https://user-images.githubusercontent.com/23720899/31592083-5a3165e8-b258-11e7-8161-32e36979b6be.png)
![geo](https://user-images.githubusercontent.com/23720899/31592084-5a654c5a-b258-11e7-846e-6f9955b312be.png)
![geo_html](https://user-images.githubusercontent.com/23720899/31592085-5a97fcb8-b258-11e7-8e8d-df69995c5507.png)

**Comment by qindiandadudu** [comment]
line3d 在jupyter notebook中也显示空白
![line3d](https://user-images.githubusercontent.com/23720899/31592398-83ee278e-b25a-11e7-88da-491715c37e4a.png)

**Comment by chfw** [comment]
1. right click and choose "Inspect"
2. go to "console"
3. please get a screenshot of the red error lines and paste it here.

**Comment by chenjiandongx** [comment]
请直接调用 bar3d，在之前不用调用 render() 函数

**Comment by qindiandadudu** [comment]
@chenjiandongx   是的，请直接调用 bar3d/geo可以显示，但是为什么调用了render（）就不显示了呢？这两个有相互影响吗？

**Comment by qindiandadudu** [comment]
@chfw after delete bar3d.render( ) / geo.render( ), it works well
![bar3dwork](https://user-images.githubusercontent.com/23720899/31642798-88b7437a-b31f-11e7-9f4f-ec26fcb924e6.png)

**Comment by chenjiandongx** [comment]
@qindiandadudu 调用实例本身就是一个 `render` 函数，只是形式上把它简化了

**Comment by chfw** [comment]
@chenjiandongx good job. I overlooked those two lines.

**Comment by Shoyee** [comment]
我直接调用geo也不能显示，但是render()可以正常保存打开显示，以下是截图。求解
<img width="1020" alt="屏幕快照 2019-03-15 下午8 05 10" src="https://user-images.githubusercontent.com/34617885/54430186-b70b1c00-475d-11e9-9a7f-cc1f06dd48ef.png">
<img width="592" alt="屏幕快照 2019-03-15 下午8 06 17" src="https://user-images.githubusercontent.com/34617885/54430218-d609ae00-475d-11e9-9e0f-941422dbff40.png">

pyecharts是最新版，其他图形可以在notebook里显示，地图不行，是js文件出错了吗？怎么解决？

**Comment by Shoyee** [comment]
就是头一天还可以显示没问题的，第二天打开运行的时候，就不能显示了

**Comment by Shoyee** [comment]
就是今天安装了pyecharts-snapshot之后，再运行的时候不显示了

**Comment by chfw** [comment]
软件好像没有听说会过期的。前天买的牛奶，昨天吃还没有坏，今天就酸了。
