### ISSUE TITLE
散点图如何通过其他维度来生成visualmap？

### ISSUE THREAD

**Issue by Junosmart** [chenjiandongx/pyecharts#22]
现在散点图似乎只能引入x、y的二维数据，如何针对第三维的数据生成visualmap呢？
另外，好像tooltip项还未能设置？

此库帮助很大，作者加油！

**Comment by chenjiandongx** [comment]
是的 目前只能引入二维的点 后期的版本会考虑你这方面的问题的

**Comment by chenjiandongx** [comment]
@Junosmart 
tooltip 现在已提供部分设置选项，请参考文档

**Comment by chenjiandongx** [comment]
@Junosmart 
![2017-09-17_18-48-57](https://user-images.githubusercontent.com/19553554/30520110-0aac9f28-9bd9-11e7-98f3-fd042e3826d3.gif)

现在已经支持引入第三个维度生成 visualMap
