### ISSUE TITLE
希望可以提供方法，让生成的div的id可读

### ISSUE THREAD

**Issue by SongZhuhai** [chenjiandongx/pyecharts#221]
### 提 issue 注意事项
0. 先仔细阅读文档中是否有关于您需要解决的问题的解决方法
1. 提 issue 前请先搜搜看以往的 issue 有没有解决了您的问题
2. 如若是不能正常使用的问题，请贴上详细的 pyecharts 版本，使用系统以及 Python 版本
3. 最好详细描述问题，必要时加上**代码+贴图**

**Comment by kinegratii** [comment]
目前开发分支dev已经实现该功能，可以使用开发分支或者期待下一个版本。

> 可以访问图表类的chart_id访问图表对象的标识符，该标识符用于标识图表容器(div)和js代码中echarts实例变量名称。

**Comment by SongZhuhai** [comment]
好的，谢谢你们

**Comment by chenjiandongx** [comment]
@SongZhuhai 版本已更新，现 chart_id, width, height 等参数均为可读
