### ISSUE TITLE
请教关于数据视图的问题

### ISSUE THREAD

**Issue by BackboneCN** [chenjiandongx/pyecharts#222]
您好：目前提供的数据视图样式难看，而且不提供EXECL导出下载。请问有办法解决嘛？谢谢

**Comment by chenjiandongx** [comment]
这个我只是调用了 Echarts 官方提供的工具，如果你想有这个功能的话，恐怕得到 Echarts 下面去提 ISSUE 了

**Comment by chfw** [comment]
类似这个应用吗？https://github.com/pyexcel/excel2table。 我认为任何一个包不能求全，而应该求精，而且要精益求精。

**Comment by BackboneCN** [comment]
东哥，我们平时工作这个功能还是非常有用的。有打算加入这个功能嘛？

**Comment by zealotCE** [comment]
个人建议，你把数据转成pandas.DataFrame,然后to_excel 或者 to.csv 功能。
或者你用其他的转excel 的库。
