### ISSUE TITLE
图标与html结合

### ISSUE THREAD

**Issue by rickyi22** [chenjiandongx/pyecharts#224]
版本：0.2.3
我生成了radar、heatmap等html格式的文件后，如果我要加到我的HTML5文件里的话， 可以保持原来可以点击的状态吗？ 因为只知道比较简单的H5制作，希望大神能指导一下～
是直接把整个html文件的source放进去就可以吗  <html></html> 之间的部分

**Comment by chenjiandongx** [comment]
@rickyi22 可以的，复制生成的 render.html 的 <body> 部分，再在 <head> 中引入 `<script src="https://cdn.bootcss.com/echarts/3.6.2/echarts.min.js"></script>` 就可以了
