### ISSUE TITLE
文档整理建议

### ISSUE THREAD

**Issue by kinegratii** [chenjiandongx/pyecharts#226]
目前文档内容较多，也涉及到不同的主题，建议作一份目录或者Checklist，分类的方法可以有多种

- 可以按照使用方法步骤（安装、使用、API、FAQ）划分
- 可以按照使用场景/应用领域划分
- 当然也可以综合上述几种划分。

具体可参考 [django官方文档](https://docs.djangoproject.com/)

**Comment by chenjiandongx** [comment]
@kinegratii 能否给我你的邮箱地址

**Comment by chfw** [comment]
最好能分页，而且能生成PDF

**Comment by kinegratii** [comment]
@chenjiandongx  

github账号：kinegratii#gmail.com
个人邮箱：kinegratii#yeah.net
(将#换成@)

**Comment by chenjiandongx** [comment]
@kinegratii 
请检查您的邮箱 kinegratii@yeah.net
