### ISSUE TITLE
如何实现ECharts 中的事件和行为

### ISSUE THREAD

**Issue by fuxuemingzhu** [chenjiandongx/pyecharts#227]
Echarts的官网中提供了自定义事件和行为的方法，请问在pyecharts+Flask中，如何实现类似下面效果：

```javascript
myChart.on('click', function (params) {
    // 控制台打印数据的名称
    console.log(params.name);
});
```

参见echarts官网地址：[http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA](http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)

**Comment by chenjiandongx** [comment]
Fixed
