### ISSUE TITLE
功能前瞻：自定义模板和模板函数

### ISSUE THREAD

**Issue by kinegratii** [chenjiandongx/pyecharts#228]
## 概述

目前图表渲染函数 `Base.render()` 暂不支持（即没有公开明确的参数）自定义模板页面，和Django/Flask等web框架整合没有简单统一的方式，使用者又多有需求（ #225 、#213 、#184 ）。

鉴于此，本人基于现有代码，另开一个分支（地址： https://github.com/kinegratii/pyecharts/tree/feature_template_function  ）完成该功能，目前已经完成预览版，现将功能说明如下，以供大家讨论。

## 使用方法

1 python 代码

```python

from jinja2 import FileSystemLoader
from pyecharts import Bar
from pyecharts.engine import EchartsEnvironment
from pyecharts.utils import write_utf8_html_file

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar = Bar("柱状图数据堆叠示例", jshost='https://cdn.bootcss.com/echarts/3.6.2')
bar.add("商家A", attr, v1, is_stack=True)
bar.add("商家B", attr, v2, is_stack=True)

env = EchartsEnvironment(loader=FileSystemLoader('.'))
tpl = env.get_template('demo.html')
write_utf8_html_file('demo_gen.html', tpl.render(bar=bar))
```

2 模板页面

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>自定义模板</title>
    {{ echarts_js_dependencies(bar) }}
</head>
<body>
{{ echarts_container(bar) }}
{{ echarts_js_content(bar) }}
</body>
</html>
```
3 生成后的html页面源代码，为表示页面结构，省略options内容。

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>自定义模板</title>
    <script type="text/javascript" src="https://cdn.bootcss.com/echarts/3.6.2/echarts.js"></script>
</head>
<body>
<div id="47c0e8643c1c4fefbad818ab83523609" style="width:800px;height:400px;"></div>
<script type="text/javascript">

    var myChart_47c0e8643c1c4fefbad818ab83523609 = echarts.init(document.getElementById('47c0e8643c1c4fefbad818ab83523609'));
    var option_47c0e8643c1c4fefbad818ab83523609 = {
    };
    myChart_47c0e8643c1c4fefbad818ab83523609.setOption(option_47c0e8643c1c4fefbad818ab83523609);
    
</script>
</body>
</html>
```

## 代码和功能变更内容

- 新增 `pyecharts.engine` 模块
- 提取模板引擎相关内容，新增 `pyecharts.engine.EChartsEnvironment` 类
- 此类增加若干个模板函数，其API文档详见 [模板函数](https://github.com/kinegratii/pyecharts/blob/feature_template_function/docs/zh-cn/api.md#模板引擎)
- 其他功能优化增强，比如 width/height也支持有效字符串内容。
- 新增单元测试案例

## 几点说明

- 由此此项功能影响比较大，和正常开发会一些不太一样的地方。
    - 目前代码变更仅在本人仓库内进行，待讨论成熟充分后才合并到主分支‘
    - 为了不影响现有代码，基本上是新增一个全新的 [engine](https://github.com/kinegratii/pyecharts/blob/feature_template_function/pyecharts/engine.py) 模块，但一些工具性函数会重复书写
- 代码风格：为了实现自定义功能，代码多采用类继承和面向对象的方式改造原有代码。

## 后续功能

- 在Flask/Django 更加方面的集成整合
- API规范化 

欢迎大家讨论。

**Comment by chfw** [comment]
引用模版函数功能很有创意，可以进一步完善看看：

1. 替代内嵌的 JINJA2_ENV，并进一步替代现有的一些模版 --> 实现之后，是否可以考虑：bar.render(template='custom_template')
2. configure()函数与template.online雷同，可以取其一。

我的疑问是：如何解决响应式的div 需求。

**Comment by chfw** [comment]
Page 继承 list 👍

**Comment by chfw** [comment]
伴随文档和测试 💯

**Comment by chenjiandongx** [comment]
@chfw 
`bar.render(template='custom_template')` 这个想法不错，@chenjiandongx 表示支持

**Comment by kinegratii** [comment]
@chenjiandongx  @chfw 

后续的计划

- `JINJA2_ENV` 全局变量改用 `EChartsEnvironment` 进行实例化
-  `bar.render(template='custom_template'， object_name='chart'')` 增加若干可选参数
    - template 模板文件名称
    - object_name 模板文件中该图表对象的变量名称

`configure` 函数目前是为了不影响原有代码复制了一份。后续有打算所有配置信息整理成一个类。将这个函数改为全局性配置函数。然后使用以下方式调用。

```python
import pyecharts
from pyecharts import Bar

# 配置所有参数

pyecharts.configure(
    template_dir='.', # 模板文件目录为当前目录
    jshost='https://cdn.bootcss.com/echarts/3.6.2'
)
bar = Bar()
bar.render(template='my_bar_tpl.html', path='my_bar.html', object_name='bar')
....
```
关于 内置模板文件和自定义模板文件的查找逻辑 之后整理下再发布。

**Comment by chenjiandongx** [comment]
要不就新增一个 Configure 类吧 from pyecharts import Configure

**Comment by kinegratii** [comment]
目前已经针对 Chart.render() 进行改造

过渡兼容版本，使用 new_version作为开关。
```python
Chart.render(
    path='render.html', 
    new_version=False, template_name='simple_chart.html',object_name='chart'
)
```
最后的版本
```python
Chart.render(path='render.html', template_name='simple_chart.html',object_name='chart')
```
各参数意义：

*  path：生成的html文件路径，同旧版
* template_name：模板文件，其模板目录通过 `configure` 函数进行设置。
* object_name： 模板文件中，表示图表对象的变量的名称

JINJA2_ENV 对象变更：

* 继承 `EChartsEnvironment` ，支持 echart_* 系列模板函数
* 增加全局变量 `pyecharts.conf.DEFAULT_CONFIG.echarts_template_dir` 指向目录为搜索路径，**并且优先级在原有templates目录之前**
