### ISSUE TITLE
pycharm安装报错

### ISSUE THREAD

**Issue by linfanli** [chenjiandongx/pyecharts#23]
使用pycharm安装,提供缺少model报错

py27＋pycharm
ImportError: No module named Image

<img width="736" alt="2017-07-28 10 44 43" src="https://user-images.githubusercontent.com/16367420/28700446-660c1c6a-7382-11e7-8843-d9b6c59fcd19.png">

py36＋pycharm
ModuleNotFoundError: No module named 'jinja2'

<img width="736" alt="2017-07-28 10 45 25" src="https://user-images.githubusercontent.com/16367420/28700450-70947196-7382-11e7-964c-cc6afc5ad64b.png">

**Comment by chenjiandongx** [comment]
try to exec pip install Image and pip install jinja2

**Comment by linfanli** [comment]
- py27

 install packages as follow: print, pytz, django, Image, jinja2 ,piecharts 

py3.6 

-  install packages as follow: print, pytz, django, Image ,piecharts
