### ISSUE TITLE
折线图上标记点显示不全

### ISSUE THREAD

**Issue by zealotCE** [chenjiandongx/pyecharts#231]
作者你好，我使用pyecharts的折线图时，发现一些疑问希望请教一下
问题1
1. 发现折线图的标记点显示不完全。如**图1图2** 
2. 我这里 x 轴是9月8日到10月的16日的，但是图中可以看到标记点只有在底部有标签的情况下才可以显示。如**图3**
**我的问题是：** 有没有办法在不完全显示底部标签的情况下，显示所有标记点？
补充一下为什么一定要显示所有标记?
因为不显示标记的话，根本没办法看到没有标记点的数据，只能看到图形，但是鼠标放上去没有反应。

![sp171025_175517](https://user-images.githubusercontent.com/26129403/31992956-57f9a9d6-b9ae-11e7-9f83-33c9dfda28ec.png)

![data1](http://om80aljc8.bkt.clouddn.com/17-10-25/35668630.jpg)

![data2](http://om80aljc8.bkt.clouddn.com/17-10-25/21738256.jpg)
问题2：
1. 如图1，我这边使用 mark_point 时，自定义的标记没有生效。
`line.add('次留',attr, value, xaxis_interval = 0 ,xaxis_rotate = 90 ,yaxis_formatter=" %", mark_point = ["average", "max", "min",{"coord":['2017-9-13', 35],'name':"第二天的留存为1.5%"}] )
`
中的 {"coord":['2017-9-13', 35],'name':"第二天的留存为1.5%"}  这里没有效果。
所以，请问我这里应该怎么调整才可以让自定义的标记显示出来呢?

问题3：
1. 请问如果我想显示百分比数据应该怎么做呢？

环境
pyecharts 0.26版本
python 3.6
jupyter环境
windows 10 17017 64bit

**Comment by chenjiandongx** [comment]
是否方便把数据贴上来或者发送至我邮箱 我方便测试

**Comment by zealotCE** [comment]
邮件已发送~
sorry 我才看到。

**Comment by chenjiandongx** [comment]
你好，试了你给的数据，确实无法实现你想要的效果，当数据量多的时候单个 markPoint 标不出来。

**Comment by zealotCE** [comment]
@chenjiandongx   嗯~  主要是标识没有的话还好，就是数据也看不到就比较糟心了。（换成直方图也没事
然后我想问一下，目前从echarts 官网里面有很多特殊图形pyecharts 目前还是不支持的，所以我想问下如果我想让pyecharts 支持这些图的话，需要做些什么？

**Comment by chenjiandongx** [comment]
可能需要一个 PR

**Comment by zealotCE** [comment]
嗯，明白。

**Comment by zealotCE** [comment]
请close吧

**Comment by chenjiandongx** [comment]
你是有权限 close 的，如果你觉得问题解决了可自行 close

**Comment by zealotCE** [comment]
好
