### ISSUE TITLE
正式发布 v0.2.7 版本

### ISSUE THREAD

**Issue by chenjiandongx** [chenjiandongx/pyecharts#233]
* ### version 0.2.7

    #### Added
    * 新增 GeoLines（地理坐标系线图）
    * [issue#230](https://github.com/chenjiandongx/pyecharts/issues/230) 新增工具类 `Style`，用于简化代码编写和统一风格

    #### Fixed
    * 修复 Geo 系列名无法正常显示的问题
    * [issue#229](https://github.com/chenjiandongx/pyecharts/issues/229) 修复水球图不能自定义图形的问题

    #### Changed
    * [issue#232](https://github.com/chenjiandongx/pyecharts/issues/232) Grid, Overlap, Timeline 类初始化参数的变动

    #### 文档整理拆分为以下篇章
    * [pyecharts 文档-预览篇](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_prepare.md)
    * [pyecharts 文档-图形篇](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_charts.md)
    * [pyecharts 文档-API 篇](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_api.md)
    * [pyecharts 文档-版本篇](https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md)
    * [pyecharts 文档-画廊篇](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_gallery.md)
    * [pyecharts 文档-FAQ 篇](https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_faq.md)

**Comment by Siffre** [comment]
辛苦大佬

**Comment by Siffre** [comment]
真他妈的漂亮，匆匆的过了一遍所有！！

**Comment by chenjiandongx** [comment]
@Siffre 还不赶紧拉你的小伙伴来 star

**Comment by Siffre** [comment]
@chenjiandongx  哈哈哈，必须的

**Comment by Siffre** [comment]
@chenjiandongx 有时间做个官网出来吧，类似ehcarts那种，现在的官网不是很美观

**Comment by chenjiandongx** [comment]
这符合Python 简洁优雅的风格

**Comment by 416104443** [comment]
render_notebook()函数被取消了么,不能在jupyter notebook中使用了啊

**Comment by chfw** [comment]
错过大家庆祝时间了。与0.2.7同步，网上pyecharts.js-app体验站与pyecharts-app联通，并正式面向大家服务。这个是简介：https://github.com/chenjiandongx/pyecharts-app/pull/1。 觉得好的话，请点star!!

除了可以看@chenjiandongx的例子外,还可以用在问问题的时候，你可以把你的例子这么放：'https://chfw.github.io/pyecharts.js-app/#' + 'http://your.domain/your/url/to/your/pyecharts.code'， 这样所有人可以点击过去看看。

比如：
https://chfw.github.io/pyecharts.js-app/#https://raw.githubusercontent.com/chfw/pyecharts-app/master/app/charts/bar3d.py

**Comment by Siffre** [comment]
@chfw 404~\(≧▽≦)/~啦啦啦

**Comment by chfw** [comment]
http://pyecharts.herokuapp.com/ 入口

**Comment by chfw** [comment]
<img width="1267" alt="screen shot 2017-10-28 at 07 17 14" src="https://user-images.githubusercontent.com/4280312/32131844-2f62ae60-bbb0-11e7-8afb-e850279fa150.png">

**Comment by chfw** [comment]
@Siffre , 问题解决了？

**Comment by chenjiandongx** [comment]
@416104443 
https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/doc_prepare.md
有疑问，先看文档
