### ISSUE TITLE
Polar图中的barAngle类型中起始刻度的角度不能更改。而且没有分割线

### ISSUE THREAD

**Issue by zmzxzmzx** [chenjiandongx/pyecharts#234]
生成Polar中的barAngle类型的图表时，起始刻度的角度不能更改，而且没有分割线。在polar.py中的这一段的中加入最后二行，即可调整角度和显示分割线。
            elif type == "barAngle":
            self._option.get('series').append({
                "type": "bar",
                "stack": is_stack,
                "name": name,
                "coordinateSystem": 'polar',
                "data": data,
            })
            self._option.update(radiusAxis={
                "show": is_radiusaxis_show,
            })
            self._option.update(
                angleAxis={
                    "show": is_angleaxis_show,
                    "type": polar_type,
                    "data": radius_data,
                    "z": 50,   
                    "startAngle": start_angle,
                    "splitLine": chart['split_line'],

**Comment by chenjiandongx** [comment]
你用的是哪个版本的 pyecharts

**Comment by zmzxzmzx** [comment]
0.2.6

**Comment by chenjiandongx** [comment]
```
"startAngle": start_angle,
"splitLine": chart['split_line'],
```
这两行 https://github.com/chenjiandongx/pyecharts/blob/master/pyecharts/charts/polar.py#L149 不是有吗

**Comment by zmzxzmzx** [comment]
是有，但是类型不是barAngle。
  if type not in ("barAngle", "barRadius"):

问题是barAngle里没有

**Comment by zmzxzmzx** [comment]
![image](https://user-images.githubusercontent.com/33147529/32096624-8f7047d0-bb39-11e7-913c-53e69157d031.png)

**Comment by zmzxzmzx** [comment]
type=="barAngle":这里是没有的

**Comment by chenjiandongx** [comment]
确实，那你是想提交个 PR 过来，还是我这边自己改

**Comment by zmzxzmzx** [comment]
我不会提交PR……

**Comment by chenjiandongx** [comment]
如果你愿意你可以学习一下这个可以留给你 然后你也会成为这个项目的 contributor 之一了

**Comment by zmzxzmzx** [comment]
好呀，我周末学习一下，谢谢！

**Comment by chenjiandongx** [comment]
记得推送至 dev 分支
