### ISSUE TITLE
当数值为负数时，TreeMap显示不正确

### ISSUE THREAD

**Issue by enalpha** [chenjiandongx/pyecharts#236]
本来打算做一个treemap用于显示股票百分比变动其中包括了负百分比，我发现了当数据为负值的时候直接忽略掉。 有没有办法解决这个问题？
```
from pyecharts import TreeMap

data = [
    {
        "value": 10,
        "name": "我是A",
    },
    {
        "value": 10,
        "name": "我是B",
        "children": [
            {

                'children': [
                    {
                        'value': 12,
                        "name": "我是B.children.a"
                    },
                    {
                        "value": 28,
                        "name": "我是B.children.b"
                    },
                    {
                        "value": 20,
                        "name": "我是B.children.c"
                    },
                    {
                        "value": 16,
                        "name": "我是B.children.d"
                    }],
                "value": 2,
                "name": "我是B.children",                
            }]},
            {'children': [{'value': -1.9, 'name': '浙大网新'}, 
              {'value': -1.8, 'name': '综艺股份'}, 
              {'value': -0.7, 'name': '佳都科技'}, 
              {'value': -1.3, 'name': '烽火通信'}, 
              {'value': 1.3, 'name': '信威集团'}, 
], 
'value': 10, 
'name': 'IPV6概念'}
]


treemap = TreeMap("树图-下钻示例", width=1200, height=600)
treemap.add("演示数据", data, is_label_show=True, label_pos='inside',
            treemap_left_depth=2)
treemap.render()
```
![qq20171028-160856](https://user-images.githubusercontent.com/27722028/32132653-38572348-bb8d-11e7-93b3-9530cac1638e.png)

第二个问题是，如何在每一格TreeMap顶部加入相应大类名称。我在echarts官网的treemap例子中发现有一个example的treemap的每格顶部上可以显示大类名称。例如二图中的“Speech”，“Frameworks”。我浏览过源代码，其相应代码为：
```
                upperLabel: {
                    normal: {
                        show: true,
                        height: 30
                    }
                },
```
但是upperLabel这个option在pyecharts并没有找到。

![qq20171028-161011](https://user-images.githubusercontent.com/27722028/32132657-5812e1a4-bb8d-11e7-8860-6af07c3774f0.png)

**Comment by chenjiandongx** [comment]
第一个问题
![image](https://user-images.githubusercontent.com/19553554/32143602-d832d2cc-bce6-11e7-91ad-9df29db02bb6.png)
官方说的对应的是面积，那负数可能就不行了

第二个问题我可以把 upperLabel 这个配置项加上去

**Comment by chenjiandongx** [comment]
我试了一下，加上
```
upperLabel: {
                    normal: {
                        show: true,
                        height: 30
                    }
                },
```

结果是这样的
![image_78](https://user-images.githubusercontent.com/19553554/32143903-d664e994-bceb-11e7-9283-77c340eee1fc.png)

如果查看你的官方示例的话，可以发现，主要配置在这行里。
![image_79](https://user-images.githubusercontent.com/19553554/32143920-1faaff76-bcec-11e7-9568-0e491fcd26b0.png)

他是按 level 来配置的。

**Comment by enalpha** [comment]
你意思是并不是简单地添加upperlabel就可以实现上述功能？ 是不是实现不了？不过也很感谢你的尝试。

**Comment by chfw** [comment]
how about this:

https://chfw.github.io/pyecharts.js-app/#https://raw.githubusercontent.com/chfw/pyecharts-qa/master/questions/tree-map-29-10-17/query.py

<img width="1099" alt="screen shot 2017-10-29 at 15 55 43" src="https://user-images.githubusercontent.com/4280312/32145508-b0f157a8-bcc1-11e7-8bbb-68340160ab0c.png">

**Comment by chenjiandongx** [comment]
我不是说不能实现 是配置项比较多 @chfw 这个就是实现方法

**Comment by enalpha** [comment]
thank you guys for the works!!
