### ISSUE TITLE
如何实现动态更新pyecharts？ Streaming from Templates or Streaming with Context

### ISSUE THREAD

**Issue by enalpha** [chenjiandongx/pyecharts#238]
本来想pyecharts+flask 定时更新图表：
1. 每隔一分钟下载csv 后传递给pyecharts
2.用flask无刷新显示出来

看过很多教程，后来才发现是出于streaming的范畴。
于是乎参考了http://flask.pocoo.org/docs/0.12/patterns/streaming/的文献。但发现怎么弄都实现不了上述的效果。所以唯有求助。
```
#官网提供的用于streaming
def stream_template(template_name, **context):
    app.update_template_context(context)
    t = app.jinja_env.get_template(template_name)
    rv = t.stream(context)
    rv.enable_buffering(5)
    return rv

#下面这个代码是有问题的，但搞不清楚什么问题。
@app.route("/")
def plot_chart():
    def g():
        stm= stocktreemap()
        return render_template('index.html',
                               myechart=stm.render_embed(),
                               host=DEFAULT_HOST,
                               script_list=stm.get_js_dependencies())
    return Response(stream_template(g()))
    
```

**Comment by kinegratii** [comment]
@enalpha 

几点建议：

- 代码还不够完整，缺少相关import语句和一些变量注释。
- 由于Flask数据流（Stream With Context）这个知识点并不常见，所以应当使用官方例子解释该功能，最好附上运行效果。
- 问题具体情况？无法加载，无法达到预期效果。

**Comment by enalpha** [comment]
我想了想，这个应该跟之前的jquery"异步数据加载和更新"的问题一样，还是再研究研究。

**Comment by chfw** [comment]
有三种方法:

1. Active polling, 就是你所说的用 ajax, 不断检查新数据。
2. 用server sent event, 服务器主动发送数据，单向交互。这里，你需要用tornado
3. 用websocket,实现双向数据的实时交互. 你可以参考https://github.com/miguelgrinberg/Flask-SocketIO-Chat

**Comment by enalpha** [comment]
上面提到的方法都不是很熟悉，我会认真研究的。谢谢
