### ISSUE TITLE
Heatmap 里面，数据视图显示的数据错误

### ISSUE THREAD

**Issue by zealotCE** [chenjiandongx/pyecharts#246]
1.Heatmap 里面，数据视图显示的数据错误
2.Heatmap is_calender =True 右侧保存为图片、查看数据视图等的选项没有了
直接使用文档中示例代码也是如此，我就不额外贴代码了。
![image](https://user-images.githubusercontent.com/26129403/32317481-e2d6d56a-bfee-11e7-871b-b6693b029def.png)

环境
pyecharts 0.27
python 3.6
jupyter
win10 17025 x64

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/32324353-1130aa0a-c006-11e7-989f-30e8fc8fb345.png)

下个版本开始就可以了

**Comment by zealotCE** [comment]
Nice

**Comment by zealotCE** [comment]
请close吧
