### ISSUE TITLE
考虑加个table进来吗

### ISSUE THREAD

**Issue by scczy2004** [chenjiandongx/pyecharts#25]
多图组合显示时，除了看图，很多时候还会想要看表，能不能再加入个表格，可以展示数据，并且表格可以与图混排？  谢谢

**Comment by chenjiandongx** [comment]
这个暂时做不到，Echarts 现在还没有提供 table

**Comment by 984958198** [comment]
基于 TreeMap（矩形树图） 可以做到吗？ 能的话 我研究一下
