### ISSUE TITLE
flask + pyecharts 有时页面无法正常显示

### ISSUE THREAD

**Issue by adlinx** [chenjiandongx/pyecharts#251]
- 本地打开没问题
- 不清楚是不是连接 js库出了问题

**Comment by chfw** [comment]
Right click => inspect => console => read errors

**Comment by adlinx** [comment]
- GET https://chfw.github.io/jupyter-echarts/echarts/echarts.min.js net::ERR_TIMED_OUT
- 看报错应该是js库  请求超时了 @chfw 
- 放本地就是不太清楚路径这些该怎么设置

**Comment by chenjiandongx** [comment]
两种方法解决这个问题
1. 挂自己服务器上，挂本地服务器也行
2. 放入静态文件夹里，具体设置可以参考 pyecharts-app 配置源码

**Comment by adlinx** [comment]
- 我看了您的 pyecharts-app 项目， 在
`return render_template('base.html',
                           title='折线图',
                           source_file='line',
                           myechart=_line.render_embed(),
                           script_list=_line.get_js_dependencies())`
这段代码中 没看见您 示例里的 host=DEFAULT_HOST,这个参数，所以现在不太清楚这个host怎么设置 @chenjiandongx

**Comment by chenjiandongx** [comment]
参考 base.html

**Comment by adlinx** [comment]
- 完美运行，谢谢大佬！ @chenjiandongx

**Comment by chfw** [comment]
Github 外挂 https://chfw.github.io/jupyter-echarts/echarts/echarts.min.js 是折中选择。严肃的开发的话需要自己内挂jupyter-echarts.
