### ISSUE TITLE
K线图的最大值、最小值标记问题

### ISSUE THREAD

**Issue by guyansrg** [chenjiandongx/pyecharts#258]
在0.2.7版本中，K线图若只设置mark_point=["max", "min"]的话，只会标记开盘价的最大值和最小值。
**能不能最大值标记highest的，最小值标记lowest的？** 

**炒股软件里的K线图惯例画法是：最大值标记highest的，最小值标记lowest。**

(相关Issue： #199)

**Comment by chenjiandongx** [comment]
@guyansrg 
![image](https://user-images.githubusercontent.com/19553554/32940418-91b52a26-cbbd-11e7-8305-d6a67bbae0c3.png)

**Comment by guyansrg** [comment]
非常谢谢你能及时修改。希望修改版本能早点发布。
