### ISSUE TITLE
请问右侧的小工具可以设置不显示吗

### ISSUE THREAD

**Issue by joylin1984** [chenjiandongx/pyecharts#260]
感谢作者的付出，很喜欢这个项目。
我用pyecharts在pyqt里绘图，可能是pyqt的webview内核问题，右侧的小工具无效了，不知道能不能设置不显示呢。

**Comment by fuxuemingzhu** [comment]
我也需要问这个问题，我用pyecharts+flask做了图，现在在前端展示的时候，图的右边有三个小工具，这样不美观，求问怎么去掉。

**Comment by chenjiandongx** [comment]
看来需要考虑这个问题了

**Comment by chenjiandongx** [comment]
@fuxuemingzhu @joylin1984 从下个版本开始提供 `is_toolbox_show` 参数，指定为 False 即可取消显示工具箱。

**Comment by joylin1984** [comment]
谢谢了，期待新版
