### ISSUE TITLE
功能建议 itemStyle

### ISSUE THREAD

**Issue by zealotCE** [chenjiandongx/pyecharts#261]
原因：
因为一些个人原因转回去了解了一下echarts，发现使用pyecharts中无法对item较为可惜。希望能够添加这个功能。

过程：
我去了解了一下echarts，发现其中绝大部分的图形都是支持 itemStyle 这一项的。
并且其itemStyle项下为两种类型：normal和emphasis
（两种的子属性都是 color, bordercolor, borderWidth, borderType, shadowBlur, shadowColor, shadowOffsetX, shadowOffsetY, opacity (部分图形有areaColor，我觉得可以忽略掉）
>注：color 项如果没有设置他会自己从默认的色盘中选取颜色，但是我想如果能自定义颜色也许会更好吧。

希望 itemStyle 能够成为pyecharts的新的通用配置项，请作者看看有没有加入的可能。
我还是希望pyecharts能在方便简单的情况下越来越强大。

**Comment by chenjiandongx** [comment]
后续版本可以考虑引入这部分的配置参数

**Comment by zealotCE** [comment]
Nice
