### ISSUE TITLE
文档问题与建议

### ISSUE THREAD

**Issue by kinegratii** [chenjiandongx/pyecharts#263]
## 问题与建议

- 建议新增一个索引表
- *doc_charts.md* 标题链接已失效，需更新
- 建议整合 Jupyter Notebook 相关内容，可命名为 *doc_jupyter_notebook.md*,与 `Flask` 等同级
    - 包括安装、使用、注意事项等
    - *docs/notebook-user-cases.zip* 是否考虑解压为一个文件夹，直接存储ipynb 文件，并在文档中注明这些文件如如何使用
- 增加发布日志

### 索引示例

自己整理现有文档资料，仿照 Django 文档首页，完成一个索引表。两级标题，二级标题使用 | 分割不会看起来很长。

----

开始

安装 | 第一个示例

图表选项

初始化参数 | 通用配置项 | 图表详细 | 用户自定义 | 地图文件管理

**API**

渲染流程 | 配置项 | 图表类 | 模板引擎 | 工具函数

**插件与扩展**

pyecharts-snapshot | jupyter-echarts |演示平台

**平台集成**

Jupyter Notebook | Flask框架 | Django框架

FAQ

**Python2编码**

**项目开发**

版本更新 | 开发者列表 | 交流

----

内容描述：

- 【图表选项】和【API】可以链接到现有文档。
- 【插件与扩展】单独增加一页
- 【平台集成 - Jupyter Notebook】：整合现有文档安装扩展，使用，一些问题。
- 【平台集成 - Flask】：合并现有相关文档
- 【FAQ】：一些杂项，内容比较少的都可归于此项
- 【项目开发 - 版本更新】： changelog.md
- 【项目开发 - 开发者列表】：描述项目参与项目的一些约定，比如 Flake8应用、单元测试与CI集成测试
- 【项目开发 - 交流】：微信群、邮箱等联系方式

**Comment by chenjiandongx** [comment]
1. 那应该考虑创建一个 doc_index.md 只在这个文件维护其他文档链接。
2. doc_jupyter_notebook.md 也可以考虑增加，不过不建议解压文件夹，建议还是打成压缩包，不然项目会直接变为 Notebook 类型。
3. 发布日志指的不是 changelog.md 吗？

**Comment by chfw** [comment]
可以用 [gitattributes](https://github.com/chfw/jupyter-echarts/blob/master/.gitattributes) 强制为python
`doc_jupyter_notebook.md 也可以考虑增加，不过不建议解压文件夹，建议还是打成压缩包，不然项目会直接变为 Notebook 类型。`

**Comment by chfw** [comment]
请考虑用sphinx 或 mkdocs 自动可读性强产生文档。个人推荐readthedocs.org

**Comment by chenjiandongx** [comment]
@chfw 发现 readthedocs.org 已经注册过 pyecharts 这个项目了 http://pyecharts.readthedocs.io/en/latest/

**Comment by kinegratii** [comment]
@chenjiandongx 

发布日志，即每次发布功能介绍汇总，用于新版本发布时的一篇通稿，可以发布到知乎、微博、个人博客等社交媒体的文章。比如这篇文章 https://zhuanlan.zhihu.com/p/29785047 。

- 是对 changelog.md 详细介绍。
- 正式文档主要记载 V0.2.0 、V0.3.0  分别有哪些内容，而这个发布日志，主要记录新的功能使用教程和迁移教程，引导用户升级到新版本。
- 当然并不是每次发布都需要一个发布日志。

文档生成方面，可以先用工具生成。

托管平台或者使用 github 自带的 项目Pages。

**Comment by chenjiandongx** [comment]
@kinegratii 接受你的建议，可以在 docs 文件下新建个 changelog 文件夹，放发布日志。

**Comment by chfw** [comment]
@chenjiandongx ，正在联系http://pyecharts.readthedocs.io/的现任作者，等回复。
