### ISSUE TITLE
是否支持flask中依赖js文件本地读取?

### ISSUE THREAD

**Issue by dengshaochun** [chenjiandongx/pyecharts#265]
关于在flask中使用echarts：
 > host 是 echarts js 库的地址，默认的地址为 http://chfw.github.io/jupyter-echarts/echarts 当然，如果你愿意你也可以改变这个地址，先克隆 https://github.com/chfw/jupyter-echarts 然后将 echarts 文件夹挂载在你自己的服务器上即可。

目前我使用内网环境,这个步骤感觉很麻烦，是否支持从本地文件夹读取呢？

**Comment by chfw** [comment]
打开pyecharts.tar.gz 或 `python install directory/lib/site-packages/`

找到并放在你的服务器下：pyecharts/templates/js

**Comment by chenjiandongx** [comment]
@dengshaochun 参考 pyecharts-app ，使用 static 文件夹。

**Comment by dengshaochun** [comment]
@chfw 看了下pyecharts-app，我先去尝试下，非常感谢。
