### ISSUE TITLE
曲线图怎么显示每一点的值

### ISSUE THREAD

**Issue by evido3s** [chenjiandongx/pyecharts#269]
请教下，曲线图怎么显示每一点的值，没有看到文档中说明是哪个属性

**Comment by shieleven** [comment]
is_label_show=True

**Comment by evido3s** [comment]
@shieleven  thanks，另想请教下，怎么在x轴上把时间显示完全，
![image](https://user-images.githubusercontent.com/19970961/33305118-7ec9cb00-d447-11e7-8478-553d869e9e46.png)

**Comment by shieleven** [comment]
xaxis_interval=0
多看文档

**Comment by evido3s** [comment]
@shieleven  但有个问题，x轴日期把间隙占了，无法显示完整的日期，请问这个有方法吗
![image](https://user-images.githubusercontent.com/19970961/33375976-d5c0a596-d546-11e7-8ee4-d389c1e844b1.png)

**Comment by evido3s** [comment]
看文档我知道了，还是要多看文档，谢谢，
