### ISSUE TITLE
为什么无法生成图，run cells后只是显示一些详细的信息。

### ISSUE THREAD

**Issue by lovexj88** [chenjiandongx/pyecharts#27]
类似与这种：{'_index_flag': 1833663,
 'angleAxis': {'axisLine': {'lineStyle': {'normal': {'curveness': 0,
                                                     'opacity': 1,
                                                     'type': 'solid',
                                                     'width': 1}},
                            'show': True},
               'boundaryGap': False,
               'clockwise': True,
               'data': [1,

**Comment by chenjiandongx** [comment]
所有图形都无法显示吗 使用了 render_notebook() 方法了吗

**Comment by lovexj88** [comment]
可以了，可以了。
