### ISSUE TITLE
可否增加表格形式的图表展示？

### ISSUE THREAD

**Issue by shieleven** [chenjiandongx/pyecharts#270]
因工作汇报需要，需要将源数据生成类似excel的表格形式，直接在页面显示后，再生成网页快照，发送至相关人员邮箱。
目前想到的方案是模拟点击图表-数据视图按钮，再生成网页快照。但是显示效果较差。
可否增加表格形式的图表展示？

**Comment by shieleven** [comment]
找到了官方事例。问题关闭http://echarts.baidu.com/option.html#toolbox.feature.dataView.optionToContent

**Comment by MatthewZou9419** [comment]
+1
