### ISSUE TITLE
Geo地图标签使用{c}的时候如何可以不显示坐标值（经纬度）

### ISSUE THREAD

**Issue by ilcityfox** [chenjiandongx/pyecharts#272]

**Comment by chenjiandongx** [comment]
暂时没什么办法，因为这个在 Echarts 是用回调函数实现的。Python 无法传递函数过去，https://github.com/chenjiandongx/pyecharts/issues/192

**Comment by ilcityfox** [comment]
OK, 收到，谢谢！
