### ISSUE TITLE
有没有办法用excel的一列文字，或者一个数组做Geo地图上的标签？谢谢！

### ISSUE THREAD

**Issue by ilcityfox** [chenjiandongx/pyecharts#274]
### 提 issue 注意事项
0. 先仔细阅读文档中是否有关于您需要解决的问题的解决方法
1. 提 issue 前请先搜搜看以往的 issue 有没有解决了您的问题
2. 如若是不能正常使用的问题，请贴上详细的 pyecharts 版本，使用系统以及 Python 版本
3. 最好详细描述问题，必要时加上**代码+贴图**

**Comment by chenjiandongx** [comment]
@ilcityfox 下次请先把 ISSUE 提示模板删除，这个没有办法实现，如果是单个地区对应单独的文字的话，因为在 Echarts 是用回调函数来实现的，Python 在这边无法传递函数过去。

**Comment by ilcityfox** [comment]
ok，谢谢
