### ISSUE TITLE
对于Line, Bar等，如何控制显示范围（也就是Y轴的范围）？

### ISSUE THREAD

**Issue by xbanke** [chenjiandongx/pyecharts#28]
系统自动设置的范围 有些时候比较傻，会把图压得很扁。

axis_range ：这个参数似乎对Line等不起作用。

**Comment by chenjiandongx** [comment]
当前版本没有提供这个参数配置，后期版本会考虑加入的。

**Comment by xbanke** [comment]
或者 is_datazoom_show 能否也加在 y轴上？

**Comment by chenjiandongx** [comment]
@xbanke 
后续版本再考虑吧 目前主要精力在编写英文文档

**Comment by chenjiandongx** [comment]
@xbanke 
版本已更新
