### ISSUE TITLE
jupyter notebook内无法显示Timeline的问题

### ISSUE THREAD

**Issue by zgnecah** [chenjiandongx/pyecharts#280]
有没有解决方案？貌似所有Timeline相关的在Juypter Notebook内都显示不了

**Comment by chenjiandongx** [comment]
* ### version 0.3.1
    * [issue#290](https://github.com/chenjiandongx/pyecharts/issues/290) 紧急修复 v0.3.0 版本不能正常显示图形的严重 bug
    * [issue#296](https://github.com/chenjiandongx/pyecharts/issues/296) 修复 Timeline 不能在 notebook 中显示的 bug
