### ISSUE TITLE
jupyter notebook download as html 后再在浏览器打开看不见图片

### ISSUE THREAD

**Issue by Longtailneighbor** [chenjiandongx/pyecharts#281]

**Comment by Longtailneighbor** [comment]
在jupyter notebook 里画好图，然后file-下载为html， 再浏览器打开，无法看到图片

**Comment by chfw** [comment]
用"online()"。 不过0.3.0之后，这个online()函数被替代了，届时通知。

例子:

https://nbviewer.jupyter.org/github/pyexcel/pyexcel/blob/v0.6.0/examples/visualization/bar.ipynb

**Comment by Longtailneighbor** [comment]
这个案例我点进去也看不到图

**Comment by Longtailneighbor** [comment]
刚试了下，可以，谢啦

**Comment by topsun888** [comment]
谢谢！

**Comment by topsun888** [comment]
另外，如果我想在html文件中显示图片，必须要使用pyexcel来对数据进行可视化吗?能不能直接用Bar, Pie命令？

**Comment by chfw** [comment]
不是，你理解错了。`online()`来自pyecharts.

http://pyecharts.org/#/zh-cn/jupyter_notebook?id=%e5%af%bc%e5%87%ba%e5%8a%9f%e8%83%bd
