### ISSUE TITLE
Timeline类js_dependencies项重复的bug

### ISSUE THREAD

**Issue by kinegratii** [chenjiandongx/pyecharts#296]
问题在 add 函数的构建

```
class Timeline(Base):
    def add(self, chart, time_point):
        self._js_dependencies = self._js_dependencies.union(
            chart.get_js_dependencies())
```

- 初始时 self._js_dependencies 只有一个元素 {'echarts'}
- 调用 get_js_dependencies 依次调用 `PyEchartsConfig.produce_html_script_list` ->  `PyEchartsConfig.get_js_library` -> `DEFAULT_JS_LIBRARIES.get(key, key)` 

问题在于， 在 `DEFAULT_JS_LIBRARIES` 中传入的 echarts 返回的是转化后 echarts.min ，在 union 操作中就会同时包含 echarts 和 echarts.min 两个元素。

建议仿造 Grid 类的 add 函数

```
class Grid(Base):
    def add(self, chart, **kwargs):
            self._js_dependencies = self._js_dependencies.union(chart.js_dependencies)
```

**Comment by chenjiandongx** [comment]
FIXED
