### ISSUE TITLE
Anaconda3安装pyecharts

### ISSUE THREAD

**Issue by AdvancedHOH** [chenjiandongx/pyecharts#298]
Anaconda3下无法自动安装pyecharts(会提示没有找到相关的包)
其环境中附带的jupyter notebook无法导入pyecharts
只有pip下安装的jupyter notebook才可以导入
在Anaconda3相关环境下使用pyecharts
必须手动配置
是否能够和Anaconda合作将pyecharts加入到其库中呢？
![fig](https://user-images.githubusercontent.com/29780144/33927233-6cb0aa02-e01c-11e7-8e4e-069571dbab29.jpg)

**Comment by chfw** [comment]
需要有人写CONDA RECIPE，然后自动PYECHARTS能进入CONDA。

这是别人写的样本https://github.com/conda-forge/staged-recipes/pull/4105
