### ISSUE TITLE
是否可以实现添加error bar？

### ISSUE THREAD

**Issue by ZaneMuir** [chenjiandongx/pyecharts#3]
是否可以在柱状图、折线图之类里实现添加Error Bar？
相比matplotlib这类的，pyecharts十分的简单易用，而且也比较美观；但如果不能添加Error Bar的话，还是没有办法用于科研工作中的制图。

###### PS: 如果能实现绘制p值的星号大概就更加完美了😂

**Comment by chenjiandongx** [comment]
目前 Echarts 官方好像没提供这个功能

**Comment by ZaneMuir** [comment]
好的吧，看来还是只能用来做一些简单的demo了😂
