### ISSUE TITLE
请问一下微博转发关系图中的json项所指的都是哪些参数呢？

### ISSUE THREAD

**Issue by Hudi233** [chenjiandongx/pyecharts#30]
你好，请问一下微博关系图中的nodes, links, categories, cont, mid, userl = j 这后三个参数指明什么呢？我阅读weibo.json看到三个数组[name 描述节点大小等]、[source 指明link]、[name 节点名字]，没有弄明白哪有6个参数，希望不吝赐教。

比如我自以为是的参考写了一个json，却得到这样的结果

Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    nodes, links, categories, cont, mid, userl = j
ValueError: not enough values to unpack (expected 6, got 3)

**Comment by chenjiandongx** [comment]
参考 [weibo,json](https://github.com/chenjiandongx/pyecharts/blob/master/json/weibo.json)

**Comment by Hudi233** [comment]
好的，我参考了这个，可是json里我只发现了三个数组啊，[name 描述节点大小等]、[source 指明link]、[name 节点名字]

**Comment by chenjiandongx** [comment]
nodes, links, categories, cont, mid, userl = j 自己写的话，后面三个参数可以不用
保留 nodes,links,categories 即可

**Comment by Hudi233** [comment]
好的，我试试，多谢赐教。
