### ISSUE TITLE
jupyter下载为html的时候没有显图表

### ISSUE THREAD

**Issue by bang411** [chenjiandongx/pyecharts#305]
新版本0.3.1的问题,我在notebook 上面画完图后,download as html下载下来后,那个html文件没渲染出来.
虽然我通过改html里的下部分代码,把原来的
```
<script>
    require.config({
         paths:{
           'echarts': '/nbextensions/echarts/echarts.min'
         }
    });
</script>
```
全部改成下面这个链接后,那个html文件可以正常出图了
```
<script>
    require.config({
         paths:{
           'echarts': 'https://cdnjs.cloudflare.com/ajax/libs/echarts/3.8.5/echarts.min'
         }
    });
</script>
```
但是好像不是长久之计吧,这里主要是什么问题呢?

**Comment by chfw** [comment]
from pyecharts import online

online() # or online(host='your_own_host_that_has_jupyter_echarts')

**Comment by bang411** [comment]
@chfw is this  online()  fuction will been aborted? does configue() work?

**Comment by bang411** [comment]
@chfw it doesn't work neither online() or configue()

**Comment by chfw** [comment]
online()用的是github 链接

例子：
https://nbviewer.jupyter.org/github/pyexcel/pyexcel/blob/v0.6.0/examples/visualization/bar.ipynb
