### ISSUE TITLE
macOS上python3编译未通过

### ISSUE THREAD

**Issue by wbdu** [chenjiandongx/pyecharts#34]
Collecting pyecharts
  Downloading pyecharts-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f4/t5xbjjj97gj_wwrcpcvd7c3h0000gn/T/pip-build-mke1433t/pyecharts/setup.py", line 8, in <module>
        import pyecharts.__version__ as about
      File "/private/var/folders/f4/t5xbjjj97gj_wwrcpcvd7c3h0000gn/T/pip-build-mke1433t/pyecharts/pyecharts/__init__.py", line 4, in <module>
        from pyecharts.charts.bar import Bar
      File "/private/var/folders/f4/t5xbjjj97gj_wwrcpcvd7c3h0000gn/T/pip-build-mke1433t/pyecharts/pyecharts/charts/bar.py", line 4, in <module>
        from pyecharts.base import Base
      File "/private/var/folders/f4/t5xbjjj97gj_wwrcpcvd7c3h0000gn/T/pip-build-mke1433t/pyecharts/pyecharts/base.py", line 9, in <module>
        from jinja2 import Template
    ModuleNotFoundError: No module named 'jinja2'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f4/t5xbjjj97gj_wwrcpcvd7c3h0000gn/T/pip-build-mke1433t/pyecharts/

**Comment by chenjiandongx** [comment]
没在 Mac 机下测试过，因为用不起 Mac，真是一个悲伤的故事，看看有没有使用了 Mac 能用的吧

**Comment by Lorryrui** [comment]
我这边mac确实也用不了。我去windows上吧

**Comment by MiracleXYZ** [comment]
看起来像是没有安装jinja2模块

**Comment by chenjiandongx** [comment]
那就 pip install jinja2 试试看吧

**Comment by chfw** [comment]
@wbdu , Could you please try the tar ball in the PR #36 ? 

    pip install pyecharts-0.1.8.tar.gz

**Comment by chenjiandongx** [comment]
@wbdu 
你试试在你的 Mac 上安装一下 @chfw 提供的 tar 包，看能否正常安装及使用。

**Comment by wbdu** [comment]
有高人啊， 安装完jinja2之后，安装通过。

**Comment by chenjiandongx** [comment]
@wbdu 
你能否将 jinja2 和 pyecharts 先给卸载了，然后再重新安装 @chfw 提供的 tar 包试试看是否是错。就当是帮我测试一下，因为如果能解决问题的话我在下一个版本会改进这个问题。

**Comment by wbdu** [comment]
@chenjiandongx 好的，马上搞

**Comment by wbdu** [comment]
Processing ./pyecharts-0.1.8.tar.gz
Requirement already satisfied: pprint in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pyecharts==0.1.8)
Requirement already satisfied: Image in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pyecharts==0.1.8)
Collecting jinja2 (from pyecharts==0.1.8)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Requirement already satisfied: django in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Image->pyecharts==0.1.8)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Image->pyecharts==0.1.8)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jinja2->pyecharts==0.1.8)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from django->Image->pyecharts==0.1.8)
Requirement already satisfied: olefile in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pillow->Image->pyecharts==0.1.8)
Building wheels for collected packages: pyecharts
  Running setup.py bdist_wheel for pyecharts ... done
  Stored in directory: /Users/stevendu/Library/Caches/pip/wheels/f1/ad/05/c06dd23d713dc278642a94edd37fb6eacd0d8065d5b875e152
Successfully built pyecharts
Installing collected packages: jinja2, pyecharts
Successfully installed jinja2-2.9.6 pyecharts-0.1.8

**Comment by chenjiandongx** [comment]
嗯 谢谢你提供的反馈

**Comment by VincentCalc** [comment]
MoudeMacBook-Pro:~ mou$ pip3 install pyecharts
Collecting pyecharts
  Using cached https://files.pythonhosted.org/packages/1c/a8/45e5f87ee326fbb48d36650ebb705691e4383529be0ab3281a8a8bffca09/pyecharts-0.5.5-py2.py3-none-any.whl
Requirement already satisfied: jupyter-echarts-pypkg==0.1.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyecharts) (0.1.1)
Requirement already satisfied: future in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyecharts) (0.16.0)
Requirement already satisfied: lml==0.0.2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyecharts) (0.0.2)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyecharts) (5.1.0)
Collecting pyecharts-javascripthon==0.0.6 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/6f/68/23644a394341fef4cbcb48a3fa4b2816408a13a1fa3281cf9030b2ac2d67/pyecharts_javascripthon-0.0.6-py2.py3-none-any.whl
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyecharts) (2.10)
Requirement already satisfied: pyecharts-jupyter-installer==0.0.3 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from jupyter-echarts-pypkg==0.1.1->pyecharts) (0.0.3)
Collecting javascripthon>=0.10; python_version > "3.4" (from pyecharts-javascripthon==0.0.6->pyecharts)
  Using cached https://files.pythonhosted.org/packages/ea/ef/b46401e181768b3738660f5dc1f7ea0b334ed17fff685a61503d2989e77e/javascripthon-0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9y/rt0339ms3f7_rpk443l208tr0000gn/T/pip-install-4u7dub0h/javascripthon/setup.py", line 73, in <module>
        'metapensiero.pj': ['data/*.js']
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 504, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 571, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9y/rt0339ms3f7_rpk443l208tr0000gn/T/pip-install-4u7dub0h/javascripthon/

可以请教一下我这个是什么问题吗？找了一大圈没找到解决方法

**Comment by chfw** [comment]
Please upgrade your openssl library on your Mac. 

reference:

https://github.com/pypa/pip/issues/829#issuecomment-20931050

**Comment by xxyyffyeah** [comment]
装好了那个tar.gz,jinja2，都不行啊，还是老问题
![2019-01-06 17 40 07](https://user-images.githubusercontent.com/33823764/50734440-2c94c200-11da-11e9-9e0a-e387e2f47299.png)

**Comment by chfw** [comment]
`pip freeze` show me the list
