### ISSUE TITLE
ImportError: cannot import name 'Bar'

### ISSUE THREAD

**Issue by brucerow** [chenjiandongx/pyecharts#35]
windows7+python3.5

pip install Image失败，提示”The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.“，改用pip install pillow后，pyecharts安装成功，但运行示例的时候：ImportError: cannot import name 'Bar'

**Comment by chenjiandongx** [comment]
试试 pip uninstall pyecharts 再 pip install pyecharts==0.1.8 吧

**Comment by brucerow** [comment]
是我本地环境问题，现在已经可以用了，多谢多谢

**Comment by lostliujunli** [comment]
bruce 兄弟是怎么解决的本地环境的问题的呢，我也遇到了类似的问题
