### ISSUE TITLE
包安装失败怎么解决？

### ISSUE THREAD

**Issue by haozhou0327** [chenjiandongx/pyecharts#38]
使用命令
pip install pyecharts
安装时出现以下错误：
Command "python setup.py egg_info" failed with error code 1 in c:\users\eship\appdata\local\temp\pip-build-dndqiu\pyecharts\

请问怎么解决呀？

**Comment by chenjiandongx** [comment]
python2 or python3?

**Comment by haozhou0327** [comment]
您好，使用的python2，刚刚直接从github下载了包，通过python setup.py install方式安装成功了。

谢谢您。

**Comment by chenjiandongx** [comment]
好的 使用愉快
