### ISSUE TITLE
map结合 visualMap是否支持地图下钻及页面筛选器

### ISSUE THREAD

**Issue by linfanli** [chenjiandongx/pyecharts#39]
你好，在实际场景中有如下应用

1. 地图的下钻：例如在已经给出的两个示例，a.全国地图， b.广东省地图，是否支持在全国地图中点击广东，下钻到广东地国（现阶段只有鼠标悬浮出有标符信息）
2. 地图页面筛选器：实现不同业务数据的可视化展示。
3. 支持图面汉化： 中国特色使用我大中华汉字

<img width="932" alt="2017-07-29 9 48 52" src="https://user-images.githubusercontent.com/16367420/28745466-bba8f934-74ab-11e7-82ca-6f8049eb79a4.png">

<img width="937" alt="2017-07-29 9 49 03" src="https://user-images.githubusercontent.com/16367420/28745412-aa792310-74aa-11e7-8aaa-1c2cb9059183.png">

**Comment by chenjiandongx** [comment]
你好，
1 和 2 目前版本暂时没实现该功能 我可以来看看有没有办法加入该功能
3 的话是提供修改参数的，visual_range_text 参数是可以修改的 比如 [‘大’,‘小’]

**Comment by linfanli** [comment]
楼主给力啊，
地图下钻和页面筛选器开发好了，麻烦告诉我下email：pvli508@126.com

另外有个请教下，gif你是用什么工具做的，我上网找没有找到合适的

**Comment by chenjiandongx** [comment]
你持续关注项目就行，gif 使用的是 ShareX

**Comment by linfanli** [comment]
ShareX 不支持mac os
必须长期关注，另外还有个新需求
地图搭配置时间轴，baidu echarts实例 [全国宏观经济指标](http://echarts.baidu.com/echarts2/doc/example/map14.html)
<img width="771" alt="2017-07-29 11 15 33" src="https://user-images.githubusercontent.com/16367420/28745851-c37393f6-74b3-11e7-98b1-0ed4591ddd3c.png">

**Comment by chenjiandongx** [comment]
我尽力...，手头工作要完成先。

**Comment by chfw** [comment]
@linfanli , you can use quicktime + ffmpeg + gifscile. 

More details here: https://gist.github.com/dergachev/4627207

**Comment by linfanli** [comment]
@chfw thx
I have installed "GIF Brewery 3"

**Comment by linfanli** [comment]
??
@chenjiandongx 已经支持地图下钻了吗

**Comment by chenjiandongx** [comment]
@linfanli 
地图下钻没有办法实现 issue 开了也没用 所以我就关了

**Comment by chfw** [comment]
@linfanli I started using GIF Brewery 3
