### ISSUE TITLE
是否可以实现与Django集成？

### ISSUE THREAD

**Issue by wuming123057** [chenjiandongx/pyecharts#4]
是否可以实现与Django集成？

**Comment by wuming123057** [comment]
可以参考Bokeh类库，以及示例http://www.jianshu.com/p/8b4f17950777

**Comment by sailf** [comment]
+1 需要这个功能

**Comment by chenjiandongx** [comment]
我先把 Django 熟悉一下先 看看具体要怎么实现哈 可以的话后期会加集成到 Django 的
