### ISSUE TITLE
问题求助：图片无法显示

### ISSUE THREAD

**Issue by yxhucc2015** [chenjiandongx/pyecharts#40]
将kline图与line图用custom（）放在一张表中，再用grid（）另一张bar图联系，没有报错，但是显示不出图表。 请问该如何解决？
 同问， 是否有办法实现bar/line/kline 双x轴？ 类似于matplotlib 里的 subplot（） + twinx（）。

**Comment by chenjiandongx** [comment]
这个项目只是设置配置项 只要配置项数据类型不错误 它一般都不会报错的 我没有办法检测是否能正常显示图片的 把代码贴上来我看一下吧

**Comment by yxhucc2015** [comment]
`kline = Kline("ten_year",is_grid = True)
kline.add('日K', x,y,is_datazoom_show = True, datazoom_type = 'inside', datazoom_range = [10,25],grid_bottom = '60%')  

line_5D = Line()
line_5D.add('五日均线',x_5RA,y_5RA)
kline.custom(line_5D.get_series())

line_10D = Line()
line_10D.add('十日均线',x_10RA,y_10RA)
kline.custom(line_10D.get_series())

bar = Bar('')
bar.add('vol',x,vol,is_legend_show = False) 
kline.grid(bar.get_series(),grid_top = '60%')

kline.show_config()

kline.render()`

**Comment by chenjiandongx** [comment]
是 目前这样用会导致坐标轴索引出现问题 看看后续版本能不能改进吧

**Comment by yxhucc2015** [comment]
好的 谢谢

**Comment by chenjiandongx** [comment]
@yxhucc2015 
请尝试使用 Page() 类，详情见文档
