### ISSUE TITLE
问题：坐标轴能否增加线性/对数的选择？

### ISSUE THREAD

**Issue by laputa-ghost** [chenjiandongx/pyecharts#41]
对于部分数据较大的情况下，可能需要用到对数坐标，不知道能否实现？

**Comment by chenjiandongx** [comment]
你把数据进行对数处理再画上去试试看

**Comment by laputa-ghost** [comment]
找到一个解决方案，通过更改生成的HTML的yAxis或者option中xy_axis函数参数，令type='log'。
不知道能否有更简单的方法，建议直接增加选项控制。

**Comment by chenjiandongx** [comment]
嗯 你能否贴上使用效果图

**Comment by chenjiandongx** [comment]
@laputa-ghost 
版本已更新为 0.1.9.3，新增了 xaxis_type 和 yaxis_type 参数，详情参考 [changelog.md](https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md)

**Comment by enjoyhot** [comment]
你好，请问当前最新版本的Line应该怎么设置xaxis_type呢？通过以下方法添加，发现出现是空白？
谢谢。
`
attr = [10, 20, 90, 91,92,93]
v1 = [5, 20, 36, 10, 10, 100]
v2 = [55, 60, 16, 20, 15, 80]
line = Line("10 seconds batch duration")
line.add("商家A", attr, v1, mark_point=["average"],is_smooth=True, xaxis_type='value')
line
`
