### ISSUE TITLE
map地图visualMap 组件的最大值，能否自定义

### ISSUE THREAD

**Issue by linfanli** [chenjiandongx/pyecharts#42]
map地图visualMap 组件（地图左下解）最大值为100
<img width="702" alt="2017-07-30 11 19 29" src="https://user-images.githubusercontent.com/16367420/28755019-713b7348-7584-11e7-9115-f702ff145b63.png">

当value值较大时，地图不正常以不同的色块代表的不现的value值。地图的value由于>100,地图统一显示为红色
<img width="705" alt="2017-07-30 11 25 03" src="https://user-images.githubusercontent.com/16367420/28755039-b07bae1a-7584-11e7-9243-b6ea3eccd8fd.png">

![gk_map](https://user-images.githubusercontent.com/16367420/28755041-b66dcb78-7584-11e7-8e44-be99243c9184.gif)

**Comment by chenjiandongx** [comment]
visual_range -> list
指定组件的允许的最小值与最大值。默认为 [0, 100]

**Comment by linfanli** [comment]
多谢谢楼主，及时
