### ISSUE TITLE
多图的交互

### ISSUE THREAD

**Issue by yumengzou** [chenjiandongx/pyecharts#44]
刚从matplotlib的坑里转过来，很喜欢pyecharts自带的交互。仔细看了文档，发现用户不能自定义多图之间的交互。想问问有没有要往这个方向开发的打算？

**Comment by chenjiandongx** [comment]
待定 后期再看看吧

**Comment by chenjiandongx** [comment]
@yumengzou 
add() 第一个 name 参数相同的话 多图之间是会互动的 你可以尝试一下

**Comment by yumengzou** [comment]
![clustering place by type](https://user-images.githubusercontent.com/29134324/29201213-e4132ace-7e8e-11e7-8577-d78c3ac63dc1.png)

我就是用的一樣的name參數。
我的scatter是scatter.add('Cluster '+str(i),data,grid_right="65%",legend_top="10%",legend_pos="0%")
我的radar是radar.add('Cluster '+str(i), data, item_color=c[i],is_area_show=True,area_color=c[i],area_opacity=0.5,legend_pos='50%',legend_top="10%")
最後合併用的是scatter.grid(radar.get_series(),grid_left="55%")
然而效果是如圖的。

**Comment by yumengzou** [comment]
我想了一下可能原因是grid3D和xyAxis不能交互

**Comment by chenjiandongx** [comment]
3D 图使用 xAxis 和 yAxIs 的设置是无效的

**Comment by chenjiandongx** [comment]
@yumengzou 
3D 图已提供 x y z 轴设置选项，请参考文档中的 **通用配置项**

**Comment by yumengzou** [comment]
我在upgrade时出现了几个问题
1. ShimWarning: The 'IPython.html' package has been deprecated since IPython 4.0. You should import from 'notebook' instead. 'IPython.html.widgets' has moved to 'ipywidgets'. 兼容问题，不过只是warning，没有error
2. from IPython.html.nbextensions import install_nbextension
ModuleNotFoundError: No module named 'IPython.html.nbextensions'

**Comment by chfw** [comment]
Which version of IPython please?

**Comment by chfw** [comment]
After you have upgraded IPython, I think you will need to Jupyter-notebook too.

**Comment by chenjiandongx** [comment]
@yumengzou 
安装 notebook 可以解决问题 `pip install notebook`

然后再次安装 pyecharts ` pip install pyecharts`

**Comment by chfw** [comment]
http://ipython.org/news.html#ipython-4-0

`For 4.0, we will split up components into several packages. The parts which work for any language will be called Jupyter, while the parts specific to executing Python code will remain as IPython.`

**Comment by yumengzou** [comment]
@chenjiandongx @chfw Thank both of you! I've successfully upgraded pyecharts and will test with the xyzAxis on 3DGrid now.
