### ISSUE TITLE
radar图可以开放更多的模式么？

### ISSUE THREAD

**Issue by Kimice** [chenjiandongx/pyecharts#46]
现在的radar图默认selectedMode为single, 不同数据源只能分开展示。
[这种图](http://echarts.baidu.com/demo.html#radar) 暂时无法很好的支持，只能强行定制。

我现在是这样改的，希望未来的支持更全面更兼容，或者可以提供更开放的定制接口
```
radar._option.get('legend')[0]['data'] = [aaa, bbb...]  # data name related with series data name
radar._option.get('legend')[0]['selectedMode'] = True
```

**Comment by chenjiandongx** [comment]
@Kimice 
你好 已接受你的建议 下个版本的话会提供 legend_selectedmode 参数，默认为 'multiple'，需要选择 single 的话可以使用 lenged_selectedmode='single'

**Comment by chenjiandongx** [comment]
@Kimice 
版本已更新，该参数已加入，请使用最新版本。pip install pyecharts==0.1.1.9

**Comment by Kimice** [comment]
@赞！pip install pyecharts==0.1.9.1哦
