### ISSUE TITLE
怎样在Jupyter Notebook中显示图表？

### ISSUE THREAD

**Issue by uuleejie** [chenjiandongx/pyecharts#5]
你好，将有关代码粘贴到notebook中后运行，没有报错，也没有显示图表。请问应该怎样做才能显示图表？

**Comment by uuleejie** [comment]
看看文档后知道了，不用回复，谢谢！

**Comment by Chandlerwu007** [comment]
文档中没有看见呀

**Comment by chenjiandongx** [comment]
@Chandlerwu007 用浏览器打开生成 .html 文件 默认为 render.html

**Comment by Chandlerwu007** [comment]
恩。。打开了。试了下，好像不能指定存放路径。

**Comment by Chandlerwu007** [comment]
对浏览器有什么要求么？在家里电脑能正常显示，但在单位上的显示为空白。

**Comment by Lving** [comment]
其实 jupyter 是支持js的

**Comment by ygw365** [comment]
in /pyecharts-master/pyecharts/base.py
```
    def render2(self):
        import datetime
        divid = datetime.datetime.now()
        my_option = json.dumps(self._option, indent=4)
        s = '''
        <div id="{{ chartid }}" style="width:800px; height:600px;"></div>
<script>
    require.config({
         paths:{
            echarts: '//cdn.bootcss.com/echarts/3.2.3/echarts.min',
         }
    });
    require(['echarts'],function(ec){
    var myChart = ec.init(document.getElementById('{{ chartid }}'));
               var option =  {{ opt }};
                myChart.setOption(option);
    });
</script>
'''
        tmp = Template(s)
        return tmp.render(opt=my_option.decode('utf8'),chartid=divid)
```

in notebook:

```
from pyecharts import Bar

bar = Bar("标记线和标记点示例")
bar.add("商家A", attr, v1, mark_point=["average"])
bar.add("商家B", attr, v2, mark_line=["min", "max"])
HTML(bar.render2())
```
![snip20170724_3](https://user-images.githubusercontent.com/3285067/28515885-ce9aa54c-7091-11e7-89c9-2b6ea834bc7d.png)

**Comment by chenjiandongx** [comment]
@ygw365 谢谢你的提醒，能否提供整个的完整代码。

**Comment by chenjiandongx** [comment]
@ygw365 
谢谢你的贡献 能否提供整个完整的代码

**Comment by ygw365** [comment]
@chenjiandongx chen，已经提了PR，你看下

**Comment by foodish** [comment]
@ygw365 添加了您的代码，不过有错误。没有Template函数。。。

**Comment by chenjiandongx** [comment]
Guys, now you can show your charts in jupyter notebook.It will be a cool features.enjoy it!

**Comment by foodish** [comment]
升级后可以完美显示了，感谢 @chenjiandongx

**Comment by ygw365** [comment]
@foodish , pip install jinja2

**Comment by foodish** [comment]
@ygw365 最新版已经好了。感谢！

**Comment by xbanke** [comment]
@chenjiandongx 已经更新了，在notebook中可以正常显示，但如果 下载为html的话，可能因为改变了跟路径，无法加载相应js文件，进而无法显示echarts图。

**Comment by chenjiandongx** [comment]
@xbanke 
使用 render() 方法仍然会在本地保存一个 .html 文件，render_notebook() 只是专门为 notebook 提供的新方法而已

**Comment by xbanke** [comment]
@chenjiandongx 我明白你的意思，用render只能保存那张图。notebook其中一个很重要的场景就是可以导出各类格式的文件进行分享，只是在生成html时，echarts的图有问题，当然这可能要改notebook的配置，而不是pyecharts

**Comment by chenjiandongx** [comment]
@xbanke 
就是因为正常的 html echart 文件在 notebook 中不能正常显示，才花了那么多时间来测试能确保 notebook 所有图形正常显示的 Js 代码

**Comment by yi1260** [comment]
jupyter的远程模式还是显示不了@chenjiandongx 已经是最新版本了,  是只能在本地模式下才行吗

**Comment by chensonglovelife** [comment]
1.8 version still have this bug.python2.7 + v1.8 + chrome of Mac

**Comment by chenjiandongx** [comment]
@chensonglovelife I do not test in Mac

**Comment by chenjiandongx** [comment]
@yi1260 
我没这么测试过 现在还是不可以吗

**Comment by lionshaw** [comment]
@yi1260 远程模式要加载相应的资源，bokeh 里有类似的解决方法
```python
from bokeh.io import output_notebook
output_notebook()
```
可以参考其实现 [notebook](https://github.com/bokeh/bokeh/blob/master/bokeh/util/notebook.py)

**Comment by chfw** [comment]
@chenjiandongx , could you please share you jupyter notebook on github? I can try my best to include a unit test for those notebooks. Tavis-ci will then verify your notebook per each commit, functionally. With that said, visual check is still required. However, with 700+ stars, there are plenty of eyes for that check :).

> 
> @xbanke
> 就是因为正常的 html echart 文件在 notebook 中不能正常显示，才花了那么多时间来测试能确保 notebook 所有图形正常显示的 Js 代码

**Comment by wqw547243068** [comment]
![image](https://user-images.githubusercontent.com/3257257/41155512-e78cd39e-6b50-11e8-899d-bc7fbe938832.png)

**Comment by chfw** [comment]
if your jupyter host is not localhost:8888, you will have a problem. And we do not support other jupyter domain as of now. One solution is to do the following before your code:

```
from pyecharts import online

online()
```
