### ISSUE TITLE
能否加上bar的x轴标签旋转功能？

### ISSUE THREAD

**Issue by fuyangzhen** [chenjiandongx/pyecharts#52]
默认的貌似是间隔显示label,如果想都显示出来的话，可以加上角度旋转吗？

**Comment by chenjiandongx** [comment]
在 add() 中加上  interval=0，试试看

**Comment by fuyangzhen** [comment]
interval=0对于长label太密集了，堆积在一起就看不清了

**Comment by chenjiandongx** [comment]
下个版本会新增 xaxis_rotate 和 yaxis_rotate 参数可供设置，敬请关注。

**Comment by chenjiandongx** [comment]
@fuyangzhen 
已更新至 0.1.9.2 版本，请查看 [changelog](https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md)
