### ISSUE TITLE
如何实现数据的异步加载

### ISSUE THREAD

**Issue by August-Ghost** [chenjiandongx/pyecharts#59]
一个月分钟级的K线数据， 画出来缩放的时候就已经卡得不要不要的了，有没有可能实现数据的异步加载呢？

**Comment by chenjiandongx** [comment]
这个目前只是提供echarts 的Python 接口 具体内部逻辑不由这个项目处理

**Comment by chenjiandongx** [comment]
下个版本会改进html模板 绘图速度应该有所提升

**Comment by August-Ghost** [comment]
好的，了解了解
