### ISSUE TITLE
怎么没有台北的数据？

### ISSUE THREAD

**Issue by xiaomintongxue** [chenjiandongx/pyecharts#6]
我试了下全国省会的数据显示，但是好像台北的没有显示。可以再继续完善啊

**Comment by chenjiandongx** [comment]
Echarts 本身没有提供台北的地图 只有台湾省而已

**Comment by xiaomintongxue** [comment]
@chenjiandongx 我是基于例子输入台北市天气温度，然后没法显示调用geo，具体省会地图我还没试

**Comment by chenjiandongx** [comment]
@xiaomintongxue 
现已支持自定义地图，请查看关于文档关于 Map 的部分。
