### ISSUE TITLE
3D多图显示问题

### ISSUE THREAD

**Issue by cavities** [chenjiandongx/pyecharts#61]
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from pyecharts import Scatter3D
v = pd.read_csv("Guerry.csv")

''' data from rdataset  http://vincentarelbundock.github.io/Rdatasets/datasets.html HistData Guerry'''

results = smf.ols('Lottery ~ Literacy + np.log(Pop1831)', data=v).fit()


def lineplot_zip(z_xy,param):
    v = z_xy[:,0]*param[1]+z_xy[:,1]*param[2] +param[0]
    return v

v1 = v.sort_values('Lottery')


f_xy_zip = [[x,y] for x in np.linspace(0,100,num=100) for y in np.linspace(0,10,num=100)]

z = lineplot_zip(np.array(f_xy_zip),results.params.tolist())


ret = [[t[0][0],t[0][1],t[1]] for t in zip(f_xy_zip,z)]
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
range_color1 = sorted(['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026'])

ret_s =[[s[0],s[1],s[2]]  for s in zip(v1['Literacy'].tolist(),np.log(v['Pop1831']).tolist(),v1['Lottery'].tolist())]


Sc = Scatter3D('guerry test',width=1200, height=600)
Sc.add("s",ret, is_visualmap=True, grid3D_opacity=2,visual_range_color=range_color,center = [25,50])
Sc.add("t",ret_s, is_visualmap=True,grid3D_opacity=2,visual_range_color=range_color,center = [75,50])
Sc.render("ttt.html")

```
1没办法在jupyter_notebook上显示3D散点图 
二是没有办法  在一个html总绘制 多个散点图

**Comment by chenjiandongx** [comment]
Jupiyter notebook 无法显示3D图 这个在文档中已经说明 第二个没看明白 能表达得清楚一点吗

**Comment by chfw** [comment]
@chenjiandongx @cavities , I managed to fix scatter3D in notebook display

<img width="731" alt="screen shot 2017-08-03 at 09 00 32" src="https://user-images.githubusercontent.com/4280312/28912003-494a0838-782a-11e7-92bc-61032174ba3e.png">

Will submit a PR soon.

**Comment by cavities** [comment]
就是在一个html中绘制 多个3d散点图

**Comment by cavities** [comment]
@chenjiandongx 其实就是想要 render到html 文件时候可以在一个html中存储多个 多维散点图
add("s",ret, grid3D_opacity=2,visual_range_color=range_color,center = [25,50])
add("s",ret1, grid3D_opacity=2,visual_range_color=range_color,center = [75,50])
类似的方法 没有效果

**Comment by chfw** [comment]
You can try my version of pyecharts before my PR is to be merged. Even mine will be merged, your verification is required to pass it to release anyway. So by doing it now, we save some time :)

[pyecharts-0.1.9.1.tar.gz](https://github.com/chenjiandongx/pyecharts/files/1198515/pyecharts-0.1.9.1.tar.gz)
