### ISSUE TITLE
py2.7下编码问题render方法报错

### ISSUE THREAD

**Issue by lx9921** [chenjiandongx/pyecharts#62]
bar = Bar("图表")
bar.pdcast(user_grouped['sum_bet'])
bar.add("销量",bar.pdcast(user_grouped['sum_bet'])[1],bar.pdcast(user_grouped['sum_bet'])[0])
bar.render()
直接调用render方法报错UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 19: ordinal not in range(128)
而调用render_notebook()则能够在notebook中正常显示。
其中x轴为中文，但是也都声明了utf-8编码，不知道问题出在哪里了。中文编码真是头疼的问题啊。。。
网上查了下可能是因为json.dump会默认把中文当做ascii来处理造成的？
求高人指教
![default](https://user-images.githubusercontent.com/8848292/28910799-dcc78ed8-7860-11e7-97d6-a20778602827.JPG)

**Comment by chenjiandongx** [comment]
请仔细阅读文档中关于Python2编码问题的部分 引入future 模块

**Comment by lx9921** [comment]
![default](https://user-images.githubusercontent.com/8848292/28911670-ddfa27cc-7863-11e7-9e1a-fa31d30f9897.JPG)
之前就引入过了future模块了，还是出现了这个问题。。

**Comment by chfw** [comment]
Which version of notebook are you having? As far as I know, jupiter-nook requires at least Python 3.

And in your case, you can try to put a 'u' in front of your Chinese text and try again. 

`from __future__ import unicode_literals` needs to be put in the very first place before any other code to function well.

**Comment by lx9921** [comment]
谢谢各位指导，jupiter-notebook是anaconda2自带的。。。而且ide换成pycharm也会出现同样问题。
用chardet查看了下也是utf-8编码啊。。有些迷惑了
![default](https://user-images.githubusercontent.com/8848292/28913034-299303ca-7869-11e7-9b0f-16777aba581b.JPG)

**Comment by lx9921** [comment]
问题已解决，还是json.dumps里的参数出现了问题，修改源码将base.py中render方法json.dumps(self._option, indent=4,ensure_ascii=False)中的ensure_ascii参数删除后即可解决问题。谢谢各位帮助

**Comment by chfw** [comment]
Could you please upload a sample of your text file here for us to reproduce your problem?

**Comment by wy7980** [comment]
遇到这个问题好像是在linux下有

**Comment by chfw** [comment]
哪个版本呢?可以给个可以重复的例子么?有的放矢才好解决。

**Comment by wy7980** [comment]
ubuntu16.04 apt-get安装，版本：
```
>>> print pyecharts.__version__
0.1.9.1
```
源码：
```
from pyecharts import Bar

g1=[0.3,0.2,0.1 ]
g2=[0.3,0.2,0.1 ]

def getcharts(uz,uz2):
	attr = ['1','2','4']
	#create chart
	bar2 = Bar(title="对比图",width=1600,height=800)
	bar2.add("zlib8",attr,uz,mark_point=["average"],mark_line=["max"])
	bar2.add("zlib11",attr,uz2,xaxis_name="文件",xaxis_name_pos="middle",yaxis_name = "时间",yaxis_name_pos="start",yaxis_formatter="ms",mark_point=["average"],mark_line=["max"])
	bar2.render()

if __name__ == "__main__":
	getcharts(g1,g2)

```
错误信息：
```
Traceback (most recent call last):
  File "xx.py", line 20, in <module>
    getcharts(g1,g2)
  File "xx.py", line 17, in getcharts
    bar2.render()
  File "/home/xx/.local/lib/python2.7/site-packages/pyecharts/base.py", line 417, in render
    my_option = json.dumps(self._option, indent=4, ensure_ascii=False)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
```
根据 @lx9921 的方法可以解决

**Comment by chfw** [comment]
@wy7980 , 我在fedora26英文环境下，用python 2.7.13试过了你的示例，没有问题。

不过，你的示例的开头缺了这两行：

    #coding=utf-8
    from __future__ import unicode_literals

换句话说，就是"对比图" ，"文件"没有被当成UNICODE。

**Comment by chfw** [comment]
你的示例缺少了这么两句重要的语句：

    #coding=utf-8
    from __future__ import unicode_literals

文档有[提到](https://github.com/chenjiandongx/pyecharts/blob/master/document/doc_zh_CN.md#python2-编码问题)

**Comment by chfw** [comment]
让我收回我的话，python2 有jupyter-notebook

不过，解决方式不变。这是我遇到的问题：
<img width="915" alt="screen shot 2017-08-30 at 22 28 06" src="https://user-images.githubusercontent.com/4280312/29896004-2f89b11e-8dd3-11e7-8ae3-56d4620bdfe0.png">
下面是我的解决方式：

`from __future__ import unicode_literals`

<img width="911" alt="screen shot 2017-08-30 at 22 30 37" src="https://user-images.githubusercontent.com/4280312/29896018-41fb2be8-8dd3-11e7-8747-120ddc939112.png">
