### ISSUE TITLE
添加离线模式 

### ISSUE THREAD

**Issue by emailhy** [chenjiandongx/pyecharts#67]
支持离线运行，打包echarts 和其他js

**Comment by chfw** [comment]
Master branch 已支持离线模式，详情看#51。

你可以克隆这个项目然后装上，你将是第一用离线模式的用户。你可以和现有的对。离线模式超好快哦。

**Comment by chenjiandongx** [comment]
@emailhy 
已更新至 0.1.9.2 版本，请查看 [changelog](https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md)
