### ISSUE TITLE
关于条形图排序功能

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#68]
你好，是不是没有排序的功能，没有找到。

**Comment by dengyingguo** [comment]
`# -*- coding: utf-8 -*-
# Time    : 2017/8/2 20:56
# Author  : XiaoDeng
# version : python3.6.1
# Software: PyCharm Community Edition

from pyecharts import Bar

bar = Bar("x 轴和 y 轴交换")

v2 = [10, 25, 8, 60, 20, 80]
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]

# sort
zip_data = zip(attr, v2)
dict = dict(zip_data)
print(dict)  # {'衬衫': 10, '羊毛衫': 25, '雪纺衫': 8, '裤子': 60, '高跟鞋': 20, '袜子': 80}

data = sorted(dict.items(), key=lambda d: d[1], reverse=True)
print(data)

attr = []
v2 = []

for line in data:
    k1 = line[0]
    k2 = line[1]
    attr.append(k1)
    v2.append(k2)

bar.add("商家B", attr, v2, is_convert=True, mark_line=['average'])

bar.render('bar10.html')`

通过先对数据进行排序，倒是实现了

**Comment by dengyingguo** [comment]
# -*- coding: utf-8 -*-
# Time    : 2017/8/2 20:56
# Author  : XiaoDeng
# version : python3.6.1
# Software: PyCharm Community Edition

from pyecharts import Bar

bar = Bar("x 轴和 y 轴交换")

v2 = [10, 25, 8, 60, 20, 80]
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]

# sort
zip_data = zip(attr, v2)
dict = dict(zip_data)
print(dict)  # {'衬衫': 10, '羊毛衫': 25, '雪纺衫': 8, '裤子': 60, '高跟鞋': 20, '袜子': 80}

data = sorted(dict.items(), key=lambda d: d[1], reverse=True)
print(data)

attr = []
v2 = []

for line in data:
    k1 = line[0]
    k2 = line[1]
    attr.append(k1)
    v2.append(k2)

bar.add("商家B", attr, v2, is_convert=True, mark_line=['average'])

bar.render('bar10.html')

通过对数据首先排序的方式，倒是实现了

**Comment by chenjiandongx** [comment]
排序这个没有提供，用户可自定对数据进行操作后再传入 add() 方法

**Comment by wangxiaolei0721** [comment]
You provided a feasible method. Thanks.
