### ISSUE TITLE
地图除了广东还支持哪些省份呢？

### ISSUE THREAD

**Issue by Chandlerwu007** [chenjiandongx/pyecharts#7]

**Comment by chenjiandongx** [comment]
china、world、安徽、澳门、北京、重庆、福建、福建、甘肃、广东，广西、广州、海南、河北、黑龙江、河南、湖北、湖南、江苏、江西、吉林、辽宁、内蒙古、宁夏、青海、山东、上海、陕西、四川、台湾、天津、香港、新疆、西藏、云南、浙江 。文档里有注明

**Comment by Chandlerwu007** [comment]
恩。找到了。但是怎么查看每个省份具体支持的城市列表呢？

**Comment by chenjiandongx** [comment]
怎么说呢 这没具体详细提供了 试试吧 显示不出来就是没有了

**Comment by Chandlerwu007** [comment]
恩。比如我输入北京，我希望获得各个区的名字列表。。。但好像只能靠自己猜

**Comment by chenjiandongx** [comment]
基本上应该是都有的 得到名字列表这个暂时还没有这种操作哈

**Comment by Chandlerwu007** [comment]
谢谢

**Comment by suuuch** [comment]
@chenjiandongx 想请教下，我只想绘制深圳的热力图？有没有对应的说明呢？

**Comment by chenjiandongx** [comment]
@suuuch 
Geo 的地图需要自己提供经纬度

**Comment by suuuch** [comment]
@chenjiandongx 嗯嗯，我有经纬度的，最后还是用了百度地图的API，因为希望精确到街道，谢谢。这个包非常给力了。大神膜拜一下。。

**Comment by chenjiandongx** [comment]
后面会对 Geo 进行改善的，会增加用户自己提供经纬度的设置选项的

**Comment by chfw** [comment]
这个图例怎么样？

<img width="868" alt="screen shot 2017-08-28 at 00 40 31" src="https://user-images.githubusercontent.com/4280312/29755070-9bc9ae70-8b89-11e7-9bf2-bec09cb5f1a1.png">
