### ISSUE TITLE
能否对DataFrame多列数据同时自动渲染

### ISSUE THREAD

**Issue by morgengu** [chenjiandongx/pyecharts#71]
现在每个数据值渲染，都用单独add（）的方式。如果一个DataFrame有50列，可能就要加49次。能不能设，一个DataFrame加入，默认index为轴，也可以指定某一列为轴，其他数据自动识别，形成多数据渲染，这样就方便高效得多了。

**Comment by chenjiandongx** [comment]
每个 add() 都会生成一个新的图例，如果你所有列的处理逻辑都是一样的，那就用 for 循环吧。

**Comment by morgengu** [comment]
谢谢回复，就是觉得稍显不pythonic。个人觉得pyecharts可以定位于：用法简约，快速，美观，较高的可定制性（完全定制echart，可以直接用js了）。80%的人一般只用那20%的功能，如果加强对pandas的契合，我觉得完全有可能成为pandas的标准化可视化包。感谢作者的辛勤劳动，包更新很快，让人惊喜。

**Comment by chenjiandongx** [comment]
@morgengu 
pyecharts 会尽量提供多一些配置参数 让其拥有更好的可定制性
