### ISSUE TITLE
散点图x坐标不支持非数字值？

### ISSUE THREAD

**Issue by August-Ghost** [chenjiandongx/pyecharts#72]
在绘制散点图的时候发现x坐标不支持非数字值。
```
from pyecharts import Scatter
scatter = Scatter("test")
scatter.add("scatter_title",["2016-01-01", "2016-01-02"], [1, 2])
scatter.render_notebook()
```

会出现如图情况：
![default](https://user-images.githubusercontent.com/15943189/29034999-b74fd5c4-7bcc-11e7-8053-5be3d63781ba.PNG)

但如果将散点图叠加到线图上， 当散点图的x坐标与线图x坐标相同时， 此时散点图可正常显示显示：
![2](https://user-images.githubusercontent.com/15943189/29035372-ee8ebe5a-7bcd-11e7-8291-ca11c86481e1.PNG)

**Comment by chenjiandongx** [comment]
下个版本会提供设置选项解决这个问题的。

**Comment by August-Ghost** [comment]
好的，了解
