### ISSUE TITLE
Geo 图形下，部分城市的坐标无法获得，导致无法绘图

### ISSUE THREAD

**Issue by miaozaiye** [chenjiandongx/pyecharts#74]
目前发现以下城市的坐标无法获得：

['深圳', '杭州', '广州', '成都', '武汉', '南京', '西安', '长沙', '厦门', '郑州', '苏州', '合肥', '福州', '大连', '青岛', '沈阳', '石家庄', '无锡', '珠海', '昆明', '太原', '南昌', '南宁', '哈尔滨', '宁波', '贵阳', '东莞', '长春', '佛山', '常州', '温州', '呼和浩特', '乌鲁木齐', '兰州', '中山', '海口', '汕头', '烟台', '嘉兴', '徐州', '潍坊', '绍兴', '洛阳', '惠州', '泉州', '桂林', '香港', '临沂', '绵阳', '淄博', '唐山', '新加坡', '江门', '台州', '银川', '保定', '芜湖', '加拿大', '新西兰', '柳州', '扬州', '澳大利亚', '济宁', '湖州', '镇江', '泰安', '邢台', '东营', '遵义', '揭阳', '邯郸', '西宁', '湘潭', '吉林', '湛江', '呼伦贝尔','泰州', '枣庄', '宜昌', '临汾', '岳阳', '开封', '马鞍山', '安阳', '三亚', '营口', '舟山', '赤峰', '淮安', '延边朝鲜', '宝鸡', '大庆', '黄冈', '澳门', '自贡',  '日照', '玉溪', '德州', '肇庆', '衡水', '宜宾', '大同', '平顶山', '阳泉', '咸阳', '鞍山', '晋中', '攀枝花', '德阳', '衢州', '株洲', '红河哈尼', '张家口', '滨州', 
 '大理白族', '沧州', '拉萨', '南充', '巴彦淖尔', '张家界', '河源',  '牡丹江', '清远', '丹东', '葫芦岛', '黔东南苗',
 '盘锦', '云浮', '荷兰', '楚雄彝族',  '抚州', '固原',  '菏泽', '茂名',  '昌都', '克拉玛依', '常德', '林芝',
 '阿拉善盟', '广安',  '汕尾', '齐齐哈尔', '长治', '阳江',  '本溪', '湘西土家']

**Comment by chenjiandongx** [comment]
请问你的 pyecharts 是哪个版本的？

**Comment by chenjiandongx** [comment]
pyecharts.__version__ 可以看到

**Comment by miaozaiye** [comment]
你好，版本是 '0.1.9.1'

**Comment by chenjiandongx** [comment]
试试最新版本吧 pip install pyecharts==0.1.9.2

**Comment by miaozaiye** [comment]
一直无法安装成功，提示

>  raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

**Comment by chenjiandongx** [comment]
看起来像是你自己网络的问题

**Comment by chenjiandongx** [comment]
@miaozaiye 
``` pip install pyecharts==0.1.9.4``` 安装最新版本吧
