### ISSUE TITLE
请问可以在同一个html页面显示多个图吗

### ISSUE THREAD

**Issue by YichiHuang** [chenjiandongx/pyecharts#76]
如题

**Comment by chenjiandongx** [comment]
请参考用户自定义部分

**Comment by YichiHuang** [comment]
您好，我看的用户自定义部分，不过显示的是readme.md

**Comment by chenjiandongx** [comment]
请将文档拉到下面就可以看到用户自定义了

**Comment by YichiHuang** [comment]
我点击用户自定义，显示的页面是：[https://github.com/chenjiandongx/pyecharts/blob/master/README.md#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89](url)

**Comment by YichiHuang** [comment]
我点击用户自定义，显示的页面是https://github.com/chenjiandongx/pyecharts/blob/master/README.md#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by chenjiandongx** [comment]
@YichiHuang 链接已修复

**Comment by YichiHuang** [comment]
Thanks~

**Comment by zhangyi7456** [comment]
请问from pyechasrts import Page 载入Page失败了

**Comment by YichiHuang** [comment]
卸载原版本，下载最新版本，重新安装

**Comment by chenjiandongx** [comment]
Page 是我 release 后才加上去的 所以0.1.9.3 版本是没有的 等0.1.9.4版本吧 或者你现在使用源码安装就有

**Comment by zhangyi7456** [comment]
好的，谢谢两位。最近一直在跟踪使用，我是做报告的，感觉很好

**Comment by chenjiandongx** [comment]
请执行 pip install pyecharts==0.1.9.4 下载最新版本，已加入 Page()

**Comment by marciorf** [comment]
Any chance to create a render_embed version of page.render() ?
