### ISSUE TITLE
更新最新版本之后，无法再pycharm中直接运行html了

### ISSUE THREAD

**Issue by dengyingguo** [chenjiandongx/pyecharts#82]
更新最新版本之后，无法再pycharm中直接运行html了

**Comment by chfw** [comment]
结论需要有实验数据。能扩展一下吗。如何看的html,有什么什么报错，什么症状。

**Comment by chenjiandongx** [comment]
@dengyingguo 
无法再 pycharrm 中直接运行 html 是什么意思？ pyecharts 具体是哪个版本？

**Comment by dengyingguo** [comment]
最新版本，0.1.9.4。无 open in  Browser  这一项
![image](https://user-images.githubusercontent.com/24351777/29210220-0a927af2-7ec5-11e7-8c04-e5c7cc47ceb9.png)

![image](https://user-images.githubusercontent.com/24351777/29210230-15b490d2-7ec5-11e7-95b2-3042ce63491a.png)

**Comment by dengyingguo** [comment]
graph3.html 可以直接运行，其原因该html是在版本0.1.9.2中生成的

**Comment by chenjiandongx** [comment]
@dengyingguo 
这跟版本没关系吧 只要是后缀名为 .html 的应该都能被识别吧 我这边 0.1.9.4 是可以的

**Comment by dengyingguo** [comment]
@chenjiandongx   
那可能是我py或者pycharms的问题啦， 问题不大，直接文件中找到去打开也可以的。略繁琐而已，无伤大雅。
