### ISSUE TITLE
pyecharts是否支持关系图

### ISSUE THREAD

**Issue by linfanli** [chenjiandongx/pyecharts#83]
pyecharts是支持百度关系图，示例如下
[人物关系：乔布斯](http://echarts.baidu.com/echarts2/doc/example/force1.html)
<img width="763" alt="2017-08-11 2 05 59" src="https://user-images.githubusercontent.com/16367420/29202810-2b9d2c46-7e9e-11e7-8ead-de7a7801f3e7.png">

**Comment by chenjiandongx** [comment]
关系图请仔细阅读文档
