### ISSUE TITLE
jupyter notebook 显示不出图

### ISSUE THREAD

**Issue by fzhdou** [chenjiandongx/pyecharts#84]
from pyecharts import Bar
bar=("test")
bar.add("t",["1","2","3"],[1,2,3])
bar
在out处只有白屏，但是用bar.render()可以生成图片，这是怎回事啊？

**Comment by chenjiandongx** [comment]
@fzhdou 
请问你使用的是什么版本 ``` pyecharts.__version__ ``` 可以查看

**Comment by fzhdou** [comment]
用的是最新版

**Comment by chenjiandongx** [comment]
@fzhdou 
是所有图都显示不出来吗 还是3D图显示不出来

**Comment by fzhdou** [comment]
所有图都不行

**Comment by chenjiandongx** [comment]
@fzhdou 
你用 ```pip install pyecharts==0.1.9.2``` 下载回这个版本试一下

**Comment by emailhy** [comment]
@chenjiandongx @fzhdou 
和防火墙有关系， render() 到local 可以 ， 但是用notebook 还是要从cdn获取js， 能否把notebook 的render改为从本地js  load，

**Comment by chenjiandongx** [comment]
@emailhy 
请问你也是 notebook 无法显示图形吗

**Comment by fzhdou** [comment]
好像是不能联网的的机器就不行，我用另一台联网的电脑试了就没问题

**Comment by chenjiandongx** [comment]
@fzhdou 
正常 因为 notebook 本来就是设置要联网的

**Comment by zhangyi7456** [comment]
@chenjiandongx 大神，请教个问题，最近在用pyechats画图，怎么用git安装你最新的库啊，我用pip只会安装你放出来的版本，有些最新的功能没法用😯，

**Comment by chenjiandongx** [comment]
@zhangyi7456 
如果急用的话就采用源码安装吧 README.md 文档有写，不急的话就再等等，新版本预计明天会发布

**Comment by chenjiandongx** [comment]
新版本已更新 https://github.com/chenjiandongx/pyecharts/blob/master/changelog.md
