### ISSUE TITLE
最新版的，jupyter notebook 显示不出图

### ISSUE THREAD

**Issue by huihui7987** [chenjiandongx/pyecharts#85]
显示空白

**Comment by chenjiandongx** [comment]
@huihui7987 
请问是什么图显示不出来 是某一种还是所有图都显示不出来

**Comment by huihui7987** [comment]
目前是scatter3d显示不出来

**Comment by chenjiandongx** [comment]
@huihui7987 
是 0.1.9.4 版本吗？ 三种 3D 图均显示不出来吗？

**Comment by chfw** [comment]
Please check if webgl.js or the host is accessible. 

http://oog4yfyu0.bkt.clouddn.com/echarts-gl.js

Here's what I got from my end:
![image](https://user-images.githubusercontent.com/4280312/29206505-21c89666-7e7a-11e7-9e13-7cea0a0a5660.png)

And here's the response when I use browser itself:

![image](https://user-images.githubusercontent.com/4280312/29206567-5bb003dc-7e7a-11e7-98a2-93124111a1a4.png)

**Comment by chfw** [comment]
right click on the page and click 'inspect'. please then click 'console' and see if you get any javascript errors.

**Comment by huihui7987** [comment]
3D图均显示不出来，python3.6,Mac,jupyter5.0.0

**Comment by chenjiandongx** [comment]
@huihui7987 
试试下载回 ```pip install pyecharts==0.1.9.2``` 这个版本看一下行不行

**Comment by chfw** [comment]
mine starts working, both 0.1.9.2 and 0.1.9.4

**Comment by huihui7987** [comment]
抱歉，更新后竟然还是0.1.9.1版本的所以显示不出来，现在手动更新到0.1.9.4可以了，谢谢您

**Comment by chenjiandongx** [comment]
ok
