### ISSUE TITLE
Bar 3D 坐标轴调节interval没有作用

### ISSUE THREAD

**Issue by permissionx** [chenjiandongx/pyecharts#86]

**Comment by chenjiandongx** [comment]
Bar 3D？

**Comment by permissionx** [comment]
而且坐标轴标签字体下半部分显示不出来。

**Comment by chenjiandongx** [comment]
intervel 对 3D 图是无效的，只对平面直角坐标系有效

**Comment by permissionx** [comment]
好像坐标轴标题也不能改的样子。

**Comment by chenjiandongx** [comment]
等下个版本吧 会提供 name intervel 等一系列配置参数的

**Comment by permissionx** [comment]
非常感谢！

**Comment by chenjiandongx** [comment]
@permissionx 
已更新文档 请阅读通用配置项 axis3D 部分。还没更新至 pypi 想使用该新功能可以使用源码安装

**Comment by WenyinWei** [comment]
嗯，有个小问题，在使用 Bar 3D 时即使设置了 

```xaxis3d_opts=opts.Axis3DOpts(type_="category", name='m', data=m_)```

成功修改了坐标轴的名字，但是鼠标移到一个 Bar 上面标签还是显示的 `x=blabla, y=blabla`，能否在显示的时候就直接显示坐标轴的名字。
