### ISSUE TITLE
强烈建议整合到Django或者flask里面去。

### ISSUE THREAD

**Issue by ideaplat** [chenjiandongx/pyecharts#9]

**Comment by chenjiandongx** [comment]
嗯 等我看看要怎么实现 可以的话后期版本会实现的

**Comment by ideaplat** [comment]
后期的计划有吗？

**Comment by Harold2017** [comment]
flask 的 render_template里面可以直接引入render后的html文件的呀， 不用专门整合吧

**Comment by Harold2017** [comment]
每次请求自动生成一个chart，请求结束之后再删除，也能用起来，不过效率确实很低

**Comment by marciorf** [comment]
I would like this

**Comment by chenjiandongx** [comment]
@ideaplat 
@marciorf 
I will seriously consider your advice

**Comment by chfw** [comment]
I am interested to take this issue forward and integrate pyecharts with both frameworks.

**Comment by chenjiandongx** [comment]
@chfw six six six, can you give me your email?

**Comment by chfw** [comment]
All in this file: https://github.com/pyexcel/pyexcel-commons/blob/master/config/pyexcel.yaml

**Comment by chenjiandongx** [comment]
@chfw 
hey, can you give me your email?

**Comment by chenjiandongx** [comment]
版本已更新为 0.1.9.3，新版本集成了 Flask& Django

**Comment by marciorf** [comment]
you are the best

**Comment by chfw** [comment]
please note an update is coming from version 0.3.2: https://github.com/pyecharts/pyecharts/pull/403
