### ISSUE TITLE
ImportError: cannot import name 'Grid' 'Overlap'

### ISSUE THREAD

**Issue by kent119** [chenjiandongx/pyecharts#92]
你好，我第一次用pyecharts。使用其他的函数都没问题，只有在试图调用 Grid 和 Overlap 的时候出现了一样的问题。请问是notebook的原因吗，该如何解决？谢谢。

系统：Ubuntu 16.04
环境： conda + jupyter notebook + py3.6
版本： 最新版本 pyecharts

输入：
`from pyecharts import Grid`

错误提示：
```
ImportErrorTraceback (most recent call last)
<ipython-input-71-c5312a0f8bf3> in <module>()
----> 1 from pyecharts import Grid

ImportError: cannot import name 'Grid'
```

输入：
`from pyecharts import Overlap`

错误提示：
```
ImportErrorTraceback (most recent call last)
<ipython-input-73-fa1ed03d5292> in <module>()
----> 1 from pyecharts import Overlap

ImportError: cannot import name 'Overlap'
```

**Comment by chenjiandongx** [comment]
@kent119 
你好，是这样的。你现在所看到的文档是下个版本的，下个版本预计今天内会发布，所以文档先更新了。
如果要使用的话你也可以把原先 pip 安装的先给卸载了 再采用源码安装 这样就可以使用 Gird Page 等自定义类了，不然就请再等一下，发布之后就可以采用 pip 安装了。

**Comment by kent119** [comment]
原来是这样啊，那我就等着更新吧，很期待这两个新功能。谢谢。
