### ISSUE TITLE
能否直接生成静态图片呢？

### ISSUE THREAD

**Issue by hAcKlyc** [chenjiandongx/pyecharts#94]
有些地方使用需要直接生成静态图片……

**Comment by chenjiandongx** [comment]
图片自己按下载按钮下载吧 不然就自己截图

**Comment by chfw** [comment]
我刚写好一个包[pyecharts-snapshot](https://github.com/chfw/pyecharts-snapshot)， 可是帮助一步到位。请按照[安装细节](https://github.com/chfw/pyecharts-snapshot#installation), 你就可以用下面的语句了:

```
from pyecharts_snapshot.main import make_a_snapshot

...
somechart.render()
make_a_snapshot('render.html', 'cool_snapshot.png')

```

或者：

`$ snapshot render.html`

**Comment by chfw** [comment]
我做了另一个工具[echarts-scrappeteer](https://github.com/chfw/echarts-scrappeteer)，可以一次性下载网页里的所有echarts.


```
$ scrappeteer https://chfw.github.io/echarts-china-cities-js/preview.html
Found 363 echarts
```

![demo](https://user-images.githubusercontent.com/4280312/30129987-a55757e0-933f-11e7-98ac-3571fae691ce.gif)
