### ISSUE TITLE
更新到9.5之后jupyter不会直接显示图形

### ISSUE THREAD

**Issue by zhangyi7456** [chenjiandongx/pyecharts#97]
大神你好，我是从9.4过来的，9.4可以直接用line的方式在jupyter里直接显示图形。但是用pip升级9.5后就不再显示了，求教

**Comment by anyang001** [comment]
同上

**Comment by chenjiandongx** [comment]
对本库的现有用户来说，0.1.9.5 版本的离线模式要求： 1）老版本已完全卸载 2）您现有的 notebook 文档需要刷新并重新运行。

卸载  `pip uninstall pyecharts`
安装  `pip install pyecharts==0.1.9.5`

离线模式工作原理：pyecharts 自动把 echarts 脚本文件装在了 jupyter nbextensions 文件夹下面。以下代码可以告诉你 pyecharts 网页脚本是否装到了 Jupyter 里面：

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/jaska/.jupyter/nbconfig
    notebook section
      echarts/main  enabled 
      - Validating: OK
```
状态为 OK 则表明 notebook extension 安装成功，建议重新刷新运行原有的 notebook 文件。

**Comment by zhangyi7456** [comment]
@chenjiandongx 运行看了一下，没有后面那句，没安装成功啊

**Comment by chenjiandongx** [comment]
请把状态贴上来

**Comment by zhangyi7456** [comment]
![1502862667 1](https://user-images.githubusercontent.com/26074889/29349209-1444804e-828b-11e7-9c31-939586af662c.jpg)

**Comment by chenjiandongx** [comment]
卸载 pip uninstall pyecharts
安装 pip install pyecharts==0.1.9.5
@zhangyi7456 
确定你是这样执行过的吗？

**Comment by zhangyi7456** [comment]
解决了！早上的时候我已经重新装过了，刚才又重新更新了pyecharts所有的脚本文件。虽然依旧没有显示      echarts/main  enabled 
      - Validating: OK
但是可以显示图了。

**Comment by chenjiandongx** [comment]
enjoy it!

**Comment by zhangyi7456** [comment]
另一个是，Windows里命令符，这一句nbextension好像没有“s”才能正常运行;
$ jupyter nbextensions install echarts --user

**Comment by chenjiandongx** [comment]
谢谢提醒 已修改

**Comment by zhangyi7456** [comment]
@chenjiandongx 因为共同的爱好聚在一起，感谢楼主作者的努力优化，一直在跟随，祝好

**Comment by anyang001** [comment]
@chenjiandongx jupyter nbextension list检查没问题，但是图形还是显示不出来。python我都重装了一次。。。

**Comment by anyang001** [comment]
![image](https://user-images.githubusercontent.com/31056083/29352967-3e3ef158-829b-11e7-8334-1c9aa122dc27.png)
![image](https://user-images.githubusercontent.com/31056083/29353002-5d082a64-829b-11e7-800e-87ce60dacb4f.png)

**Comment by kent119** [comment]
+1

我和楼上一样，只不过我的jupyter notebook是装在另一台服务器的Ubuntu的Docker里。
重装过notebook， python，但是情况和楼上 @anyang001  一模一样。

**Comment by chfw** [comment]
Try: refresh your page and then click 'Cell->Run all'. Please also remember that: each failed page will be cached for 10 minutes by Jupyter. So either you could open a new test page and run the same code again or wait for a while and come back.

And if echarts has been installed well, you can test it using this link: 
http://localhost:8888/nbextensions/echarts/echarts.min.js

Debug: right click on the big white area. Please show me the <script>...</script> area.
<img width="597" alt="screen shot 2017-08-16 at 09 17 29" src="https://user-images.githubusercontent.com/4280312/29354092-4c4eecee-8264-11e7-98bb-06ec1b4c06b6.png">

**Comment by anyang001** [comment]
<script>
  | require.config({
  |  
  | urlArgs: "v=20170816164117",
  |  
  | baseUrl: '/static/',
  | paths: {
  | 'auth/js/main': 'auth/js/main.min',
  | custom : '/custom',
  | nbextensions : '/nbextensions',
  | kernelspecs : '/kernelspecs',
  | underscore : 'components/underscore/underscore-min',
  | backbone : 'components/backbone/backbone-min',
  | jquery: 'components/jquery/jquery.min',
  | bootstrap: 'components/bootstrap/js/bootstrap.min',
  | bootstraptour: 'components/bootstrap-tour/build/js/bootstrap-tour.min',
  | 'jquery-ui': 'components/jquery-ui/ui/minified/jquery-ui.min',
  | moment: 'components/moment/moment',
  | codemirror: 'components/codemirror',
  | termjs: 'components/xterm.js/dist/xterm',
  | typeahead: 'components/jquery-typeahead/dist/jquery.typeahead.min',
  | },
  | map: { // for backward compatibility
  | "*": {
  | "jqueryui": "jquery-ui",
  | }
  | },
  | shim: {
  | typeahead: {
  | deps: ["jquery"],
  | exports: "typeahead"
  | },
  | underscore: {
  | exports: '_'
  | },
  | backbone: {
  | deps: ["underscore", "jquery"],
  | exports: "Backbone"
  | },
  | bootstrap: {
  | deps: ["jquery"],
  | exports: "bootstrap"
  | },
  | bootstraptour: {
  | deps: ["bootstrap"],
  | exports: "Tour"
  | },
  | "jquery-ui": {
  | deps: ["jquery"],
  | exports: "$"
  | }
  | },
  | waitSeconds: 30,
  | });
  |  
  | require.config({
  | map: {
  | '*':{
  | 'contents': 'services/contents',
  | }
  | }
  | });
  |  
  | // error-catching custom.js shim.
  | define("custom", function (require, exports, module) {
  | try {
  | var custom = require('custom/custom');
  | console.debug('loaded custom.js');
  | return custom;
  | } catch (e) {
  | console.error("error loading custom.js", e);
  | return {};
  | }
  | })
  | </script>

**Comment by anyang001** [comment]
![image](https://user-images.githubusercontent.com/31056083/29355019-ff65818e-82a1-11e7-8af2-0c2251cb1634.png)

**Comment by chfw** [comment]
Nope, you will need to right click on **output area** after your python codes and click **inspect**. 

But have you re-run it?

**Comment by anyang001** [comment]
![image](https://user-images.githubusercontent.com/31056083/29355308-1a51ae40-82a3-11e7-9622-54c385972e4d.png)
i  run the same code again

**Comment by chfw** [comment]
恭喜，0.1.9.5是已经启用。那你点击这个，看你的浏览器能不能得到echarts.min.js

http://localhost:8888/nbextensions/echarts/echarts.min.js

**Comment by anyang001** [comment]
出错了
404 : Not Found
You are requesting a page that does not exist!

**Comment by kent119** [comment]
+1

404 : Not Found
You are requesting a page that does not exist!

**Comment by anyang001** [comment]
@kent119 看来我们错误完全一样

**Comment by kent119** [comment]
![image](https://user-images.githubusercontent.com/18453664/29356152-ec80bab2-82a5-11e7-83c2-01e136ada0f0.png)

看看这里的信息有用吗

**Comment by chfw** [comment]
那就是地图没有装上，这也是问题所在。0.1.9.5会自动装地图，可是不知道为何装不上。请告诉你们装0.1.9.5的步骤。请你告诉我你的运行环境： jupyter version，操作系统 并且运行这个：

`jupyter --paths`

**Comment by chfw** [comment]
而且Jupyter-notebook必须先存在。

**Comment by anyang001** [comment]
操作系统是win10
$jupyter --paths:
C:\Users\41600>jupyter --paths
config:
    C:\Users\41600\.jupyter
    C:\Users\41600\Anaconda3\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\41600\AppData\Roaming\jupyter
    C:\Users\41600\Anaconda3\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\41600\AppData\Roaming\jupyter\runtime

**Comment by anyang001** [comment]
我是先按照Anaconda3-4.4.0-Windows-x86_64.exe，自带jupyter 然后通过pip intall pyecharts安装的0.1.9.5

**Comment by anyang001** [comment]
先安装的Anaconda3-4.4.0-Windows-x86_64，自带jupyter
通过pip install pyecharts 安装的0.1.9.5

**Comment by anyang001** [comment]
昨天安装的时候都可以用，后面因为VPN的问题（国内外网站都开代理，当时不知道这个会导致问题）导致chrome打不开jupyter，就将python卸载后重装，重装后就不行了。

**Comment by kent119** [comment]
我出现的问题 @anyang001 一模一样，不过系统不一样。
系统：Ubuntu 16.04
安装：在 docker 里新开的 container 自带 jupyter， 然后 `pip install pyecharts==0.1.9.5` （如果装旧版本就没问题，不过新版本需要用 Grid 的功能）

```
$jupyter --paths:
config:
    /root/.jupyter
    /opt/conda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /root/.local/share/jupyter
    /opt/conda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /root/.local/share/jupyter/runtime
```

**Comment by anyang001** [comment]
我现在装回旧版本0.1.9.2也不行

**Comment by chenjiandongx** [comment]
@anyang001 
请问你现在是否也开着代理呢

**Comment by anyang001** [comment]
开不开代理都运行过，还是没有图。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/29357500-566dc8d0-82aa-11e7-9967-f1908f285da0.png)
该目录下有内容吗

**Comment by anyang001** [comment]
![image](https://user-images.githubusercontent.com/31056083/29357735-2b53377e-82ab-11e7-805b-15abecdac4c6.png)
我没有这个文件夹。。。。。。

**Comment by chenjiandongx** [comment]
这应该就是你显示不出图的原因

**Comment by anyang001** [comment]
但是我重装过几次python和pyecharts都还是不行，不知道是什么原因

**Comment by chenjiandongx** [comment]
@anyang001 
抱歉 应该是我打的包点问题 我来检查一下 请稍等

**Comment by chenjiandongx** [comment]
@kent119 
@anyang001 
[pyecharts-0.1.9.5.tar.gz](https://github.com/chenjiandongx/pyecharts/files/1227839/pyecharts-0.1.9.5.tar.gz)
试试 pip 安装这个 tar 包

**Comment by anyang001** [comment]
终于可以，十分感谢 @chenjiandongx @chfw 
这个开源项目非常酷，希望越来越好。

**Comment by chenjiandongx** [comment]
@anyang001 希望越来越酷 👏

**Comment by kent119** [comment]
@chenjiandongx 可以用了。谢谢，非常喜欢这个项目！

**Comment by chfw** [comment]
jupyter-pip do not have wheel support. Late to find it: https://github.com/jdfreder/jupyter-pip/issues/15

**Comment by sooluck** [comment]
我用的VS Code升级9.5以后调用line没有生成网页，只能用render，请问这个是什么问题？

**Comment by chenjiandongx** [comment]
@sooluck 
这点在文档中已经说明 调用实例是在 jupyter-notebook 中显示图表的 而生成网页用的是 render()，请仔细阅读文档。

**Comment by chenjiandongx** [comment]
版本已更新 请各位更新到 0.1.9.6 版本
