### ISSUE TITLE
如何设置tooltip？

### ISSUE THREAD

**Issue by oceanzhangyang** [chenjiandongx/pyecharts#98]
没有找到设置tooltip的选项，目前比较笨的方法是在base.py直接修改。是否有更好的方式？

**Comment by chenjiandongx** [comment]
目前暂未提供 tooltip 选项 如果有需要您可以自行改进 base.py
后续版本可以考虑加入 tooltip 设置选项

**Comment by chenjiandongx** [comment]
@oceanzhangyang 
请问你对 tooltip 的需求是什么？
