### ISSUE TITLE
如何生成多Y轴的图呢？

### ISSUE THREAD

**Issue by youyoude** [chenjiandongx/pyecharts#99]
需要绘制 一个类似于echart官网———多 Y 轴示例 的图 ，怎么弄呢？

**Comment by chenjiandongx** [comment]
建议看看 Parallel 图

**Comment by chenjiandongx** [comment]
@youyoude 
请问是否为 https://github.com/chenjiandongx/pyecharts/issues/95

**Comment by youyoude** [comment]
好，  谢谢 ！ @chenjiandongx

**Comment by chenjiandongx** [comment]
@youyoude 
请看 https://github.com/chenjiandongx/pyecharts/issues/95
